#!/usr/bin/env python3
# Copyright (c) 2026 Seth Kitchen, PE
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
"""Reproduce the fixed-count quadrant-zero stored GL/trig coefficient table.

Python standard library only. Default and --check are read-only. No evaluator,
compiler, subprocess, network, private snapshots, or geometry sample is used.
"""
import argparse
from fractions import Fraction
import hashlib
import json
import os
from pathlib import Path
import re
import struct
import sys

sys.dont_write_bytecode = True
import ideal_projection
import source_contracts
import sum2_contracts
import sum2_guard_contracts
F = Fraction
ROOT = Path(__file__).resolve().parents[2]
PACKAGE = Path('tools/carla_lane_oracle')
PINS = PACKAGE / 'spiral-moment-pins.json'
DATA = Path('extensions/carla/spiral_moment_table_data.mojo')
SIGN = 1 << 63
INFINITY = 0x7FF0000000000000
MAX_FINITE = INFINITY - 1
WORD_COUNT = 64 * 22 * 2
ARRAY_SPECS = {
    '_GL_NODES': ('extensions/carla/geometry.mojo', 5),
    '_GL_WEIGHTS': ('extensions/carla/geometry.mojo', 5),
    '_COS_COEFFICIENTS': ('extensions/carla/curve_trig.mojo', 11),
    '_SIN_COEFFICIENTS': ('extensions/carla/curve_trig.mojo', 11),
}
SCALAR_NAMES = {'_PHASE_LIMIT', '_INV_HALF_PI', '_HALF_PI_HIGH', '_HALF_PI_LOW'}
BLOCK_PATHS = {
    'geometry_trig_aliases': 'extensions/carla/lane_geometry.mojo',
    'scalar_spiral': 'extensions/carla/lane_geometry.mojo',
    'scalar_horner': 'extensions/carla/curve_trig.mojo',
    'scalar_sincos': 'extensions/carla/curve_trig.mojo',
    'scalar_trig_wrappers': 'extensions/carla/curve_trig.mojo',
    'ideal_sincos_selector': 'extensions/carla/curve_trig.mojo',
    'ideal_horner': 'extensions/carla/curve_trig.mojo',
    'ideal_sincos_branch': 'extensions/carla/curve_trig.mojo',
    'ideal_spiral': 'extensions/carla/curve_bounds.mojo',
    'ideal_uncertain': 'extensions/carla/curve_trig.mojo',
}
BLOCK_BOUNDARIES = {
    'geometry_trig_aliases': ('from extensions.carla.curve_trig import (', 'from std.math import ceil'),
    'scalar_spiral': ('def _lane_spiral(geometry: RoadGeometry, d: Float64)', 'def _lane_geometry_derivative_at('),
    'scalar_horner': ('def _scalar_polynomial[', 'def _jet_polynomial['),
    'scalar_sincos': ('@no_inline\ndef _curve_sincos(value: Float64)', 'def _curve_sin(value: Float64)'),
    'scalar_trig_wrappers': ('def _curve_sin(value: Float64)', '@no_inline\ndef _curve_atan('),
    'ideal_sincos_selector': ('def _sincos_expression[', 'def _constant_sincos_jet('),
    'ideal_horner': ('def _expression_polynomial[', '@no_inline\ndef _curve_sincos('),
    'ideal_sincos_branch': ('def _sincos_branch_expression[', 'def _uncertain(value:'),
    'ideal_spiral': ('def _spiral_expression[', 'def _sample_index('),
    'ideal_uncertain': ('def _uncertain_expression[', 'def _sincos_jet('),
}
ROUTING_PATHS = {
    'ideal_caller': 'extensions/carla/curve_bounds.mojo',
    'trig_dependencies': 'extensions/carla/curve_trig.mojo',
    'canonical_scalar': 'extensions/carla/lane_geometry.mojo',
    'stored_geometry': 'extensions/carla/geometry.mojo',
}
DEPENDENCIES = {
    'group': 'stored_arithmetic',
    'pin_file': 'tools/carla_lane_oracle/runtime-source-pins.json',
    'paths': ['extensions/carla/curve_interval.mojo'] + [path for path in
              source_contracts.GROUP_PATHS['canonical_accumulation']
              if path != 'extensions/carla/curve_interval.mojo'],
    'additional_groups': ['canonical_accumulation'],
    'guard_pin_file': str(sum2_guard_contracts.PINS),
}
PIN_KEYS = {'schema', 'scope', 'arrays', 'scalars', 'blocks', 'rounded_node_sums',
            'ideal_projection', 'routing', 'dependencies'}
HEADER = '''# Copyright (c) 2026 Seth Kitchen, PE
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
# GENERATED by tools/carla_lane_oracle/spiral_moments.py. Do not edit words.
# Replay: python3 -B tools/carla_lane_oracle/spiral_moments.py --check
# Proof and limits: tools/carla_lane_oracle/spiral-moments.md
# Exact stored GL/trig polynomial only; no fitted or ideal-sin/cos data.
# Layout: count 1..64; cosine 0..10 then sine 0..10; low then high.
# 64 * 22 * 2 UInt64 words = 22,528 raw payload bytes.
# Bound as ref global_constant[_SPIRAL_MOMENT_WORDS](), never materialize.

'''


class CheckError(ValueError):
    """An input, source pin, coefficient, endpoint, or format is unsupported."""


def require(condition, message):
    # Do not use assert for verification: python -O must not disable checks.
    if not condition:
        raise CheckError(message)


def digest(data):
    return hashlib.sha256(data).hexdigest()


def hexword(word):
    return f'0x{word:016X}'


def fraction_of_word(word):
    require(type(word) is int and 0 <= word < 1 << 64, 'invalid UInt64 word')
    exponent = (word >> 52) & 0x7FF
    require(exponent != 0x7FF, 'nonfinite binary64 word')
    significand = word & ((1 << 52) - 1)
    shift = -1074
    if exponent:
        significand += 1 << 52
        shift = exponent - 1023 - 52
    value = F(significand << shift) if shift >= 0 else F(significand, 1 << -shift)
    return -value if word & SIGN else value


def next_up(word):
    if word in (0, SIGN):
        return 1
    return word - 1 if word & SIGN else word + 1


def next_down(word):
    if word in (0, SIGN):
        return SIGN | 1
    return word + 1 if word & SIGN else word - 1


def verify_bracket(value, low, high):
    require(fraction_of_word(low) <= value <= fraction_of_word(high),
            'endpoints do not enclose exact coefficient')
    following, preceding = next_up(low), next_down(high)
    require(following == INFINITY or fraction_of_word(following) > value,
            'lower endpoint is not greatest-below (or equal)')
    require(preceding == (SIGN | INFINITY) or fraction_of_word(preceding) < value,
            'upper endpoint is not least-above (or equal)')
    if value == 0:
        require((low, high) == (SIGN, 0), 'zero bracket must be [-0, +0]')


def bracket(value):
    """Exact integer lattice floor/ceil; no host floating-point conversion."""
    value = F(value)
    if not value:
        return SIGN, 0
    positive = abs(value)
    require(positive <= fraction_of_word(MAX_FINITE), 'binary64 overflow')
    numerator, denominator = positive.numerator, positive.denominator
    exponent = numerator.bit_length() - denominator.bit_length()
    if (numerator < denominator << exponent if exponent >= 0
            else numerator << -exponent < denominator):
        exponent -= 1
    shift = max(exponent - 52, -1074)
    if shift >= 0:
        significand = numerator // (denominator << shift)
    else:
        significand = (numerator << -shift) // denominator
    if exponent < -1022:
        low = significand
    else:
        low = ((exponent + 1023) << 52) | (significand - (1 << 52))
    high = low if fraction_of_word(low) == positive else low + 1
    pair = (SIGN | high, SIGN | low) if value < 0 else (low, high)
    verify_bracket(value, *pair)
    return pair


def nearest_even(value):
    if not value:
        return 0
    low, high = bracket(value)
    below, above = fraction_of_word(low), fraction_of_word(high)
    if value - below < above - value:
        return low
    if above - value < value - below:
        return high
    return low if low % 2 == 0 else high


def decimal_word(token):
    value = F(token)
    # Fractions have no signed zero; a source literal does.
    return SIGN if not value and token.startswith('-') else nearest_even(value)


def normalized_block(text):
    """Keep indentation and operation spelling; ignore comments/blank lines."""
    lines = [line.split('#', 1)[0].rstrip() for line in text.splitlines()]
    return '\n'.join(line for line in lines if line.strip()) + '\n'


def selected_block(text, begin, end):
    require(text.count(begin) == 1, 'missing or ambiguous source-block start')
    require(text.count(end) == 1, 'missing or ambiguous source-block end')
    start, stop = text.index(begin), text.index(end)
    require(start < stop, 'moved source-block boundary')
    require((start == 0 or text[start-1] == '\n')
            and (stop == 0 or text[stop-1] == '\n'), 'source-block boundary is not top-level')
    try:
        token_starts = ideal_projection.top_level_source_starts(text)
    except ValueError as error:
        raise CheckError('malformed source-block tokens') from error
    require(all((text.count('\n', 0, offset) + 1, 0) in token_starts
                for offset in (start, stop)), 'source-block boundary is not an actual top-level token')
    preceding = normalized_block(text[:start]).rstrip().splitlines()
    require(not preceding or not preceding[-1].startswith('@'),
            'unbound decorator before source-block start')
    return normalized_block(text[start:stop])


def literal_from_tokens(tokens, description):
    # A single decimal number token with an optional unary sign. Joining
    # arbitrary adjacent tokens would accept malformed two-number spellings.
    require((len(tokens) == 1 and tokens[0][0] == 'NUMBER') or
            (len(tokens) == 2 and tokens[0] in (('OP', '+'), ('OP', '-'))
             and tokens[1][0] == 'NUMBER'), 'unsupported ' + description)
    literal = ''.join(word for kind, word in tokens)
    require(re.fullmatch(r'[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?', literal)
            is not None, 'unsupported ' + description)
    return literal


def parse_array(text, name, size):
    # Match the complete top-level logical declaration, never a bracketed
    # prefix inside a conditional, concatenation, string or executable suffix.
    try:
        statements = ideal_projection.module_statements(text)
    except ValueError as error:
        raise CheckError('malformed constant declaration: ' + name) from error
    matches = [statement for statement in statements
               if statement[:2] == [('NAME', 'comptime'), ('NAME', name)]]
    require(len(matches) == 1, 'missing or ambiguous constant array: ' + name)
    declaration = matches[0]
    header = [('NAME', 'comptime'), ('NAME', name), ('OP', ':'), ('NAME', 'Array'),
              ('OP', '['), ('NAME', 'Float64'), ('OP', ','), ('NUMBER', str(size)),
              ('OP', ']'), ('OP', '='), ('OP', '[')]
    require(declaration[:len(header)] == header and declaration[-1] == ('OP', ']'),
            'unsupported complete constant-array declaration: ' + name)
    literals, entry = [], []
    for token in declaration[len(header):-1]:
        if token == ('OP', ','):
            literals.append(literal_from_tokens(entry, 'constant literal: ' + name))
            entry = []
        else:
            entry.append(token)
    if entry:
        literals.append(literal_from_tokens(entry, 'constant literal: ' + name))
    require(len(literals) == size, 'wrong constant-array shape: ' + name)
    return [decimal_word(literal) for literal in literals]


def verify_inputs(root):
    pins = json.loads((root / PINS).read_text(encoding='utf-8'),
                      object_pairs_hook=source_contracts.unique_keys)
    require(set(pins) == PIN_KEYS, 'wrong top-level pin set')
    require(type(pins['schema']) is int and pins['schema'] == 3, 'unsupported pin schema')
    require(set(pins['arrays']) == set(ARRAY_SPECS), 'wrong constant-array pin set')
    require(set(pins['scalars']) == SCALAR_NAMES, 'wrong scalar pin set')
    require(set(pins['blocks']) == set(BLOCK_PATHS), 'wrong operation-graph pin set')
    require(set(pins['routing']) == set(ROUTING_PATHS), 'wrong routing pin set')
    require(pins['dependencies'] == DEPENDENCIES, 'wrong dependency closure pin')
    constants = {}
    for name, record in pins['arrays'].items():
        require(set(record) == {'path', 'words'}, 'wrong array pin keys: ' + name)
        path, size = ARRAY_SPECS[name]
        require(record['path'] == path and len(record['words']) == size,
                'wrong array pin path/shape: ' + name)
        words = parse_array((root / record['path']).read_text(encoding='utf-8'),
                            name, len(record['words']))
        require([hexword(word) for word in words] == record['words'],
                'stored constant words changed: ' + name)
        constants[name] = [fraction_of_word(word) for word in words]
    require(set(constants) == {'_GL_NODES', '_GL_WEIGHTS',
                               '_COS_COEFFICIENTS', '_SIN_COEFFICIENTS'},
            'wrong constant-array set')
    for name, record in pins['scalars'].items():
        require(set(record) == {'path', 'word'}, 'wrong scalar pin keys: ' + name)
        require(record['path'] == 'extensions/carla/curve_trig.mojo',
                'wrong scalar pin path: ' + name)
        text = (root / record['path']).read_text(encoding='utf-8')
        declarations = ideal_projection.module_statements(text)
        matches = [statement for statement in declarations
                   if statement[:2] == [('NAME', 'comptime'), ('NAME', name)]]
        require(len(matches) == 1, 'missing or ambiguous scalar: ' + name)
        declaration = matches[0]
        prefix = [('NAME', 'comptime'), ('NAME', name), ('OP', '='),
                  ('NAME', 'Float64'), ('OP', '(')]
        require(declaration[:len(prefix)] == prefix and declaration[-1] == ('OP', ')'),
                'unsupported complete scalar declaration: ' + name)
        literal = literal_from_tokens(declaration[len(prefix):-1], 'scalar literal: ' + name)
        require(hexword(decimal_word(literal)) == record['word'],
                'stored scalar word changed: ' + name)
    blocks = {}
    for name, record in pins['blocks'].items():
        require(set(record) == {'path', 'begin', 'end', 'normalized_source', 'sha256'},
                'wrong operation pin keys: ' + name)
        require((record['begin'], record['end']) == BLOCK_BOUNDARIES[name],
                'wrong source-block boundary pin: ' + name)
        require(record['path'] == BLOCK_PATHS[name], 'wrong operation pin path: ' + name)
        current = selected_block((root / record['path']).read_text(encoding='utf-8'),
                                 record['begin'], record['end'])
        expected = record['normalized_source']
        require(digest(expected.encode()) == record['sha256'],
                'inconsistent operation-graph pin: ' + name)
        require(current == expected, 'operation graph changed: ' + name)
        blocks[name] = current
    for name, record in pins['routing'].items():
        require(set(record) == {'path', 'normalized_tokens', 'sha256'},
                'wrong routing pin keys: ' + name)
        require(record['path'] == ROUTING_PATHS[name], 'wrong routing pin path: ' + name)
        expected = record['normalized_tokens']
        require(digest(expected.encode()) == record['sha256'], 'inconsistent routing pin: ' + name)
        current = ideal_projection.module_routing(
            (root / record['path']).read_text(encoding='utf-8'),
            set(ARRAY_SPECS) | SCALAR_NAMES)
        require(current == expected, 'source routing changed: ' + name)
    try:
        source_contracts.verify_group(root, 'stored_arithmetic')
        source_contracts.verify_group(root, 'canonical_accumulation')
        sum2_contracts.verify(root)
    except ValueError as error:
        raise CheckError('stored-half dependency closure: ' + str(error)) from error
    projection = pins['ideal_projection']
    require(set(projection) == {'legacy_normalized_source', 'legacy_sha256',
                               'helper_projections', 'rate_half_commutations',
                               'projected_ast_sha256', 'sum2_auxiliary_declarations',
                               'sum2_term_definitions', 'sum2_auxiliary_updates',
                               'sum2_error_writes', 'sum2_environment_guards'}, 'wrong ideal-projection pin set')
    require(projection['legacy_sha256'] == ideal_projection.LEGACY_SHA256,
            'historical ideal pin digest changed')
    interval = (root / DEPENDENCIES['paths'][0]).read_text(encoding='utf-8')
    marker = 'def _stored_half['
    require(interval.count(marker) == 1, 'missing or ambiguous stored-half declaration')
    helper = interval[interval.index(marker):]
    try:
        result = ideal_projection.verify_projection(
            projection['legacy_normalized_source'], blocks['ideal_spiral'], helper)
    except ValueError as error:
        raise CheckError('ideal half projection: ' + str(error)) from error
    require(all(projection[key] == value for key, value in result.items()),
            'wrong ideal-projection result pins')
    sums = [nearest_even(F(1) + node) for node in constants['_GL_NODES']]
    require([hexword(word) for word in sums] == pins['rounded_node_sums'],
            'rounded 1 + node words changed')
    constants['node_sums'] = [fraction_of_word(word) for word in sums]
    require(sum(constants['_GL_WEIGHTS']) / 2 == F(1) + F(3, 1 << 55),
            'stored zeroth moment must not be normalized to one')
    return constants, pins


def derive_coefficients(constants):
    """All 64 rows, exactly; share only unscaled prefix sums across counts.

    S[k,n] = sum(p<n,i) w[i]*(p+q[i]/2)**(2*k).
    M[k,n] = S[k,n]/(2*n**(2*k+1)). This is algebraic common work only.
    """
    sums = [F(0) for _ in range(22)]
    rows = []
    for count in range(1, 65):
        for node, weight in zip(constants['node_sums'], constants['_GL_WEIGHTS']):
            square = (F(count - 1) + node / 2) ** 2
            power = F(1)
            for index in range(22):
                sums[index] += weight * power
                power *= square
        moments = [value / (2 * count ** (2 * index + 1))
                   for index, value in enumerate(sums)]
        require(moments[0] == F(1) + F(3, 1 << 55), 'zeroth moment drift')
        row = {'count': count}
        for side, key, parity in [('cosine', '_COS_COEFFICIENTS', 0),
                                  ('sine', '_SIN_COEFFICIENTS', 1)]:
            row[side] = []
            for index, coefficient in enumerate(constants[key]):
                exact = coefficient * moments[2 * index + parity]
                endpoints = bracket(exact)
                row[side].append({'exact': str(exact),
                                  'words': [hexword(word) for word in endpoints]})
        rows.append(row)
    return rows


def words_from_rows(rows):
    return [int(word, 16) for row in rows for side in ('cosine', 'sine')
            for coefficient in row[side] for word in coefficient['words']]


def generate_source(rows):
    lines = [HEADER.rstrip('\n'), '',
             'comptime _SPIRAL_MOMENT_WORDS: Array[UInt64, 2816] = [']
    for row in rows:
        lines.append(f'    # Count {row["count"]}')
        for side in ('cosine', 'sine'):
            lines.append('    # ' + side)
            for coefficient in row[side]:
                low, high = coefficient['words']
                # Match the Mojo formatter: one array element per line.
                lines.extend([f'    UInt64({low}),', f'    UInt64({high}),'])
    lines.extend([']', ''])
    return '\n'.join(lines).encode('utf-8')


def parse_table(data):
    try:
        text = data.decode('utf-8')
    except UnicodeDecodeError as error:
        raise CheckError('table is not UTF-8') from error
    code = '\n'.join(line.split('#', 1)[0] for line in text.splitlines()).strip()
    match = re.fullmatch(r'comptime _SPIRAL_MOMENT_WORDS: Array\[UInt64, (\d+)\] = \[(.*)\]',
                        code, re.S)
    require(match is not None, 'missing or malformed table declaration')
    require(int(match[1]) == WORD_COUNT, 'wrong table declaration shape')
    body = match[2]
    tokens = re.findall(r'UInt64\((0x[0-9A-Fa-f]{16})\),', body)
    remainder = re.sub(r'UInt64\(0x[0-9A-Fa-f]{16}\),', '', body)
    require(not remainder.strip(), 'malformed coefficient word or extra source')
    require(len(tokens) == WORD_COUNT, 'missing or extra coefficient words')
    return [int(token, 16) for token in tokens]


def verify_table(data, rows):
    words = parse_table(data)
    expected = words_from_rows(rows)
    require(len(expected) == WORD_COUNT, 'wrong derived table shape')
    for index, (actual, wanted) in enumerate(zip(words, expected)):
        require(actual == wanted, f'coefficient endpoint differs at word {index}')
    require(data == generate_source(rows), 'words match but source is not canonical generated bytes')
    return words


def make_report(root, rows, pins):
    packed = b''.join(struct.pack('>Q', word) for word in words_from_rows(rows))
    return {
        'scope': 'fixed-count quadrant-zero ideal stored-polynomial coefficients and tight endpoints only',
        'counts': 64, 'coefficients': 1408, 'words': WORD_COUNT, 'payload_bytes': len(packed),
        'zeroth_moment': str(F(1) + F(3, 1 << 55)),
        'source_sha256': digest(generate_source(rows)), 'words_be64_sha256': digest(packed),
        'pin_file_sha256': digest((root / PINS).read_bytes()),
        'dependency_pin_file_sha256': digest((root / source_contracts.PINS).read_bytes()),
        'environment_guard_pin_sha256': digest((root / sum2_guard_contracts.PINS).read_bytes()),
        'environment_guard_scope': 'Invocation-local predicate and caller source contracts only; no native FP-state/codegen qualification',
        'checked_source_root': str(root.resolve()),
        'ideal_half_projection': {key: pins['ideal_projection'][key] for key in
                                  ('helper_projections', 'rate_half_commutations', 'projected_ast_sha256')},
        'dependency_scope': DEPENDENCIES,
        'routing_sha256': {name: record['sha256'] for name, record in pins['routing'].items()},
        'source_block_sha256': {name: record['sha256'] for name, record in pins['blocks'].items()},
        'not_certified': ['rounded geometry/error graphs', 'branch eligibility',
                          'native execution/codegen', 'query correctness/performance'],
    }


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument('--check', action='store_true', help='read-only check (the default)')
    mode.add_argument('--generate', action='store_true', help='write canonical outputs to output directory')
    parser.add_argument('--report', action='store_true', help='explicitly write a JSON report')
    parser.add_argument('--output', type=Path, help='output directory; otherwise CARLA_LANE_ORACLE_OUTPUT or out/carla-lane-oracle')
    parser.add_argument('--repo-root', type=Path, default=ROOT, help='repository root (default: this script repository)')
    args = parser.parse_args(argv)
    if args.check and args.report:
        parser.error('--check is read-only; use --report without --check')
    if args.output is not None and not (args.generate or args.report):
        parser.error('--output requires --generate or --report')
    root = args.repo_root.resolve()
    try:
        constants, pins = verify_inputs(root)
        rows = derive_coefficients(constants)
        if not args.generate:
            verify_table((root / DATA).read_bytes(), rows)
        report = make_report(root, rows, pins)
        if args.generate or args.report:
            output = args.output or Path(os.environ.get('CARLA_LANE_ORACLE_OUTPUT',
                                                        str(root / 'out/carla-lane-oracle')))
            # Never let an output option overwrite tracked source inputs/tools.
            protected = [root / DATA, root / PINS, Path(__file__).resolve(),
                         root / source_contracts.PINS, root / sum2_guard_contracts.PINS] + [root / path for path in DEPENDENCIES['paths']] + [root / record['path']
                         for group in ('arrays', 'scalars', 'blocks', 'routing')
                         for record in pins[group].values()]
            products = {'spiral-moment-report.json': (json.dumps(report, indent=2) + '\n').encode()}
            if args.generate:
                products.update({
                    DATA.name: generate_source(rows),
                    'spiral_moment_words.be64': b''.join(struct.pack('>Q', word) for word in words_from_rows(rows)),
                    'spiral_moment_exact_coefficients.json': (json.dumps({'counts': rows}, indent=2) + '\n').encode(),
                })
            for name in products:
                destination = (output / name).resolve()
                require(destination not in [path.resolve() for path in protected],
                        'generation cannot overwrite repository source; use a separate output directory')
            output.mkdir(parents=True, exist_ok=True)
            for name, data in products.items():
                (output / name).write_bytes(data)
        print('PASS: 64 counts, 1408 exact coefficients, 2816 tight endpoints, 22528 payload bytes')
        print('canonical source SHA-256: ' + report['source_sha256'])
        return 0
    except (CheckError, OSError, ValueError, KeyError, TypeError) as error:
        print('FAIL: ' + str(error), file=sys.stderr)
        return 1


if __name__ == '__main__':
    raise SystemExit(main())
