#!/usr/bin/env python3
# Copyright (c) 2026 Seth Kitchen, PE
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
"""Reproduce the fixed-count quadrant-zero stored GL/trig coefficient table.

Python standard library only. Default and --check are read-only. No evaluator,
compiler, subprocess, network, private snapshots, or geometry sample is used.
"""
import argparse
from fractions import Fraction
import hashlib
import json
import os
from pathlib import Path
import re
import struct
import sys

sys.dont_write_bytecode = True
F = Fraction
ROOT = Path(__file__).resolve().parents[2]
PACKAGE = Path('tools/carla_lane_oracle')
PINS = PACKAGE / 'spiral-moment-pins.json'
DATA = Path('extensions/carla/spiral_moment_table_data.mojo')
SIGN = 1 << 63
INFINITY = 0x7FF0000000000000
MAX_FINITE = INFINITY - 1
WORD_COUNT = 64 * 22 * 2
ARRAY_SPECS = {
    '_GL_NODES': ('extensions/carla/geometry.mojo', 5),
    '_GL_WEIGHTS': ('extensions/carla/geometry.mojo', 5),
    '_COS_COEFFICIENTS': ('extensions/carla/curve_trig.mojo', 11),
    '_SIN_COEFFICIENTS': ('extensions/carla/curve_trig.mojo', 11),
}
SCALAR_NAMES = {'_PHASE_LIMIT', '_INV_HALF_PI', '_HALF_PI_HIGH', '_HALF_PI_LOW'}
BLOCK_PATHS = {
    'geometry_trig_aliases': 'extensions/carla/lane_geometry.mojo',
    'scalar_spiral': 'extensions/carla/lane_geometry.mojo',
    'scalar_horner': 'extensions/carla/curve_trig.mojo',
    'scalar_sincos': 'extensions/carla/curve_trig.mojo',
    'scalar_trig_wrappers': 'extensions/carla/curve_trig.mojo',
    'ideal_sincos_selector': 'extensions/carla/curve_trig.mojo',
    'ideal_horner': 'extensions/carla/curve_trig.mojo',
    'ideal_sincos_branch': 'extensions/carla/curve_trig.mojo',
    'ideal_spiral': 'extensions/carla/curve_bounds.mojo',
}
HEADER = '''# Copyright (c) 2026 Seth Kitchen, PE
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
# GENERATED by tools/carla_lane_oracle/spiral_moments.py. Do not edit words.
# Replay: python3 -B tools/carla_lane_oracle/spiral_moments.py --check
# Proof and limits: tools/carla_lane_oracle/spiral-moments.md
# Exact stored GL/trig polynomial only; no fitted or ideal-sin/cos data.
# Layout: count 1..64; cosine 0..10 then sine 0..10; low then high.
# 64 * 22 * 2 UInt64 words = 22,528 raw payload bytes.
# Bound as ref global_constant[_SPIRAL_MOMENT_WORDS](), never materialize.

'''


class CheckError(ValueError):
    """An input, source pin, coefficient, endpoint, or format is unsupported."""


def require(condition, message):
    # Do not use assert for verification: python -O must not disable checks.
    if not condition:
        raise CheckError(message)


def digest(data):
    return hashlib.sha256(data).hexdigest()


def hexword(word):
    return f'0x{word:016X}'


def fraction_of_word(word):
    require(type(word) is int and 0 <= word < 1 << 64, 'invalid UInt64 word')
    exponent = (word >> 52) & 0x7FF
    require(exponent != 0x7FF, 'nonfinite binary64 word')
    significand = word & ((1 << 52) - 1)
    shift = -1074
    if exponent:
        significand += 1 << 52
        shift = exponent - 1023 - 52
    value = F(significand << shift) if shift >= 0 else F(significand, 1 << -shift)
    return -value if word & SIGN else value


def next_up(word):
    if word in (0, SIGN):
        return 1
    return word - 1 if word & SIGN else word + 1


def next_down(word):
    if word in (0, SIGN):
        return SIGN | 1
    return word + 1 if word & SIGN else word - 1


def verify_bracket(value, low, high):
    require(fraction_of_word(low) <= value <= fraction_of_word(high),
            'endpoints do not enclose exact coefficient')
    following, preceding = next_up(low), next_down(high)
    require(following == INFINITY or fraction_of_word(following) > value,
            'lower endpoint is not greatest-below (or equal)')
    require(preceding == (SIGN | INFINITY) or fraction_of_word(preceding) < value,
            'upper endpoint is not least-above (or equal)')
    if value == 0:
        require((low, high) == (SIGN, 0), 'zero bracket must be [-0, +0]')


def bracket(value):
    """Exact integer lattice floor/ceil; no host floating-point conversion."""
    value = F(value)
    if not value:
        return SIGN, 0
    positive = abs(value)
    require(positive <= fraction_of_word(MAX_FINITE), 'binary64 overflow')
    numerator, denominator = positive.numerator, positive.denominator
    exponent = numerator.bit_length() - denominator.bit_length()
    if (numerator < denominator << exponent if exponent >= 0
            else numerator << -exponent < denominator):
        exponent -= 1
    shift = max(exponent - 52, -1074)
    if shift >= 0:
        significand = numerator // (denominator << shift)
    else:
        significand = (numerator << -shift) // denominator
    if exponent < -1022:
        low = significand
    else:
        low = ((exponent + 1023) << 52) | (significand - (1 << 52))
    high = low if fraction_of_word(low) == positive else low + 1
    pair = (SIGN | high, SIGN | low) if value < 0 else (low, high)
    verify_bracket(value, *pair)
    return pair


def nearest_even(value):
    if not value:
        return 0
    low, high = bracket(value)
    below, above = fraction_of_word(low), fraction_of_word(high)
    if value - below < above - value:
        return low
    if above - value < value - below:
        return high
    return low if low % 2 == 0 else high


def decimal_word(token):
    value = F(token)
    # Fractions have no signed zero; a source literal does.
    return SIGN if not value and token.startswith('-') else nearest_even(value)


def normalized_block(text):
    """Keep indentation and operation spelling; ignore comments/blank lines."""
    lines = [line.split('#', 1)[0].rstrip() for line in text.splitlines()]
    return '\n'.join(line for line in lines if line.strip()) + '\n'


def selected_block(text, begin, end):
    require(text.count(begin) == 1, 'missing or ambiguous source-block start')
    start = text.index(begin)
    require(text[start + len(begin):].count(end) == 1,
            'missing or ambiguous source-block end')
    stop = text.index(end, start + len(begin))
    return normalized_block(text[start:stop])


def parse_array(text, name, size):
    pattern = (r'^comptime ' + re.escape(name) + r': Array\[Float64, '
               + str(size) + r'\] = \[(.*?)\]')
    matches = re.findall(pattern, text, re.M | re.S)
    require(len(matches) == 1, 'missing or ambiguous constant array: ' + name)
    body = '\n'.join(line.split('#', 1)[0] for line in matches[0].splitlines())
    tokens = [part.strip() for part in body.split(',') if part.strip()]
    require(len(tokens) == size, 'wrong constant-array shape: ' + name)
    require(all(re.fullmatch(r'[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?',
                             token) for token in tokens), 'unsupported constant literal: ' + name)
    return [decimal_word(token) for token in tokens]


def verify_inputs(root):
    pins = json.loads((root / PINS).read_text(encoding='utf-8'))
    require(pins['schema'] == 1, 'unsupported pin schema')
    require(set(pins['arrays']) == set(ARRAY_SPECS), 'wrong constant-array pin set')
    require(set(pins['scalars']) == SCALAR_NAMES, 'wrong scalar pin set')
    require(set(pins['blocks']) == set(BLOCK_PATHS), 'wrong operation-graph pin set')
    constants = {}
    for name, record in pins['arrays'].items():
        path, size = ARRAY_SPECS[name]
        require(record['path'] == path and len(record['words']) == size,
                'wrong array pin path/shape: ' + name)
        words = parse_array((root / record['path']).read_text(encoding='utf-8'),
                            name, len(record['words']))
        require([hexword(word) for word in words] == record['words'],
                'stored constant words changed: ' + name)
        constants[name] = [fraction_of_word(word) for word in words]
    require(set(constants) == {'_GL_NODES', '_GL_WEIGHTS',
                               '_COS_COEFFICIENTS', '_SIN_COEFFICIENTS'},
            'wrong constant-array set')
    for name, record in pins['scalars'].items():
        require(record['path'] == 'extensions/carla/curve_trig.mojo',
                'wrong scalar pin path: ' + name)
        text = (root / record['path']).read_text(encoding='utf-8')
        matches = re.findall(r'^comptime ' + re.escape(name) +
                             r' = Float64\(([^)]+)\)$', text, re.M)
        require(len(matches) == 1, 'missing or ambiguous scalar: ' + name)
        require(hexword(decimal_word(matches[0])) == record['word'],
                'stored scalar word changed: ' + name)
    for name, record in pins['blocks'].items():
        require(record['path'] == BLOCK_PATHS[name], 'wrong operation pin path: ' + name)
        current = selected_block((root / record['path']).read_text(encoding='utf-8'),
                                 record['begin'], record['end'])
        expected = record['normalized_source']
        require(digest(expected.encode()) == record['sha256'],
                'inconsistent operation-graph pin: ' + name)
        require(current == expected, 'operation graph changed: ' + name)
    sums = [nearest_even(F(1) + node) for node in constants['_GL_NODES']]
    require([hexword(word) for word in sums] == pins['rounded_node_sums'],
            'rounded 1 + node words changed')
    constants['node_sums'] = [fraction_of_word(word) for word in sums]
    require(sum(constants['_GL_WEIGHTS']) / 2 == F(1) + F(3, 1 << 55),
            'stored zeroth moment must not be normalized to one')
    return constants, pins


def derive_coefficients(constants):
    """All 64 rows, exactly; share only unscaled prefix sums across counts.

    S[k,n] = sum(p<n,i) w[i]*(p+q[i]/2)**(2*k).
    M[k,n] = S[k,n]/(2*n**(2*k+1)). This is algebraic common work only.
    """
    sums = [F(0) for _ in range(22)]
    rows = []
    for count in range(1, 65):
        for node, weight in zip(constants['node_sums'], constants['_GL_WEIGHTS']):
            square = (F(count - 1) + node / 2) ** 2
            power = F(1)
            for index in range(22):
                sums[index] += weight * power
                power *= square
        moments = [value / (2 * count ** (2 * index + 1))
                   for index, value in enumerate(sums)]
        require(moments[0] == F(1) + F(3, 1 << 55), 'zeroth moment drift')
        row = {'count': count}
        for side, key, parity in [('cosine', '_COS_COEFFICIENTS', 0),
                                  ('sine', '_SIN_COEFFICIENTS', 1)]:
            row[side] = []
            for index, coefficient in enumerate(constants[key]):
                exact = coefficient * moments[2 * index + parity]
                endpoints = bracket(exact)
                row[side].append({'exact': str(exact),
                                  'words': [hexword(word) for word in endpoints]})
        rows.append(row)
    return rows


def words_from_rows(rows):
    return [int(word, 16) for row in rows for side in ('cosine', 'sine')
            for coefficient in row[side] for word in coefficient['words']]


def generate_source(rows):
    lines = [HEADER.rstrip('\n'), '',
             'comptime _SPIRAL_MOMENT_WORDS: Array[UInt64, 2816] = [']
    for row in rows:
        lines.append(f'    # Count {row["count"]}')
        for side in ('cosine', 'sine'):
            lines.append('    # ' + side)
            for coefficient in row[side]:
                low, high = coefficient['words']
                # Match the Mojo formatter: one array element per line.
                lines.extend([f'    UInt64({low}),', f'    UInt64({high}),'])
    lines.extend([']', ''])
    return '\n'.join(lines).encode('utf-8')


def parse_table(data):
    try:
        text = data.decode('utf-8')
    except UnicodeDecodeError as error:
        raise CheckError('table is not UTF-8') from error
    code = '\n'.join(line.split('#', 1)[0] for line in text.splitlines()).strip()
    match = re.fullmatch(r'comptime _SPIRAL_MOMENT_WORDS: Array\[UInt64, (\d+)\] = \[(.*)\]',
                        code, re.S)
    require(match is not None, 'missing or malformed table declaration')
    require(int(match[1]) == WORD_COUNT, 'wrong table declaration shape')
    body = match[2]
    tokens = re.findall(r'UInt64\((0x[0-9A-Fa-f]{16})\),', body)
    remainder = re.sub(r'UInt64\(0x[0-9A-Fa-f]{16}\),', '', body)
    require(not remainder.strip(), 'malformed coefficient word or extra source')
    require(len(tokens) == WORD_COUNT, 'missing or extra coefficient words')
    return [int(token, 16) for token in tokens]


def verify_table(data, rows):
    words = parse_table(data)
    expected = words_from_rows(rows)
    require(len(expected) == WORD_COUNT, 'wrong derived table shape')
    for index, (actual, wanted) in enumerate(zip(words, expected)):
        require(actual == wanted, f'coefficient endpoint differs at word {index}')
    require(data == generate_source(rows), 'words match but source is not canonical generated bytes')
    return words


def make_report(root, rows, pins):
    packed = b''.join(struct.pack('>Q', word) for word in words_from_rows(rows))
    return {
        'scope': 'fixed-count quadrant-zero ideal stored-polynomial coefficients and tight endpoints only',
        'counts': 64, 'coefficients': 1408, 'words': WORD_COUNT, 'payload_bytes': len(packed),
        'zeroth_moment': str(F(1) + F(3, 1 << 55)),
        'source_sha256': digest(generate_source(rows)), 'words_be64_sha256': digest(packed),
        'pin_file_sha256': digest((root / PINS).read_bytes()),
        'source_block_sha256': {name: record['sha256'] for name, record in pins['blocks'].items()},
        'not_certified': ['rounded geometry/error graphs', 'branch eligibility',
                          'native execution/codegen', 'query correctness/performance'],
    }


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument('--check', action='store_true', help='read-only check (the default)')
    mode.add_argument('--generate', action='store_true', help='write canonical outputs to output directory')
    parser.add_argument('--report', action='store_true', help='explicitly write a JSON report')
    parser.add_argument('--output', type=Path, help='output directory; otherwise CARLA_LANE_ORACLE_OUTPUT or out/carla-lane-oracle')
    parser.add_argument('--repo-root', type=Path, default=ROOT, help='repository root (default: this script repository)')
    args = parser.parse_args(argv)
    if args.check and args.report:
        parser.error('--check is read-only; use --report without --check')
    if args.output is not None and not (args.generate or args.report):
        parser.error('--output requires --generate or --report')
    root = args.repo_root.resolve()
    try:
        constants, pins = verify_inputs(root)
        rows = derive_coefficients(constants)
        if not args.generate:
            verify_table((root / DATA).read_bytes(), rows)
        report = make_report(root, rows, pins)
        if args.generate or args.report:
            output = args.output or Path(os.environ.get('CARLA_LANE_ORACLE_OUTPUT',
                                                        str(root / 'out/carla-lane-oracle')))
            # Never let an output option overwrite tracked source inputs/tools.
            protected = [root / DATA, root / PINS, Path(__file__).resolve()] + [root / record['path']
                         for group in ('arrays', 'scalars', 'blocks')
                         for record in pins[group].values()]
            products = {'spiral-moment-report.json': (json.dumps(report, indent=2) + '\n').encode()}
            if args.generate:
                products.update({
                    DATA.name: generate_source(rows),
                    'spiral_moment_words.be64': b''.join(struct.pack('>Q', word) for word in words_from_rows(rows)),
                    'spiral_moment_exact_coefficients.json': (json.dumps({'counts': rows}, indent=2) + '\n').encode(),
                })
            for name in products:
                destination = (output / name).resolve()
                require(destination not in [path.resolve() for path in protected],
                        'generation cannot overwrite repository source; use a separate output directory')
            output.mkdir(parents=True, exist_ok=True)
            for name, data in products.items():
                (output / name).write_bytes(data)
        print('PASS: 64 counts, 1408 exact coefficients, 2816 tight endpoints, 22528 payload bytes')
        print('canonical source SHA-256: ' + report['source_sha256'])
        return 0
    except (CheckError, OSError, ValueError, KeyError, TypeError) as error:
        print('FAIL: ' + str(error), file=sys.stderr)
        return 1


if __name__ == '__main__':
    raise SystemExit(main())
