# Copyright (c) 2026 Seth Kitchen, PE
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
# Noncommercial use is free; commercial use requires a paid license.
# See LICENSE, LICENSE-COMMERCIAL.md and THIRD-PARTY-NOTICES.md.

"""A surface drawn through a field of numbers, from three.js
`examples/jsm/objects/MarchingCubes.js`.

A marching cubes object holds a cube of `resolution` cells a side, each
with a number. `update` finds the surface where the numbers cross
`isolation` and turns it into triangles: each cube of eight neighboring
cells looks up which of its edges the surface crosses, places a vertex on
each by linear interpolation, and joins them by Paul Bourke's tables. The
field's gradient, interpolated the same way, is the vertex normal.

`add_ball` adds a metaball and `add_plane_x`, `add_plane_y` and
`add_plane_z` add a wall at one side. `blur` smooths the field. The
surface fills the cube from -1 to 1 on each axis, so scale the mesh's node
to size it.

The arithmetic is three.js's, operation by operation. JavaScript computes
in doubles and stores the field, the normals, the colors and the vertices
in `Float32Array`s. This port does the same, so the vertices match
three.js's one for one.

Where the port differs:

- **A full buffer raises.** three.js keeps writing past `maxPolyCount`
  into nothing and warns. `update` raises instead.
- **A cell outside the cube raises.** three.js reads `undefined` and
  writes nowhere.
- **The surface is a new geometry.** three.js writes into one geometry and
  sets its draw range. `geometry` returns the surface as a geometry of
  exactly the triangles made; `replace_geometry` puts it in the store.
- **The bound is computed.** three.js sets a bounding sphere of radius one,
  which does not hold the cube's corners.
- **The flat normals are asked for.** three.js reads its material's
  `flatShading`. Set `flat_shading` here.
"""

from core.assets import Assets
from core.buffer_attribute import BufferAttribute
from core.buffer_geometry import BufferGeometry, COLOR, NORMAL, POSITION, UV
from core.geometry_store import GeometryId
from render.framebuffer import FloatColor
from std.math import floor, isfinite, sqrt

# three.js's `maxPolyCount` default.
comptime DEFAULT_MAX_POLY_COUNT = 10000
# three.js's `isolation` default.
comptime DEFAULT_ISOLATION = Float64(80.0)


def _sign(value: Float64) -> Float64:
    """Return JavaScript's `Math.sign` of a finite number."""
    if value > 0:
        return 1
    if value < 0:
        return -1
    return value


def _lerp(a: Float32, b: Float32, t: Float64) -> Float32:
    """Return three.js's `lerp` of two stored floats, in doubles."""
    var start = Float64(a)
    return Float32(start + (Float64(b) - start) * t)


struct MarchingCubes(Movable):
    """A field of numbers and the surface through it, three.js's
    `MarchingCubes`."""

    # The cells along each side, three.js's `resolution` and `size`.
    var resolution: Int
    # The value the surface passes through, three.js's `isolation`.
    var isolation: Float64
    # Whether the geometry has coordinates and colors, three.js's
    # `enableUvs` and `enableColors`.
    var enable_uvs: Bool
    var enable_colors: Bool
    # Whether each triangle's three normals are their mean, three.js's
    # `material.flatShading`.
    var flat_shading: Bool
    # How many triangles `update` may make, three.js's `maxPolyCount`.
    var max_poly_count: Int
    # The field, a number a cell, x fastest: three.js's `field`.
    var field: List[Float32]
    # The field's gradient at each cell, three.js's `normal_cache`. A cell
    # whose first number is zero has not been worked out.
    var normal_cache: List[Float32]
    # A color a cell, three.js's `palette`.
    var palette: List[Float32]
    # How many vertices the last `update` made, three.js's `count`.
    var count: Int
    # The vertices the last `update` made: three.js's `positionArray`,
    # `normalArray`, `uvArray` and `colorArray`.
    var positions: List[Float32]
    var normals: List[Float32]
    var uvs: List[Float32]
    var colors: List[Float32]
    # Paul Bourke's tables: which edges each of the 256 corner patterns
    # cuts, and the triangles that join them.
    var _edges: List[Int]
    var _triangles: List[Int]

    def __init__(
        out self,
        resolution: Int,
        enable_uvs: Bool = False,
        enable_colors: Bool = False,
        max_poly_count: Int = DEFAULT_MAX_POLY_COUNT,
    ) raises:
        """Create an empty field, three.js's constructor and `init`.

        Args:
            resolution: The cells along each side.
            enable_uvs: Whether the geometry has texture coordinates: each
                vertex's x and z.
            enable_colors: Whether the geometry has vertex colors, from the
                palette.
            max_poly_count: How many triangles `update` may make.

        Raises:
            Error: If the resolution or the triangle count is not positive.
        """
        if resolution <= 0:
            raise Error("A marching cubes field needs a positive resolution")
        if max_poly_count <= 0:
            raise Error("A marching cubes field needs room for a triangle")
        self.resolution = resolution
        self.isolation = DEFAULT_ISOLATION
        self.enable_uvs = enable_uvs
        self.enable_colors = enable_colors
        self.flat_shading = False
        self.max_poly_count = max_poly_count
        var cells = resolution * resolution * resolution
        self.field = List[Float32](length=cells, fill=0)
        self.normal_cache = List[Float32](length=cells * 3, fill=0)
        self.palette = List[Float32](length=cells * 3, fill=0)
        self.count = 0
        self.positions = List[Float32]()
        self.normals = List[Float32]()
        self.uvs = List[Float32]()
        self.colors = List[Float32]()
        self._edges = _edge_table()
        self._triangles = _triangle_table()

    def _delta(self) -> Float64:
        """Return the width of a cell in the -1 to 1 cube."""
        return 2.0 / Float64(self.resolution)

    def _index(self, x: Int, y: Int, z: Int) raises -> Int:
        """Return a cell's index, three.js's `size2 * z + size * y + x`.

        Raises:
            Error: If the cell is outside the cube.
        """
        var size = self.resolution
        if not _in_cube(x, y, z, size):
            raise Error("A marching cubes cell must be inside the field")
        return size * size * z + size * y + x

    def set_cell(mut self, x: Int, y: Int, z: Int, value: Float32) raises:
        """Set one cell of the field, three.js's `setCell`.

        Args:
            x: The cell's column.
            y: The cell's row.
            z: The cell's layer.
            value: Its new number.

        Raises:
            Error: If the cell is outside the cube.
        """
        self.field[self._index(x, y, z)] = value

    def get_cell(self, x: Int, y: Int, z: Int) raises -> Float32:
        """Return one cell of the field, three.js's `getCell`.

        Args:
            x: The cell's column.
            y: The cell's row.
            z: The cell's layer.

        Returns:
            Its number.

        Raises:
            Error: If the cell is outside the cube.
        """
        return self.field[self._index(x, y, z)]

    def add_ball(
        mut self,
        ball_x: Float64,
        ball_y: Float64,
        ball_z: Float64,
        strength: Float64,
        subtract: Float64,
        color: Optional[FloatColor] = None,
    ) raises:
        """Add a metaball, three.js's `addBall`.

        Each cell near the ball gains `strength / d² - subtract`, where `d`
        is its distance from the center as a fraction of the cube, while
        that is positive. A negative strength takes the ball away. The
        palette gains the ball's color, faded smoothly to its edge.

        Args:
            ball_x: The center's x, from 0 to 1 across the cube.
            ball_y: The center's y.
            ball_z: The center's z.
            strength: How strong the ball is. Its sign says whether it adds
                or takes away.
            subtract: What is taken from every cell's share, which sets the
                ball's reach.
            color: The ball's color in linear light, three.js's `colors` as
                a `Color`. `None` takes the center's coordinates as a
                color, as three.js does.

        Raises:
            Error: If a number is not finite.
        """
        if not _finite_ball(ball_x, ball_y, ball_z, strength, subtract):
            raise Error("A metaball's numbers must be finite")
        var sign = _sign(strength)
        var power = abs(strength)
        var red = ball_x
        var green = ball_y
        var blue = ball_z
        if Bool(color):
            red = Float64(color.value().r)
            green = Float64(color.value().g)
            blue = Float64(color.value().b)
        var size = Float64(self.resolution)
        var radius = size * sqrt(power / subtract)
        # A negative `subtract` has no reach. three.js's loops run from
        # not-a-number and stop at once.
        if not (radius >= 0):
            return
        var zs = ball_z * size
        var ys = ball_y * size
        var xs = ball_x * size
        var z_range = _cells(zs, radius, size)
        var y_range = _cells(ys, radius, size)
        var x_range = _cells(xs, radius, size)
        var size2 = self.resolution * self.resolution
        for z in range(z_range[0], z_range[1]):
            var z_offset = size2 * z
            var fz = Float64(z) / size - ball_z
            var fz2 = fz * fz
            for y in range(y_range[0], y_range[1]):
                var y_offset = z_offset + self.resolution * y
                var fy = Float64(y) / size - ball_y
                var fy2 = fy * fy
                for x in range(x_range[0], x_range[1]):
                    var fx = Float64(x) / size - ball_x
                    var val = (
                        power / (0.000001 + fx * fx + fy2 + fz2) - subtract
                    )
                    if val > 0.0:
                        var at = y_offset + x
                        self.field[at] = Float32(
                            Float64(self.field[at]) + val * sign
                        )
                        var dx = Float64(x) - xs
                        var dy = Float64(y) - ys
                        var dz = Float64(z) - zs
                        var ratio = sqrt(dx * dx + dy * dy + dz * dz) / radius
                        var contrib = 1 - ratio * ratio * ratio * (
                            ratio * (ratio * 6 - 15) + 10
                        )
                        self._tint(at * 3, red * contrib)
                        self._tint(at * 3 + 1, green * contrib)
                        self._tint(at * 3 + 2, blue * contrib)

    def _tint(mut self, at: Int, amount: Float64):
        """Add to one palette channel, in doubles, stored as a float."""
        self.palette[at] = Float32(Float64(self.palette[at]) + amount)

    def _add(mut self, at: Int, amount: Float64):
        """Add to one cell, in doubles, stored as a float."""
        self.field[at] = Float32(Float64(self.field[at]) + amount)

    def _reach(self, strength: Float64, subtract: Float64) raises -> Float64:
        """Return how many cells a wall reaches, three.js's `dist`.

        Raises:
            Error: If a number is not finite.
        """
        if not _finite_pair(strength, subtract):
            raise Error("A wall's strength and subtract must be finite")
        var size = Float64(self.resolution)
        var dist = size * sqrt(strength / subtract)
        if dist > size:
            dist = size
        return dist

    def _wall(self, step: Int, strength: Float64, subtract: Float64) -> Float64:
        """Return what a wall adds at `step` cells from its side."""
        var fraction = Float64(step) / Float64(self.resolution)
        return strength / (0.0001 + fraction * fraction) - subtract

    def add_plane_x(mut self, strength: Float64, subtract: Float64) raises:
        """Add a wall at the cube's x = 0 side, three.js's `addPlaneX`.

        Args:
            strength: How strong the wall is.
            subtract: What is taken from every cell's share.

        Raises:
            Error: If a number is not finite.
        """
        var dist = self._reach(strength, subtract)
        var size = self.resolution
        var x = 0
        while Float64(x) < dist:
            var val = self._wall(x, strength, subtract)
            if val > 0.0:
                for y in range(size):  # pragma: no branch
                    var cxy = x + y * size
                    for z in range(size):  # pragma: no branch
                        self._add(size * size * z + cxy, val)
            x += 1

    def add_plane_y(mut self, strength: Float64, subtract: Float64) raises:
        """Add a wall at the cube's y = 0 side, three.js's `addPlaneY`.

        Args:
            strength: How strong the wall is.
            subtract: What is taken from every cell's share.

        Raises:
            Error: If a number is not finite.
        """
        var dist = self._reach(strength, subtract)
        var size = self.resolution
        var y = 0
        while Float64(y) < dist:
            var val = self._wall(y, strength, subtract)
            if val > 0.0:
                var cy = y * size
                for x in range(size):  # pragma: no branch
                    var cxy = cy + x
                    for z in range(size):  # pragma: no branch
                        self._add(size * size * z + cxy, val)
            y += 1

    def add_plane_z(mut self, strength: Float64, subtract: Float64) raises:
        """Add a wall at the cube's z = 0 side, three.js's `addPlaneZ`.

        Args:
            strength: How strong the wall is.
            subtract: What is taken from every cell's share.

        Raises:
            Error: If a number is not finite.
        """
        var dist = self._reach(strength, subtract)
        var size = self.resolution
        var z = 0
        while Float64(z) < dist:
            var val = self._wall(z, strength, subtract)
            if val > 0.0:
                var cz = size * size * z
                for y in range(size):  # pragma: no branch
                    var cyz = cz + y * size
                    for x in range(size):  # pragma: no branch
                        self._add(cyz + x, val)
            z += 1

    def blur(mut self, intensity: Float64 = 1) raises:
        """Smooth the field, three.js's `blur`.

        Each cell moves toward its corner neighbors, one at a time, in
        three.js's order.

        Args:
            intensity: How far each step moves, from 0 for none to 1.

        Raises:
            Error: If the intensity is not finite.
        """
        if not isfinite(intensity):
            raise Error("A blur's intensity must be finite")
        var copy = self.field.copy()
        var size = self.resolution
        var size2 = size * size
        for x in range(size):  # pragma: no branch
            for y in range(size):  # pragma: no branch
                for z in range(size):  # pragma: no branch
                    var index = size2 * z + size * y + x
                    var val = Float64(copy[index])
                    var count = 1
                    for x2 in range(-1, 2, 2):  # pragma: no branch
                        var x3 = x2 + x
                        if not _inside(x3, size):
                            continue
                        for y2 in range(-1, 2, 2):  # pragma: no branch
                            var y3 = y2 + y
                            if not _inside(y3, size):
                                continue
                            for z2 in range(-1, 2, 2):  # pragma: no branch
                                var z3 = z2 + z
                                if not _inside(z3, size):
                                    continue
                                var val2 = Float64(
                                    copy[size2 * z3 + size * y3 + x3]
                                )
                                count += 1
                                val += intensity * (val2 - val) / Float64(count)
                    self.field[index] = Float32(val)

    def reset(mut self):
        """Clear the field, the palette and the normals, three.js's `reset`.

        As in three.js, only the first number of each cached normal is
        cleared: that zero is what marks it as not worked out.
        """
        for i in range(len(self.field)):  # pragma: no branch
            self.normal_cache[i * 3] = 0.0
            self.field[i] = 0.0
            self.palette[i * 3] = 0.0
            self.palette[i * 3 + 1] = 0.0
            self.palette[i * 3 + 2] = 0.0

    def update(mut self) raises:
        """Find the surface, three.js's `update`.

        The outer layer of cells is left out, because the gradient there
        reads past the cube. The normals are cached between updates, as in
        three.js: call `reset` before building a new field.

        Raises:
            Error: If the surface needs more than `max_poly_count`
                triangles.
        """
        self.count = 0
        self.positions = List[Float32]()
        self.normals = List[Float32]()
        self.uvs = List[Float32]()
        self.colors = List[Float32]()
        var size = self.resolution
        var half = Float64(size) / 2.0
        var last = size - 2
        # The three ranges are one range, so an inner loop runs whenever
        # the loop around it does.
        for z in range(1, last):
            var z_offset = size * size * z
            var fz = (Float64(z) - half) / half
            for y in range(1, last):  # pragma: no branch
                var y_offset = z_offset + size * y
                var fy = (Float64(y) - half) / half
                for x in range(1, last):  # pragma: no branch
                    var fx = (Float64(x) - half) / half
                    self._polygonize(fx, fy, fz, y_offset + x)
        if self.count // 3 > self.max_poly_count:
            raise Error(
                "A marching cubes surface needs more triangles than"
                " max_poly_count"
            )

    def _normal(mut self, q: Int):
        """Work out a cell's gradient unless it is cached, three.js's
        `compNorm`."""
        var q3 = q * 3
        if self.normal_cache[q3] == 0.0:
            var yd = self.resolution
            var zd = yd * yd
            self.normal_cache[q3] = Float32(
                Float64(self.field[q - 1]) - Float64(self.field[q + 1])
            )
            self.normal_cache[q3 + 1] = Float32(
                Float64(self.field[q - yd]) - Float64(self.field[q + yd])
            )
            self.normal_cache[q3 + 2] = Float32(
                Float64(self.field[q - zd]) - Float64(self.field[q + zd])
            )

    def _cut(
        self,
        mut vertices: List[Float32],
        mut normals: List[Float32],
        mut colors: List[Float32],
        axis: Int,
        offset: Int,
        corner: SIMD[DType.float64, 4],
        a: Int,
        b: Int,
    ):
        """Place the vertex where an edge crosses the isolation, three.js's
        `VIntX`, `VIntY` and `VIntZ`.

        `corner` holds the edge's start in the cube and the isolation's
        share along it is worked out from the two cells `a` and `b`.
        """
        var start = Float64(self.field[a])
        var mu = (self.isolation - start) / (Float64(self.field[b]) - start)
        for k in range(3):  # pragma: no branch
            var place = corner[k]
            if k == axis:
                place = place + mu * self._delta()
            vertices[offset + k] = Float32(place)
            normals[offset + k] = _lerp(
                self.normal_cache[a * 3 + k], self.normal_cache[b * 3 + k], mu
            )
            colors[offset + k] = _lerp(
                self.palette[a * 3 + k], self.palette[b * 3 + k], mu
            )

    def _polygonize(mut self, fx: Float64, fy: Float64, fz: Float64, q: Int):
        """Add the triangles of one cube, three.js's `polygonize`."""
        var yd = self.resolution
        var zd = yd * yd
        var q1 = q + 1
        var qy = q + yd
        var qz = q + zd
        var q1y = q1 + yd
        var q1z = q1 + zd
        var qyz = q + yd + zd
        var q1yz = q1 + yd + zd
        var isol = self.isolation
        var cube = 0
        if Float64(self.field[q]) < isol:
            cube |= 1
        if Float64(self.field[q1]) < isol:
            cube |= 2
        if Float64(self.field[qy]) < isol:
            cube |= 8
        if Float64(self.field[q1y]) < isol:
            cube |= 4
        if Float64(self.field[qz]) < isol:
            cube |= 16
        if Float64(self.field[q1z]) < isol:
            cube |= 32
        if Float64(self.field[qyz]) < isol:
            cube |= 128
        if Float64(self.field[q1yz]) < isol:
            cube |= 64
        var bits = self._edges[cube]
        if bits == 0:
            return
        var d = self._delta()
        var fx2 = fx + d
        var fy2 = fy + d
        var fz2 = fz + d
        var vertices = List[Float32](length=36, fill=0)
        var normals = List[Float32](length=36, fill=0)
        var colors = List[Float32](length=36, fill=0)
        comptime Corner = SIMD[DType.float64, 4]
        # The twelve edges, in three.js's order: each edge's axis, the cells
        # at its two ends, and its start.
        var axes: List[Int] = [0, 1, 0, 1, 0, 1, 0, 1, 2, 2, 2, 2]
        var starts: List[Int] = [q, q1, qy, q, qz, q1z, qyz, qz, q, q1, q1y, qy]
        var ends: List[Int] = [
            q1,
            q1y,
            q1y,
            qy,
            q1z,
            q1yz,
            q1yz,
            qyz,
            qz,
            q1z,
            q1yz,
            qyz,
        ]
        var corners: List[Corner] = [
            Corner(fx, fy, fz, 0),
            Corner(fx2, fy, fz, 0),
            Corner(fx, fy2, fz, 0),
            Corner(fx, fy, fz, 0),
            Corner(fx, fy, fz2, 0),
            Corner(fx2, fy, fz2, 0),
            Corner(fx, fy2, fz2, 0),
            Corner(fx, fy, fz2, 0),
            Corner(fx, fy, fz, 0),
            Corner(fx2, fy, fz, 0),
            Corner(fx2, fy2, fz, 0),
            Corner(fx, fy2, fz, 0),
        ]
        for edge in range(12):  # pragma: no branch
            if bits & (1 << edge) != 0:
                self._normal(starts[edge])
                self._normal(ends[edge])
                self._cut(
                    vertices,
                    normals,
                    colors,
                    axes[edge],
                    edge * 3,
                    corners[edge],
                    starts[edge],
                    ends[edge],
                )
        var row = cube * 16
        var i = 0
        while self._triangles[row + i] != -1:
            self._emit(
                vertices,
                normals,
                colors,
                3 * self._triangles[row + i],
                3 * self._triangles[row + i + 1],
                3 * self._triangles[row + i + 2],
            )
            i += 3

    def _emit(
        mut self,
        vertices: List[Float32],
        normals: List[Float32],
        colors: List[Float32],
        o1: Int,
        o2: Int,
        o3: Int,
    ):
        """Add one triangle, three.js's `posnormtriv`."""
        var corners: List[Int] = [o1, o2, o3]
        for corner in corners:  # pragma: no branch
            for k in range(3):  # pragma: no branch
                self.positions.append(vertices[corner + k])
        if self.flat_shading:
            for _ in range(3):  # pragma: no branch
                for k in range(3):  # pragma: no branch
                    self.normals.append(
                        Float32(
                            (
                                Float64(normals[o1 + k])
                                + Float64(normals[o2 + k])
                                + Float64(normals[o3 + k])
                            )
                            / 3
                        )
                    )
        else:
            for corner in corners:  # pragma: no branch
                for k in range(3):  # pragma: no branch
                    self.normals.append(normals[corner + k])
        if self.enable_uvs:
            for corner in corners:  # pragma: no branch
                self.uvs.append(vertices[corner])
                self.uvs.append(vertices[corner + 2])
        if self.enable_colors:
            for corner in corners:  # pragma: no branch
                for k in range(3):  # pragma: no branch
                    self.colors.append(colors[corner + k])
        self.count += 3

    def geometry(self) raises -> BufferGeometry:
        """Return the surface the last `update` made.

        Returns:
            A geometry of `count` vertices, three to a triangle, with no
            index: `position` and `normal`, and `uv` and `color` when they
            are enabled. The normals are the field's gradient, not made
            unit length; the renderer makes them so.

        Raises:
            Error: If the surface holds no triangle.
        """
        if self.count == 0:
            raise Error("A marching cubes surface with no triangle")
        var geometry = BufferGeometry()
        geometry.set_attribute(
            String(POSITION), BufferAttribute(self.positions.copy(), 3)
        )
        geometry.set_attribute(
            String(NORMAL), BufferAttribute(self.normals.copy(), 3)
        )
        if self.enable_uvs:
            geometry.set_attribute(
                String(UV), BufferAttribute(self.uvs.copy(), 2)
            )
        if self.enable_colors:
            geometry.set_attribute(
                String(COLOR), BufferAttribute(self.colors.copy(), 3)
            )
        return geometry^

    def replace_geometry(self, mut assets: Assets, id: GeometryId) raises:
        """Put the surface in place of the geometry an id names, three.js's
        `needsUpdate`, so every mesh that draws the id draws the new surface.

        Args:
            assets: The stores.
            id: The geometry to replace.

        Raises:
            Error: If no geometry has that id, or `geometry` raises.
        """
        _ = assets.geometries.get(id)
        assets.geometries.geometries[id.value] = self.geometry()


def _inside(index: Int, size: Int) -> Bool:
    """Return True if a cell index lies in the cube."""
    return index >= 0 and index < size


def _in_cube(x: Int, y: Int, z: Int, size: Int) -> Bool:
    """Return True if a cell lies in the cube."""
    return _inside(x, size) and _inside(y, size) and _inside(z, size)


def _finite_pair(a: Float64, b: Float64) -> Bool:
    """Return True if both numbers are finite."""
    return isfinite(a) and isfinite(b)


def _finite_ball(
    x: Float64, y: Float64, z: Float64, strength: Float64, subtract: Float64
) -> Bool:
    """Return True if every number of a metaball is finite."""
    return (
        isfinite(x)
        and isfinite(y)
        and isfinite(z)
        and isfinite(strength)
        and isfinite(subtract)
    )


def _cells(center: Float64, radius: Float64, size: Float64) -> Tuple[Int, Int]:
    """Return the cells a ball reaches along one axis, three.js's `min_z`
    and `max_z`: from the floor of `center - radius`, at least one, to the
    floor of `center + radius`, at most `size - 1`, the last one left out.
    """
    var low = floor(center - radius)
    if low < 1:
        low = 1
    var high = floor(center + radius)
    if high > size - 1:
        high = size - 1
    # Clamped on the other side too, where the loop is empty either way,
    # so a center far outside the cube still converts to a whole number.
    if low > size:
        low = size
    if high < 1:
        high = 1
    return (Int(low), Int(high))


def _edge_table() -> List[Int]:
    """Return which of the twelve edges each corner pattern cuts."""
    return [
        0x0,
        0x109,
        0x203,
        0x30A,
        0x406,
        0x50F,
        0x605,
        0x70C,
        0x80C,
        0x905,
        0xA0F,
        0xB06,
        0xC0A,
        0xD03,
        0xE09,
        0xF00,
        0x190,
        0x99,
        0x393,
        0x29A,
        0x596,
        0x49F,
        0x795,
        0x69C,
        0x99C,
        0x895,
        0xB9F,
        0xA96,
        0xD9A,
        0xC93,
        0xF99,
        0xE90,
        0x230,
        0x339,
        0x33,
        0x13A,
        0x636,
        0x73F,
        0x435,
        0x53C,
        0xA3C,
        0xB35,
        0x83F,
        0x936,
        0xE3A,
        0xF33,
        0xC39,
        0xD30,
        0x3A0,
        0x2A9,
        0x1A3,
        0xAA,
        0x7A6,
        0x6AF,
        0x5A5,
        0x4AC,
        0xBAC,
        0xAA5,
        0x9AF,
        0x8A6,
        0xFAA,
        0xEA3,
        0xDA9,
        0xCA0,
        0x460,
        0x569,
        0x663,
        0x76A,
        0x66,
        0x16F,
        0x265,
        0x36C,
        0xC6C,
        0xD65,
        0xE6F,
        0xF66,
        0x86A,
        0x963,
        0xA69,
        0xB60,
        0x5F0,
        0x4F9,
        0x7F3,
        0x6FA,
        0x1F6,
        0xFF,
        0x3F5,
        0x2FC,
        0xDFC,
        0xCF5,
        0xFFF,
        0xEF6,
        0x9FA,
        0x8F3,
        0xBF9,
        0xAF0,
        0x650,
        0x759,
        0x453,
        0x55A,
        0x256,
        0x35F,
        0x55,
        0x15C,
        0xE5C,
        0xF55,
        0xC5F,
        0xD56,
        0xA5A,
        0xB53,
        0x859,
        0x950,
        0x7C0,
        0x6C9,
        0x5C3,
        0x4CA,
        0x3C6,
        0x2CF,
        0x1C5,
        0xCC,
        0xFCC,
        0xEC5,
        0xDCF,
        0xCC6,
        0xBCA,
        0xAC3,
        0x9C9,
        0x8C0,
        0x8C0,
        0x9C9,
        0xAC3,
        0xBCA,
        0xCC6,
        0xDCF,
        0xEC5,
        0xFCC,
        0xCC,
        0x1C5,
        0x2CF,
        0x3C6,
        0x4CA,
        0x5C3,
        0x6C9,
        0x7C0,
        0x950,
        0x859,
        0xB53,
        0xA5A,
        0xD56,
        0xC5F,
        0xF55,
        0xE5C,
        0x15C,
        0x55,
        0x35F,
        0x256,
        0x55A,
        0x453,
        0x759,
        0x650,
        0xAF0,
        0xBF9,
        0x8F3,
        0x9FA,
        0xEF6,
        0xFFF,
        0xCF5,
        0xDFC,
        0x2FC,
        0x3F5,
        0xFF,
        0x1F6,
        0x6FA,
        0x7F3,
        0x4F9,
        0x5F0,
        0xB60,
        0xA69,
        0x963,
        0x86A,
        0xF66,
        0xE6F,
        0xD65,
        0xC6C,
        0x36C,
        0x265,
        0x16F,
        0x66,
        0x76A,
        0x663,
        0x569,
        0x460,
        0xCA0,
        0xDA9,
        0xEA3,
        0xFAA,
        0x8A6,
        0x9AF,
        0xAA5,
        0xBAC,
        0x4AC,
        0x5A5,
        0x6AF,
        0x7A6,
        0xAA,
        0x1A3,
        0x2A9,
        0x3A0,
        0xD30,
        0xC39,
        0xF33,
        0xE3A,
        0x936,
        0x83F,
        0xB35,
        0xA3C,
        0x53C,
        0x435,
        0x73F,
        0x636,
        0x13A,
        0x33,
        0x339,
        0x230,
        0xE90,
        0xF99,
        0xC93,
        0xD9A,
        0xA96,
        0xB9F,
        0x895,
        0x99C,
        0x69C,
        0x795,
        0x49F,
        0x596,
        0x29A,
        0x393,
        0x99,
        0x190,
        0xF00,
        0xE09,
        0xD03,
        0xC0A,
        0xB06,
        0xA0F,
        0x905,
        0x80C,
        0x70C,
        0x605,
        0x50F,
        0x406,
        0x30A,
        0x203,
        0x109,
        0x0,
    ]


def _triangle_table() -> List[Int]:
    """Return the triangles of each corner pattern, sixteen entries each,
    ended by -1."""
    return [
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        0,
        8,
        3,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        0,
        1,
        9,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        1,
        8,
        3,
        9,
        8,
        1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        1,
        2,
        10,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        0,
        8,
        3,
        1,
        2,
        10,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        9,
        2,
        10,
        0,
        2,
        9,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        2,
        8,
        3,
        2,
        10,
        8,
        10,
        9,
        8,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        3,
        11,
        2,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        0,
        11,
        2,
        8,
        11,
        0,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        1,
        9,
        0,
        2,
        3,
        11,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        1,
        11,
        2,
        1,
        9,
        11,
        9,
        8,
        11,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        3,
        10,
        1,
        11,
        10,
        3,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        0,
        10,
        1,
        0,
        8,
        10,
        8,
        11,
        10,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        3,
        9,
        0,
        3,
        11,
        9,
        11,
        10,
        9,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        9,
        8,
        10,
        10,
        8,
        11,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        4,
        7,
        8,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        4,
        3,
        0,
        7,
        3,
        4,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        0,
        1,
        9,
        8,
        4,
        7,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        4,
        1,
        9,
        4,
        7,
        1,
        7,
        3,
        1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        1,
        2,
        10,
        8,
        4,
        7,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        3,
        4,
        7,
        3,
        0,
        4,
        1,
        2,
        10,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        9,
        2,
        10,
        9,
        0,
        2,
        8,
        4,
        7,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        2,
        10,
        9,
        2,
        9,
        7,
        2,
        7,
        3,
        7,
        9,
        4,
        -1,
        -1,
        -1,
        -1,
        8,
        4,
        7,
        3,
        11,
        2,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        11,
        4,
        7,
        11,
        2,
        4,
        2,
        0,
        4,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        9,
        0,
        1,
        8,
        4,
        7,
        2,
        3,
        11,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        4,
        7,
        11,
        9,
        4,
        11,
        9,
        11,
        2,
        9,
        2,
        1,
        -1,
        -1,
        -1,
        -1,
        3,
        10,
        1,
        3,
        11,
        10,
        7,
        8,
        4,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        1,
        11,
        10,
        1,
        4,
        11,
        1,
        0,
        4,
        7,
        11,
        4,
        -1,
        -1,
        -1,
        -1,
        4,
        7,
        8,
        9,
        0,
        11,
        9,
        11,
        10,
        11,
        0,
        3,
        -1,
        -1,
        -1,
        -1,
        4,
        7,
        11,
        4,
        11,
        9,
        9,
        11,
        10,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        9,
        5,
        4,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        9,
        5,
        4,
        0,
        8,
        3,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        0,
        5,
        4,
        1,
        5,
        0,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        8,
        5,
        4,
        8,
        3,
        5,
        3,
        1,
        5,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        1,
        2,
        10,
        9,
        5,
        4,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        3,
        0,
        8,
        1,
        2,
        10,
        4,
        9,
        5,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        5,
        2,
        10,
        5,
        4,
        2,
        4,
        0,
        2,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        2,
        10,
        5,
        3,
        2,
        5,
        3,
        5,
        4,
        3,
        4,
        8,
        -1,
        -1,
        -1,
        -1,
        9,
        5,
        4,
        2,
        3,
        11,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        0,
        11,
        2,
        0,
        8,
        11,
        4,
        9,
        5,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        0,
        5,
        4,
        0,
        1,
        5,
        2,
        3,
        11,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        2,
        1,
        5,
        2,
        5,
        8,
        2,
        8,
        11,
        4,
        8,
        5,
        -1,
        -1,
        -1,
        -1,
        10,
        3,
        11,
        10,
        1,
        3,
        9,
        5,
        4,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        4,
        9,
        5,
        0,
        8,
        1,
        8,
        10,
        1,
        8,
        11,
        10,
        -1,
        -1,
        -1,
        -1,
        5,
        4,
        0,
        5,
        0,
        11,
        5,
        11,
        10,
        11,
        0,
        3,
        -1,
        -1,
        -1,
        -1,
        5,
        4,
        8,
        5,
        8,
        10,
        10,
        8,
        11,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        9,
        7,
        8,
        5,
        7,
        9,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        9,
        3,
        0,
        9,
        5,
        3,
        5,
        7,
        3,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        0,
        7,
        8,
        0,
        1,
        7,
        1,
        5,
        7,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        1,
        5,
        3,
        3,
        5,
        7,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        9,
        7,
        8,
        9,
        5,
        7,
        10,
        1,
        2,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        10,
        1,
        2,
        9,
        5,
        0,
        5,
        3,
        0,
        5,
        7,
        3,
        -1,
        -1,
        -1,
        -1,
        8,
        0,
        2,
        8,
        2,
        5,
        8,
        5,
        7,
        10,
        5,
        2,
        -1,
        -1,
        -1,
        -1,
        2,
        10,
        5,
        2,
        5,
        3,
        3,
        5,
        7,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        7,
        9,
        5,
        7,
        8,
        9,
        3,
        11,
        2,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        9,
        5,
        7,
        9,
        7,
        2,
        9,
        2,
        0,
        2,
        7,
        11,
        -1,
        -1,
        -1,
        -1,
        2,
        3,
        11,
        0,
        1,
        8,
        1,
        7,
        8,
        1,
        5,
        7,
        -1,
        -1,
        -1,
        -1,
        11,
        2,
        1,
        11,
        1,
        7,
        7,
        1,
        5,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        9,
        5,
        8,
        8,
        5,
        7,
        10,
        1,
        3,
        10,
        3,
        11,
        -1,
        -1,
        -1,
        -1,
        5,
        7,
        0,
        5,
        0,
        9,
        7,
        11,
        0,
        1,
        0,
        10,
        11,
        10,
        0,
        -1,
        11,
        10,
        0,
        11,
        0,
        3,
        10,
        5,
        0,
        8,
        0,
        7,
        5,
        7,
        0,
        -1,
        11,
        10,
        5,
        7,
        11,
        5,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        10,
        6,
        5,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        0,
        8,
        3,
        5,
        10,
        6,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        9,
        0,
        1,
        5,
        10,
        6,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        1,
        8,
        3,
        1,
        9,
        8,
        5,
        10,
        6,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        1,
        6,
        5,
        2,
        6,
        1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        1,
        6,
        5,
        1,
        2,
        6,
        3,
        0,
        8,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        9,
        6,
        5,
        9,
        0,
        6,
        0,
        2,
        6,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        5,
        9,
        8,
        5,
        8,
        2,
        5,
        2,
        6,
        3,
        2,
        8,
        -1,
        -1,
        -1,
        -1,
        2,
        3,
        11,
        10,
        6,
        5,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        11,
        0,
        8,
        11,
        2,
        0,
        10,
        6,
        5,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        0,
        1,
        9,
        2,
        3,
        11,
        5,
        10,
        6,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        5,
        10,
        6,
        1,
        9,
        2,
        9,
        11,
        2,
        9,
        8,
        11,
        -1,
        -1,
        -1,
        -1,
        6,
        3,
        11,
        6,
        5,
        3,
        5,
        1,
        3,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        0,
        8,
        11,
        0,
        11,
        5,
        0,
        5,
        1,
        5,
        11,
        6,
        -1,
        -1,
        -1,
        -1,
        3,
        11,
        6,
        0,
        3,
        6,
        0,
        6,
        5,
        0,
        5,
        9,
        -1,
        -1,
        -1,
        -1,
        6,
        5,
        9,
        6,
        9,
        11,
        11,
        9,
        8,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        5,
        10,
        6,
        4,
        7,
        8,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        4,
        3,
        0,
        4,
        7,
        3,
        6,
        5,
        10,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        1,
        9,
        0,
        5,
        10,
        6,
        8,
        4,
        7,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        10,
        6,
        5,
        1,
        9,
        7,
        1,
        7,
        3,
        7,
        9,
        4,
        -1,
        -1,
        -1,
        -1,
        6,
        1,
        2,
        6,
        5,
        1,
        4,
        7,
        8,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        1,
        2,
        5,
        5,
        2,
        6,
        3,
        0,
        4,
        3,
        4,
        7,
        -1,
        -1,
        -1,
        -1,
        8,
        4,
        7,
        9,
        0,
        5,
        0,
        6,
        5,
        0,
        2,
        6,
        -1,
        -1,
        -1,
        -1,
        7,
        3,
        9,
        7,
        9,
        4,
        3,
        2,
        9,
        5,
        9,
        6,
        2,
        6,
        9,
        -1,
        3,
        11,
        2,
        7,
        8,
        4,
        10,
        6,
        5,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        5,
        10,
        6,
        4,
        7,
        2,
        4,
        2,
        0,
        2,
        7,
        11,
        -1,
        -1,
        -1,
        -1,
        0,
        1,
        9,
        4,
        7,
        8,
        2,
        3,
        11,
        5,
        10,
        6,
        -1,
        -1,
        -1,
        -1,
        9,
        2,
        1,
        9,
        11,
        2,
        9,
        4,
        11,
        7,
        11,
        4,
        5,
        10,
        6,
        -1,
        8,
        4,
        7,
        3,
        11,
        5,
        3,
        5,
        1,
        5,
        11,
        6,
        -1,
        -1,
        -1,
        -1,
        5,
        1,
        11,
        5,
        11,
        6,
        1,
        0,
        11,
        7,
        11,
        4,
        0,
        4,
        11,
        -1,
        0,
        5,
        9,
        0,
        6,
        5,
        0,
        3,
        6,
        11,
        6,
        3,
        8,
        4,
        7,
        -1,
        6,
        5,
        9,
        6,
        9,
        11,
        4,
        7,
        9,
        7,
        11,
        9,
        -1,
        -1,
        -1,
        -1,
        10,
        4,
        9,
        6,
        4,
        10,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        4,
        10,
        6,
        4,
        9,
        10,
        0,
        8,
        3,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        10,
        0,
        1,
        10,
        6,
        0,
        6,
        4,
        0,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        8,
        3,
        1,
        8,
        1,
        6,
        8,
        6,
        4,
        6,
        1,
        10,
        -1,
        -1,
        -1,
        -1,
        1,
        4,
        9,
        1,
        2,
        4,
        2,
        6,
        4,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        3,
        0,
        8,
        1,
        2,
        9,
        2,
        4,
        9,
        2,
        6,
        4,
        -1,
        -1,
        -1,
        -1,
        0,
        2,
        4,
        4,
        2,
        6,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        8,
        3,
        2,
        8,
        2,
        4,
        4,
        2,
        6,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        10,
        4,
        9,
        10,
        6,
        4,
        11,
        2,
        3,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        0,
        8,
        2,
        2,
        8,
        11,
        4,
        9,
        10,
        4,
        10,
        6,
        -1,
        -1,
        -1,
        -1,
        3,
        11,
        2,
        0,
        1,
        6,
        0,
        6,
        4,
        6,
        1,
        10,
        -1,
        -1,
        -1,
        -1,
        6,
        4,
        1,
        6,
        1,
        10,
        4,
        8,
        1,
        2,
        1,
        11,
        8,
        11,
        1,
        -1,
        9,
        6,
        4,
        9,
        3,
        6,
        9,
        1,
        3,
        11,
        6,
        3,
        -1,
        -1,
        -1,
        -1,
        8,
        11,
        1,
        8,
        1,
        0,
        11,
        6,
        1,
        9,
        1,
        4,
        6,
        4,
        1,
        -1,
        3,
        11,
        6,
        3,
        6,
        0,
        0,
        6,
        4,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        6,
        4,
        8,
        11,
        6,
        8,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        7,
        10,
        6,
        7,
        8,
        10,
        8,
        9,
        10,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        0,
        7,
        3,
        0,
        10,
        7,
        0,
        9,
        10,
        6,
        7,
        10,
        -1,
        -1,
        -1,
        -1,
        10,
        6,
        7,
        1,
        10,
        7,
        1,
        7,
        8,
        1,
        8,
        0,
        -1,
        -1,
        -1,
        -1,
        10,
        6,
        7,
        10,
        7,
        1,
        1,
        7,
        3,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        1,
        2,
        6,
        1,
        6,
        8,
        1,
        8,
        9,
        8,
        6,
        7,
        -1,
        -1,
        -1,
        -1,
        2,
        6,
        9,
        2,
        9,
        1,
        6,
        7,
        9,
        0,
        9,
        3,
        7,
        3,
        9,
        -1,
        7,
        8,
        0,
        7,
        0,
        6,
        6,
        0,
        2,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        7,
        3,
        2,
        6,
        7,
        2,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        2,
        3,
        11,
        10,
        6,
        8,
        10,
        8,
        9,
        8,
        6,
        7,
        -1,
        -1,
        -1,
        -1,
        2,
        0,
        7,
        2,
        7,
        11,
        0,
        9,
        7,
        6,
        7,
        10,
        9,
        10,
        7,
        -1,
        1,
        8,
        0,
        1,
        7,
        8,
        1,
        10,
        7,
        6,
        7,
        10,
        2,
        3,
        11,
        -1,
        11,
        2,
        1,
        11,
        1,
        7,
        10,
        6,
        1,
        6,
        7,
        1,
        -1,
        -1,
        -1,
        -1,
        8,
        9,
        6,
        8,
        6,
        7,
        9,
        1,
        6,
        11,
        6,
        3,
        1,
        3,
        6,
        -1,
        0,
        9,
        1,
        11,
        6,
        7,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        7,
        8,
        0,
        7,
        0,
        6,
        3,
        11,
        0,
        11,
        6,
        0,
        -1,
        -1,
        -1,
        -1,
        7,
        11,
        6,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        7,
        6,
        11,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        3,
        0,
        8,
        11,
        7,
        6,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        0,
        1,
        9,
        11,
        7,
        6,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        8,
        1,
        9,
        8,
        3,
        1,
        11,
        7,
        6,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        10,
        1,
        2,
        6,
        11,
        7,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        1,
        2,
        10,
        3,
        0,
        8,
        6,
        11,
        7,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        2,
        9,
        0,
        2,
        10,
        9,
        6,
        11,
        7,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        6,
        11,
        7,
        2,
        10,
        3,
        10,
        8,
        3,
        10,
        9,
        8,
        -1,
        -1,
        -1,
        -1,
        7,
        2,
        3,
        6,
        2,
        7,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        7,
        0,
        8,
        7,
        6,
        0,
        6,
        2,
        0,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        2,
        7,
        6,
        2,
        3,
        7,
        0,
        1,
        9,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        1,
        6,
        2,
        1,
        8,
        6,
        1,
        9,
        8,
        8,
        7,
        6,
        -1,
        -1,
        -1,
        -1,
        10,
        7,
        6,
        10,
        1,
        7,
        1,
        3,
        7,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        10,
        7,
        6,
        1,
        7,
        10,
        1,
        8,
        7,
        1,
        0,
        8,
        -1,
        -1,
        -1,
        -1,
        0,
        3,
        7,
        0,
        7,
        10,
        0,
        10,
        9,
        6,
        10,
        7,
        -1,
        -1,
        -1,
        -1,
        7,
        6,
        10,
        7,
        10,
        8,
        8,
        10,
        9,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        6,
        8,
        4,
        11,
        8,
        6,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        3,
        6,
        11,
        3,
        0,
        6,
        0,
        4,
        6,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        8,
        6,
        11,
        8,
        4,
        6,
        9,
        0,
        1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        9,
        4,
        6,
        9,
        6,
        3,
        9,
        3,
        1,
        11,
        3,
        6,
        -1,
        -1,
        -1,
        -1,
        6,
        8,
        4,
        6,
        11,
        8,
        2,
        10,
        1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        1,
        2,
        10,
        3,
        0,
        11,
        0,
        6,
        11,
        0,
        4,
        6,
        -1,
        -1,
        -1,
        -1,
        4,
        11,
        8,
        4,
        6,
        11,
        0,
        2,
        9,
        2,
        10,
        9,
        -1,
        -1,
        -1,
        -1,
        10,
        9,
        3,
        10,
        3,
        2,
        9,
        4,
        3,
        11,
        3,
        6,
        4,
        6,
        3,
        -1,
        8,
        2,
        3,
        8,
        4,
        2,
        4,
        6,
        2,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        0,
        4,
        2,
        4,
        6,
        2,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        1,
        9,
        0,
        2,
        3,
        4,
        2,
        4,
        6,
        4,
        3,
        8,
        -1,
        -1,
        -1,
        -1,
        1,
        9,
        4,
        1,
        4,
        2,
        2,
        4,
        6,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        8,
        1,
        3,
        8,
        6,
        1,
        8,
        4,
        6,
        6,
        10,
        1,
        -1,
        -1,
        -1,
        -1,
        10,
        1,
        0,
        10,
        0,
        6,
        6,
        0,
        4,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        4,
        6,
        3,
        4,
        3,
        8,
        6,
        10,
        3,
        0,
        3,
        9,
        10,
        9,
        3,
        -1,
        10,
        9,
        4,
        6,
        10,
        4,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        4,
        9,
        5,
        7,
        6,
        11,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        0,
        8,
        3,
        4,
        9,
        5,
        11,
        7,
        6,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        5,
        0,
        1,
        5,
        4,
        0,
        7,
        6,
        11,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        11,
        7,
        6,
        8,
        3,
        4,
        3,
        5,
        4,
        3,
        1,
        5,
        -1,
        -1,
        -1,
        -1,
        9,
        5,
        4,
        10,
        1,
        2,
        7,
        6,
        11,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        6,
        11,
        7,
        1,
        2,
        10,
        0,
        8,
        3,
        4,
        9,
        5,
        -1,
        -1,
        -1,
        -1,
        7,
        6,
        11,
        5,
        4,
        10,
        4,
        2,
        10,
        4,
        0,
        2,
        -1,
        -1,
        -1,
        -1,
        3,
        4,
        8,
        3,
        5,
        4,
        3,
        2,
        5,
        10,
        5,
        2,
        11,
        7,
        6,
        -1,
        7,
        2,
        3,
        7,
        6,
        2,
        5,
        4,
        9,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        9,
        5,
        4,
        0,
        8,
        6,
        0,
        6,
        2,
        6,
        8,
        7,
        -1,
        -1,
        -1,
        -1,
        3,
        6,
        2,
        3,
        7,
        6,
        1,
        5,
        0,
        5,
        4,
        0,
        -1,
        -1,
        -1,
        -1,
        6,
        2,
        8,
        6,
        8,
        7,
        2,
        1,
        8,
        4,
        8,
        5,
        1,
        5,
        8,
        -1,
        9,
        5,
        4,
        10,
        1,
        6,
        1,
        7,
        6,
        1,
        3,
        7,
        -1,
        -1,
        -1,
        -1,
        1,
        6,
        10,
        1,
        7,
        6,
        1,
        0,
        7,
        8,
        7,
        0,
        9,
        5,
        4,
        -1,
        4,
        0,
        10,
        4,
        10,
        5,
        0,
        3,
        10,
        6,
        10,
        7,
        3,
        7,
        10,
        -1,
        7,
        6,
        10,
        7,
        10,
        8,
        5,
        4,
        10,
        4,
        8,
        10,
        -1,
        -1,
        -1,
        -1,
        6,
        9,
        5,
        6,
        11,
        9,
        11,
        8,
        9,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        3,
        6,
        11,
        0,
        6,
        3,
        0,
        5,
        6,
        0,
        9,
        5,
        -1,
        -1,
        -1,
        -1,
        0,
        11,
        8,
        0,
        5,
        11,
        0,
        1,
        5,
        5,
        6,
        11,
        -1,
        -1,
        -1,
        -1,
        6,
        11,
        3,
        6,
        3,
        5,
        5,
        3,
        1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        1,
        2,
        10,
        9,
        5,
        11,
        9,
        11,
        8,
        11,
        5,
        6,
        -1,
        -1,
        -1,
        -1,
        0,
        11,
        3,
        0,
        6,
        11,
        0,
        9,
        6,
        5,
        6,
        9,
        1,
        2,
        10,
        -1,
        11,
        8,
        5,
        11,
        5,
        6,
        8,
        0,
        5,
        10,
        5,
        2,
        0,
        2,
        5,
        -1,
        6,
        11,
        3,
        6,
        3,
        5,
        2,
        10,
        3,
        10,
        5,
        3,
        -1,
        -1,
        -1,
        -1,
        5,
        8,
        9,
        5,
        2,
        8,
        5,
        6,
        2,
        3,
        8,
        2,
        -1,
        -1,
        -1,
        -1,
        9,
        5,
        6,
        9,
        6,
        0,
        0,
        6,
        2,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        1,
        5,
        8,
        1,
        8,
        0,
        5,
        6,
        8,
        3,
        8,
        2,
        6,
        2,
        8,
        -1,
        1,
        5,
        6,
        2,
        1,
        6,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        1,
        3,
        6,
        1,
        6,
        10,
        3,
        8,
        6,
        5,
        6,
        9,
        8,
        9,
        6,
        -1,
        10,
        1,
        0,
        10,
        0,
        6,
        9,
        5,
        0,
        5,
        6,
        0,
        -1,
        -1,
        -1,
        -1,
        0,
        3,
        8,
        5,
        6,
        10,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        10,
        5,
        6,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        11,
        5,
        10,
        7,
        5,
        11,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        11,
        5,
        10,
        11,
        7,
        5,
        8,
        3,
        0,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        5,
        11,
        7,
        5,
        10,
        11,
        1,
        9,
        0,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        10,
        7,
        5,
        10,
        11,
        7,
        9,
        8,
        1,
        8,
        3,
        1,
        -1,
        -1,
        -1,
        -1,
        11,
        1,
        2,
        11,
        7,
        1,
        7,
        5,
        1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        0,
        8,
        3,
        1,
        2,
        7,
        1,
        7,
        5,
        7,
        2,
        11,
        -1,
        -1,
        -1,
        -1,
        9,
        7,
        5,
        9,
        2,
        7,
        9,
        0,
        2,
        2,
        11,
        7,
        -1,
        -1,
        -1,
        -1,
        7,
        5,
        2,
        7,
        2,
        11,
        5,
        9,
        2,
        3,
        2,
        8,
        9,
        8,
        2,
        -1,
        2,
        5,
        10,
        2,
        3,
        5,
        3,
        7,
        5,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        8,
        2,
        0,
        8,
        5,
        2,
        8,
        7,
        5,
        10,
        2,
        5,
        -1,
        -1,
        -1,
        -1,
        9,
        0,
        1,
        5,
        10,
        3,
        5,
        3,
        7,
        3,
        10,
        2,
        -1,
        -1,
        -1,
        -1,
        9,
        8,
        2,
        9,
        2,
        1,
        8,
        7,
        2,
        10,
        2,
        5,
        7,
        5,
        2,
        -1,
        1,
        3,
        5,
        3,
        7,
        5,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        0,
        8,
        7,
        0,
        7,
        1,
        1,
        7,
        5,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        9,
        0,
        3,
        9,
        3,
        5,
        5,
        3,
        7,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        9,
        8,
        7,
        5,
        9,
        7,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        5,
        8,
        4,
        5,
        10,
        8,
        10,
        11,
        8,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        5,
        0,
        4,
        5,
        11,
        0,
        5,
        10,
        11,
        11,
        3,
        0,
        -1,
        -1,
        -1,
        -1,
        0,
        1,
        9,
        8,
        4,
        10,
        8,
        10,
        11,
        10,
        4,
        5,
        -1,
        -1,
        -1,
        -1,
        10,
        11,
        4,
        10,
        4,
        5,
        11,
        3,
        4,
        9,
        4,
        1,
        3,
        1,
        4,
        -1,
        2,
        5,
        1,
        2,
        8,
        5,
        2,
        11,
        8,
        4,
        5,
        8,
        -1,
        -1,
        -1,
        -1,
        0,
        4,
        11,
        0,
        11,
        3,
        4,
        5,
        11,
        2,
        11,
        1,
        5,
        1,
        11,
        -1,
        0,
        2,
        5,
        0,
        5,
        9,
        2,
        11,
        5,
        4,
        5,
        8,
        11,
        8,
        5,
        -1,
        9,
        4,
        5,
        2,
        11,
        3,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        2,
        5,
        10,
        3,
        5,
        2,
        3,
        4,
        5,
        3,
        8,
        4,
        -1,
        -1,
        -1,
        -1,
        5,
        10,
        2,
        5,
        2,
        4,
        4,
        2,
        0,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        3,
        10,
        2,
        3,
        5,
        10,
        3,
        8,
        5,
        4,
        5,
        8,
        0,
        1,
        9,
        -1,
        5,
        10,
        2,
        5,
        2,
        4,
        1,
        9,
        2,
        9,
        4,
        2,
        -1,
        -1,
        -1,
        -1,
        8,
        4,
        5,
        8,
        5,
        3,
        3,
        5,
        1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        0,
        4,
        5,
        1,
        0,
        5,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        8,
        4,
        5,
        8,
        5,
        3,
        9,
        0,
        5,
        0,
        3,
        5,
        -1,
        -1,
        -1,
        -1,
        9,
        4,
        5,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        4,
        11,
        7,
        4,
        9,
        11,
        9,
        10,
        11,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        0,
        8,
        3,
        4,
        9,
        7,
        9,
        11,
        7,
        9,
        10,
        11,
        -1,
        -1,
        -1,
        -1,
        1,
        10,
        11,
        1,
        11,
        4,
        1,
        4,
        0,
        7,
        4,
        11,
        -1,
        -1,
        -1,
        -1,
        3,
        1,
        4,
        3,
        4,
        8,
        1,
        10,
        4,
        7,
        4,
        11,
        10,
        11,
        4,
        -1,
        4,
        11,
        7,
        9,
        11,
        4,
        9,
        2,
        11,
        9,
        1,
        2,
        -1,
        -1,
        -1,
        -1,
        9,
        7,
        4,
        9,
        11,
        7,
        9,
        1,
        11,
        2,
        11,
        1,
        0,
        8,
        3,
        -1,
        11,
        7,
        4,
        11,
        4,
        2,
        2,
        4,
        0,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        11,
        7,
        4,
        11,
        4,
        2,
        8,
        3,
        4,
        3,
        2,
        4,
        -1,
        -1,
        -1,
        -1,
        2,
        9,
        10,
        2,
        7,
        9,
        2,
        3,
        7,
        7,
        4,
        9,
        -1,
        -1,
        -1,
        -1,
        9,
        10,
        7,
        9,
        7,
        4,
        10,
        2,
        7,
        8,
        7,
        0,
        2,
        0,
        7,
        -1,
        3,
        7,
        10,
        3,
        10,
        2,
        7,
        4,
        10,
        1,
        10,
        0,
        4,
        0,
        10,
        -1,
        1,
        10,
        2,
        8,
        7,
        4,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        4,
        9,
        1,
        4,
        1,
        7,
        7,
        1,
        3,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        4,
        9,
        1,
        4,
        1,
        7,
        0,
        8,
        1,
        8,
        7,
        1,
        -1,
        -1,
        -1,
        -1,
        4,
        0,
        3,
        7,
        4,
        3,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        4,
        8,
        7,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        9,
        10,
        8,
        10,
        11,
        8,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        3,
        0,
        9,
        3,
        9,
        11,
        11,
        9,
        10,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        0,
        1,
        10,
        0,
        10,
        8,
        8,
        10,
        11,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        3,
        1,
        10,
        11,
        3,
        10,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        1,
        2,
        11,
        1,
        11,
        9,
        9,
        11,
        8,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        3,
        0,
        9,
        3,
        9,
        11,
        1,
        2,
        9,
        2,
        11,
        9,
        -1,
        -1,
        -1,
        -1,
        0,
        2,
        11,
        8,
        0,
        11,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        3,
        2,
        11,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        2,
        3,
        8,
        2,
        8,
        10,
        10,
        8,
        9,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        9,
        10,
        2,
        0,
        9,
        2,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        2,
        3,
        8,
        2,
        8,
        10,
        0,
        1,
        8,
        1,
        10,
        8,
        -1,
        -1,
        -1,
        -1,
        1,
        10,
        2,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        1,
        3,
        8,
        9,
        1,
        8,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        0,
        9,
        1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        0,
        3,
        8,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
    ]
