# Copyright (c) 2026 Seth Kitchen, PE
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
# Noncommercial use is free; commercial use requires a paid license.
# See LICENSE, LICENSE-COMMERCIAL.md and THIRD-PARTY-NOTICES.md.

"""Generated checks against captured Mesa GLSL ES 3.0 references.

Generated by generate_mojo_tests.py from fixtures/fixtures.json.
Unsigned expectations are compared before conversion to float color.
Captured expectations are independent of the node interpreter.
"""

from materials.glsl import compile_shader_material
from tests.test_glsl import VERTEX, run
from std.testing import TestSuite, assert_equal, assert_raises

from materials.nodes import (
    AT_FRAGMENT,
    AT_RIGHT,
    AT_UP,
    COLOR_NODE,
    NodeContext,
    NodeInputs,
    NodeProgram,
    NodeSource,
    run_nodes,
)
from math.vector3 import Vector3
from render.framebuffer import FloatColor

comptime Lanes = SIMD[DType.float32, 4]


struct FixtureSource(NodeSource):
    """Read program words and use the independent fixture's pixel center."""

    var code: List[Float32]

    def __init__(out self, program: NodeProgram):
        """Copy the program's encoded words."""
        self.code = program.code.copy()

    def word(self, at: Int) -> Float32:
        """Read one program word without a numeric conversion."""
        return self.code[at]

    def sample(self, slot: Int, u: Float32, v: Float32) -> FloatColor:
        """Return white; the integer fixtures do not sample textures."""
        return FloatColor(1, 1, 1, 1)

    def sample_level(
        self, slot: Int, u: Float32, v: Float32, level: Float32
    ) -> FloatColor:
        """Return white; the integer fixtures do not sample textures."""
        return FloatColor(1, 1, 1, 1)

    def fetch(self, slot: Int, x: Int, y: Int, level: Int) -> FloatColor:
        """Return white; the integer fixtures do not fetch textures."""
        return FloatColor(1, 1, 1, 1)

    def size(self, slot: Int, level: Int) -> Lanes:
        """Return a one-pixel size for the unused texture interface."""
        return Lanes(1, 1, 0, 0)

    def shares(self, context: NodeContext) -> Lanes:
        """Select one corner for the unused interpolated attributes."""
        return Lanes(1, 0, 0, 0)

    def frag_coord(self, context: NodeContext) -> Lanes:
        """Match the independent 1-by-1 GLES framebuffer center."""
        if context == AT_RIGHT:
            return Lanes(1.5, 0.5, 0, 1)
        if context == AT_UP:
            return Lanes(0.5, 1.5, 0, 1)
        return Lanes(0.5, 0.5, 0, 1)

    def corner(self, context: NodeContext) -> NodeInputs:
        """Return valid attributes that these integer fixtures do not read."""
        return NodeInputs(
            0,
            0,
            Vector3(0, 0, 0),
            Vector3(0, 0, 1),
            Vector3(1, 1, 1),
            Vector3(0, 0, 0),
            False,
        )


def fixture_run(program: NodeProgram) -> Lanes:
    """Evaluate one integer fixture at the reference pixel center."""
    var source = FixtureSource(program)
    return run_nodes(source, COLOR_NODE, source.corner(AT_FRAGMENT))


def test_reference_uint_literal_boundaries() raises:
    """Check independent fixture uint_literal_boundaries."""
    # Expected UInt32 readback: ffffff000000000101000001ffffffff
    var program = compile_shader_material(
        VERTEX,
        """
        void main() {
            uvec4 result = uvec4(0u);
        result = uvec4(16777215u, 16777216u, 16777217u, 4294967295u);

            gl_FragColor = vec4(float(all(equal(result, uvec4(16777215u, 16777216u, 16777217u, 4294967295u)))));
        }
        """,
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_literal_sign_boundary() raises:
    """Check independent fixture uint_literal_sign_boundary."""
    # Expected UInt32 readback: ffffff7f0000008001000080ffffffff
    var program = compile_shader_material(
        VERTEX,
        """
        void main() {
            uvec4 result = uvec4(0u);
        result = uvec4(2147483647u, 2147483648u, 2147483649u, 0xffffffffu);

            gl_FragColor = vec4(float(all(equal(result, uvec4(2147483647u, 2147483648u, 2147483649u, 4294967295u)))));
        }
        """,
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_const_wrap() raises:
    """Check independent fixture uint_const_wrap."""
    # Expected UInt32 readback: 00000000ffffffff00000000ffffffff
    var program = compile_shader_material(
        VERTEX,
        """
        void main() {
            uvec4 result = uvec4(0u);
        result = uvec4(4294967295u + 1u, 0u - 1u, 0x80000000u * 2u, -1u);

            gl_FragColor = vec4(float(all(equal(result, uvec4(0u, 4294967295u, 0u, 4294967295u)))));
        }
        """,
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_constructors() raises:
    """Check independent fixture uint_constructors."""
    # Expected UInt32 readback: ffffffff010000000000000000000001
    var program = compile_shader_material(
        VERTEX,
        """
        void main() {
            uvec4 result = uvec4(0u);
        result = uvec4(uint(-1), uint(true), uint(false), uint(16777216.0));

            gl_FragColor = vec4(float(all(equal(result, uvec4(4294967295u, 1u, 0u, 16777216u)))));
        }
        """,
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_join_uvec2_uvec3() raises:
    """Check independent fixture uint_join_uvec2_uvec3."""
    # Expected UInt32 readback: 0100000101000080ffffffff00000080
    var program = compile_shader_material(
        VERTEX,
        """
        void main() {
            uvec4 result = uvec4(0u);
        uvec2 a = uvec2(16777217u, 2147483649u); uvec3 b = uvec3(a, 4294967295u); result = uvec4(b, 2147483648u);

            gl_FragColor = vec4(float(all(equal(result, uvec4(16777217u, 2147483649u, 4294967295u, 2147483648u)))));
        }
        """,
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_constructor_splat() raises:
    """Check independent fixture uint_constructor_splat."""
    # Expected UInt32 readback: 01000001010000010100000101000001
    var program = compile_shader_material(
        VERTEX,
        """
        void main() {
            uvec4 result = uvec4(0u);
        uvec4 a = uvec4(16777217u); result = a;

            gl_FragColor = vec4(float(all(equal(result, uvec4(16777217u, 16777217u, 16777217u, 16777217u)))));
        }
        """,
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_swizzle_join() raises:
    """Check independent fixture uint_swizzle_join."""
    # Expected UInt32 readback: ffffffff010000800100000100000080
    var program = compile_shader_material(
        VERTEX,
        """
        void main() {
            uvec4 result = uvec4(0u);
        uvec4 a = uvec4(16777217u, 2147483648u, 2147483649u, 4294967295u); result = uvec4(a.wz, a.xy);

            gl_FragColor = vec4(float(all(equal(result, uvec4(4294967295u, 2147483649u, 16777217u, 2147483648u)))));
        }
        """,
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_swizzle_assignment() raises:
    """Check independent fixture uint_swizzle_assignment."""
    # Expected UInt32 readback: ffffffff0100008001000080ffffffff
    var program = compile_shader_material(
        VERTEX,
        """
        void main() {
            uvec4 result = uvec4(0u);
        uvec4 a = uvec4(16777217u, 2147483648u, 2147483649u, 4294967295u); a.xy = a.wz; result = a;

            gl_FragColor = vec4(float(all(equal(result, uvec4(4294967295u, 2147483649u, 2147483649u, 4294967295u)))));
        }
        """,
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_uniform_exact() raises:
    """Check independent fixture uint_uniform_exact."""
    # Expected UInt32 readback: 000000000100000100000080ffffffff
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        result = uV;

            gl_FragColor = vec4(float(all(equal(result, uvec4(0u, 16777217u, 2147483648u, 4294967295u)))));
        }
        """,
    )
    program.set_uniform_uint(
        "uV", SIMD[DType.uint32, 4](0, 16777217, 2147483648, 4294967295)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_uniform_wrap() raises:
    """Check independent fixture uint_uniform_wrap."""
    # Expected UInt32 readback: 0000000001000000fffffffe01000000
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        result = uvec4(uA + 1u, 0u - uA, uA * uB, -uA);

            gl_FragColor = vec4(float(all(equal(result, uvec4(0u, 1u, 4278190079u, 1u)))));
        }
        """,
    )
    program.set_uniform_uint("uA", UInt32(4294967295))
    program.set_uniform_uint("uB", UInt32(16777217))
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_uniform_div_rem() raises:
    """Check independent fixture uint_uniform_div_rem."""
    # Expected UInt32 readback: ff00000000ffff0001000000ffffff7f
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        result = uvec4(uA / uB, uA % uB, uA / 2147483648u, uA % 2147483648u);

            gl_FragColor = vec4(float(all(equal(result, uvec4(255u, 16776960u, 1u, 2147483647u)))));
        }
        """,
    )
    program.set_uniform_uint("uA", UInt32(4294967295))
    program.set_uniform_uint("uB", UInt32(16777217))
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_uniform_vector_arithmetic() raises:
    """Check independent fixture uint_uniform_vector_arithmetic."""
    # Expected UInt32 readback: 010000000300000602000000f4ffffff
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        result = (uV + uW) * uvec4(1u, 3u, 2u, 4u);

            gl_FragColor = vec4(float(all(equal(result, uvec4(1u, 100663299u, 2u, 4294967284u)))));
        }
        """,
    )
    program.set_uniform_uint(
        "uV", SIMD[DType.uint32, 4](0, 16777217, 2147483648, 4294967295)
    )
    program.set_uniform_uint(
        "uW", SIMD[DType.uint32, 4](1, 16777216, 2147483649, 4294967294)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_uniform_vector_div_rem() raises:
    """Check independent fixture uint_uniform_vector_div_rem."""
    # Expected UInt32 readback: 000000005755550000000040ffff0000
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        result = (uV / uvec4(1u, 3u, 2u, 65537u)) + (uV % uvec4(1u, 3u, 2u, 65537u));

            gl_FragColor = vec4(float(all(equal(result, uvec4(0u, 5592407u, 1073741824u, 65535u)))));
        }
        """,
    )
    program.set_uniform_uint(
        "uV", SIMD[DType.uint32, 4](0, 16777217, 2147483648, 4294967295)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_uniform_bitwise() raises:
    """Check independent fixture uint_uniform_bitwise."""
    # Expected UInt32 readback: 01000001fffffffffefffffefefffffe
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        result = uvec4(uA & uB, uA | uB, uA ^ uB, ~uB);

            gl_FragColor = vec4(float(all(equal(result, uvec4(16777217u, 4294967295u, 4278190078u, 4278190078u)))));
        }
        """,
    )
    program.set_uniform_uint("uA", UInt32(4294967295))
    program.set_uniform_uint("uB", UInt32(16777217))
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_uniform_shift_widths() raises:
    """Check independent fixture uint_uniform_shift_widths."""
    # Expected UInt32 readback: ffffffffffffff7fffff000001000000
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        result = uvec4(uA >> 0u, uA >> 1u, uA >> 16u, uA >> 31u);

            gl_FragColor = vec4(float(all(equal(result, uvec4(4294967295u, 2147483647u, 65535u, 1u)))));
        }
        """,
    )
    program.set_uniform_uint("uA", UInt32(4294967295))
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_uniform_shift_left() raises:
    """Check independent fixture uint_uniform_shift_left."""
    # Expected UInt32 readback: 01000001020000020000010000000080
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        result = uvec4(uB << 0, uB << 1, uB << 16, uB << 31);

            gl_FragColor = vec4(float(all(equal(result, uvec4(16777217u, 33554434u, 65536u, 2147483648u)))));
        }
        """,
    )
    program.set_uniform_uint("uB", UInt32(16777217))
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_vector_shift() raises:
    """Check independent fixture uint_vector_shift."""
    # Expected UInt32 readback: 00000000000080000080000001000000
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        result = uV >> uvec4(0u, 1u, 16u, 31u);

            gl_FragColor = vec4(float(all(equal(result, uvec4(0u, 8388608u, 32768u, 1u)))));
        }
        """,
    )
    program.set_uniform_uint(
        "uV", SIMD[DType.uint32, 4](0, 16777217, 2147483648, 4294967295)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_vector_shift_scalar() raises:
    """Check independent fixture uint_vector_shift_scalar."""
    # Expected UInt32 readback: 000000000200000200000000feffffff
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        result = uV << 1u;

            gl_FragColor = vec4(float(all(equal(result, uvec4(0u, 33554434u, 0u, 4294967294u)))));
        }
        """,
    )
    program.set_uniform_uint(
        "uV", SIMD[DType.uint32, 4](0, 16777217, 2147483648, 4294967295)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_scalar_minmaxclamp() raises:
    """Check independent fixture uint_scalar_minmaxclamp."""
    # Expected UInt32 readback: 01000001ffffffff0100008000000080
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        result = uvec4(min(uA, uB), max(uA, uB), clamp(uA, 16777216u, 2147483649u), clamp(uB, 2147483648u, uA));

            gl_FragColor = vec4(float(all(equal(result, uvec4(16777217u, 4294967295u, 2147483649u, 2147483648u)))));
        }
        """,
    )
    program.set_uniform_uint("uA", UInt32(4294967295))
    program.set_uniform_uint("uB", UInt32(16777217))
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_vector_min() raises:
    """Check independent fixture uint_vector_min."""
    # Expected UInt32 readback: 000000000000000100000080feffffff
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        result = min(uV, uW);

            gl_FragColor = vec4(float(all(equal(result, uvec4(0u, 16777216u, 2147483648u, 4294967294u)))));
        }
        """,
    )
    program.set_uniform_uint(
        "uV", SIMD[DType.uint32, 4](0, 16777217, 2147483648, 4294967295)
    )
    program.set_uniform_uint(
        "uW", SIMD[DType.uint32, 4](1, 16777216, 2147483649, 4294967294)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_vector_max() raises:
    """Check independent fixture uint_vector_max."""
    # Expected UInt32 readback: 010000000100000101000080ffffffff
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        result = max(uV, uW);

            gl_FragColor = vec4(float(all(equal(result, uvec4(1u, 16777217u, 2147483649u, 4294967295u)))));
        }
        """,
    )
    program.set_uniform_uint(
        "uV", SIMD[DType.uint32, 4](0, 16777217, 2147483648, 4294967295)
    )
    program.set_uniform_uint(
        "uW", SIMD[DType.uint32, 4](1, 16777216, 2147483649, 4294967294)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_vector_min_scalar() raises:
    """Check independent fixture uint_vector_min_scalar."""
    # Expected UInt32 readback: 00000000010000010000008000000080
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        result = min(uV, 2147483648u);

            gl_FragColor = vec4(float(all(equal(result, uvec4(0u, 16777217u, 2147483648u, 2147483648u)))));
        }
        """,
    )
    program.set_uniform_uint(
        "uV", SIMD[DType.uint32, 4](0, 16777217, 2147483648, 4294967295)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_vector_max_scalar() raises:
    """Check independent fixture uint_vector_max_scalar."""
    # Expected UInt32 readback: 010000010100000100000080ffffffff
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        result = max(uV, 16777217u);

            gl_FragColor = vec4(float(all(equal(result, uvec4(16777217u, 16777217u, 2147483648u, 4294967295u)))));
        }
        """,
    )
    program.set_uniform_uint(
        "uV", SIMD[DType.uint32, 4](0, 16777217, 2147483648, 4294967295)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_vector_clamp_scalar() raises:
    """Check independent fixture uint_vector_clamp_scalar."""
    # Expected UInt32 readback: 00000001010000010000008001000080
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        result = clamp(uV, 16777216u, 2147483649u);

            gl_FragColor = vec4(float(all(equal(result, uvec4(16777216u, 16777217u, 2147483648u, 2147483649u)))));
        }
        """,
    )
    program.set_uniform_uint(
        "uV", SIMD[DType.uint32, 4](0, 16777217, 2147483648, 4294967295)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_vector_clamp_vector() raises:
    """Check independent fixture uint_vector_clamp_vector."""
    # Expected UInt32 readback: 000000000100000100000080feffffff
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        result = clamp(uV, uvec4(0u, 16777216u, 2147483647u, 2147483648u), uvec4(1u, 16777218u, 2147483649u, 4294967294u));

            gl_FragColor = vec4(float(all(equal(result, uvec4(0u, 16777217u, 2147483648u, 4294967294u)))));
        }
        """,
    )
    program.set_uniform_uint(
        "uV", SIMD[DType.uint32, 4](0, 16777217, 2147483648, 4294967295)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_scalar_comparisons() raises:
    """Check independent fixture uint_scalar_comparisons."""
    # Expected UInt32 readback: 01000000010000000100000001000000
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        result = uvec4(uint(uA > uB), uint(uB < uA), uint(uA == 4294967295u), uint(uB != 16777216u));

            gl_FragColor = vec4(float(all(equal(result, uvec4(1u, 1u, 1u, 1u)))));
        }
        """,
    )
    program.set_uniform_uint("uA", UInt32(4294967295))
    program.set_uniform_uint("uB", UInt32(16777217))
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_scalar_equal_order() raises:
    """Check independent fixture uint_scalar_equal_order."""
    # Expected UInt32 readback: 00000000010000000000000000000000
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        result = uvec4(uint(uA <= uB), uint(uA >= uB), uint(uB == 16777216u), uint(uA != uA));

            gl_FragColor = vec4(float(all(equal(result, uvec4(0u, 1u, 0u, 0u)))));
        }
        """,
    )
    program.set_uniform_uint("uA", UInt32(4294967295))
    program.set_uniform_uint("uB", UInt32(16777217))
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_vector_lessThan() raises:
    """Check independent fixture uint_vector_lessThan."""
    # Expected UInt32 readback: 01000000000000000100000000000000
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        result = uvec4(lessThan(uV, uW));

            gl_FragColor = vec4(float(all(equal(result, uvec4(1u, 0u, 1u, 0u)))));
        }
        """,
    )
    program.set_uniform_uint(
        "uV", SIMD[DType.uint32, 4](0, 16777217, 2147483648, 4294967295)
    )
    program.set_uniform_uint(
        "uW", SIMD[DType.uint32, 4](1, 16777216, 2147483649, 4294967294)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_vector_lessThanEqual() raises:
    """Check independent fixture uint_vector_lessThanEqual."""
    # Expected UInt32 readback: 01000000000000000100000000000000
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        result = uvec4(lessThanEqual(uV, uW));

            gl_FragColor = vec4(float(all(equal(result, uvec4(1u, 0u, 1u, 0u)))));
        }
        """,
    )
    program.set_uniform_uint(
        "uV", SIMD[DType.uint32, 4](0, 16777217, 2147483648, 4294967295)
    )
    program.set_uniform_uint(
        "uW", SIMD[DType.uint32, 4](1, 16777216, 2147483649, 4294967294)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_vector_greaterThan() raises:
    """Check independent fixture uint_vector_greaterThan."""
    # Expected UInt32 readback: 00000000010000000000000001000000
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        result = uvec4(greaterThan(uV, uW));

            gl_FragColor = vec4(float(all(equal(result, uvec4(0u, 1u, 0u, 1u)))));
        }
        """,
    )
    program.set_uniform_uint(
        "uV", SIMD[DType.uint32, 4](0, 16777217, 2147483648, 4294967295)
    )
    program.set_uniform_uint(
        "uW", SIMD[DType.uint32, 4](1, 16777216, 2147483649, 4294967294)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_vector_greaterThanEqual() raises:
    """Check independent fixture uint_vector_greaterThanEqual."""
    # Expected UInt32 readback: 00000000010000000000000001000000
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        result = uvec4(greaterThanEqual(uV, uW));

            gl_FragColor = vec4(float(all(equal(result, uvec4(0u, 1u, 0u, 1u)))));
        }
        """,
    )
    program.set_uniform_uint(
        "uV", SIMD[DType.uint32, 4](0, 16777217, 2147483648, 4294967295)
    )
    program.set_uniform_uint(
        "uW", SIMD[DType.uint32, 4](1, 16777216, 2147483649, 4294967294)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_vector_equal() raises:
    """Check independent fixture uint_vector_equal."""
    # Expected UInt32 readback: 00000000000000000000000000000000
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        result = uvec4(equal(uV, uW));

            gl_FragColor = vec4(float(all(equal(result, uvec4(0u, 0u, 0u, 0u)))));
        }
        """,
    )
    program.set_uniform_uint(
        "uV", SIMD[DType.uint32, 4](0, 16777217, 2147483648, 4294967295)
    )
    program.set_uniform_uint(
        "uW", SIMD[DType.uint32, 4](1, 16777216, 2147483649, 4294967294)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_vector_notEqual() raises:
    """Check independent fixture uint_vector_notEqual."""
    # Expected UInt32 readback: 01000000010000000100000001000000
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        result = uvec4(notEqual(uV, uW));

            gl_FragColor = vec4(float(all(equal(result, uvec4(1u, 1u, 1u, 1u)))));
        }
        """,
    )
    program.set_uniform_uint(
        "uV", SIMD[DType.uint32, 4](0, 16777217, 2147483648, 4294967295)
    )
    program.set_uniform_uint(
        "uW", SIMD[DType.uint32, 4](1, 16777216, 2147483649, 4294967294)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_vector_equal_identity() raises:
    """Check independent fixture uint_vector_equal_identity."""
    # Expected UInt32 readback: 01000000010000000100000001000000
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        result = uvec4(equal(uV, uV));

            gl_FragColor = vec4(float(all(equal(result, uvec4(1u, 1u, 1u, 1u)))));
        }
        """,
    )
    program.set_uniform_uint(
        "uV", SIMD[DType.uint32, 4](0, 16777217, 2147483648, 4294967295)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_if_join_0() raises:
    """Check independent fixture uint_if_join_0."""
    # Expected UInt32 readback: 010000000000000101000080feffffff
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        uvec4 x; if (uFlag) { x = uV; } else { x = uW; } result = x;

            gl_FragColor = vec4(float(all(equal(result, uvec4(1u, 16777216u, 2147483649u, 4294967294u)))));
        }
        """,
    )
    program.set_uniform("uFlag", Float32(0))
    program.set_uniform_uint(
        "uV", SIMD[DType.uint32, 4](0, 16777217, 2147483648, 4294967295)
    )
    program.set_uniform_uint(
        "uW", SIMD[DType.uint32, 4](1, 16777216, 2147483649, 4294967294)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_ternary_select_0() raises:
    """Check independent fixture uint_ternary_select_0."""
    # Expected UInt32 readback: 010000000000000101000080feffffff
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        result = uFlag ? uV : uW;

            gl_FragColor = vec4(float(all(equal(result, uvec4(1u, 16777216u, 2147483649u, 4294967294u)))));
        }
        """,
    )
    program.set_uniform("uFlag", Float32(0))
    program.set_uniform_uint(
        "uV", SIMD[DType.uint32, 4](0, 16777217, 2147483648, 4294967295)
    )
    program.set_uniform_uint(
        "uW", SIMD[DType.uint32, 4](1, 16777216, 2147483649, 4294967294)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_if_join_1() raises:
    """Check independent fixture uint_if_join_1."""
    # Expected UInt32 readback: 000000000100000100000080ffffffff
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        uvec4 x; if (uFlag) { x = uV; } else { x = uW; } result = x;

            gl_FragColor = vec4(float(all(equal(result, uvec4(0u, 16777217u, 2147483648u, 4294967295u)))));
        }
        """,
    )
    program.set_uniform("uFlag", Float32(1))
    program.set_uniform_uint(
        "uV", SIMD[DType.uint32, 4](0, 16777217, 2147483648, 4294967295)
    )
    program.set_uniform_uint(
        "uW", SIMD[DType.uint32, 4](1, 16777216, 2147483649, 4294967294)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_ternary_select_1() raises:
    """Check independent fixture uint_ternary_select_1."""
    # Expected UInt32 readback: 000000000100000100000080ffffffff
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        result = uFlag ? uV : uW;

            gl_FragColor = vec4(float(all(equal(result, uvec4(0u, 16777217u, 2147483648u, 4294967295u)))));
        }
        """,
    )
    program.set_uniform("uFlag", Float32(1))
    program.set_uniform_uint(
        "uV", SIMD[DType.uint32, 4](0, 16777217, 2147483648, 4294967295)
    )
    program.set_uniform_uint(
        "uW", SIMD[DType.uint32, 4](1, 16777216, 2147483649, 4294967294)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_runtime_swizzle() raises:
    """Check independent fixture uint_runtime_swizzle."""
    # Expected UInt32 readback: 01000000000000010100000100000000
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        uvec4 x = uV; x.zw = uW.yx; result = x.wzyx;

            gl_FragColor = vec4(float(all(equal(result, uvec4(1u, 16777216u, 16777217u, 0u)))));
        }
        """,
    )
    program.set_uniform_uint(
        "uV", SIMD[DType.uint32, 4](0, 16777217, 2147483648, 4294967295)
    )
    program.set_uniform_uint(
        "uW", SIMD[DType.uint32, 4](1, 16777216, 2147483649, 4294967294)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_runtime_vector_index() raises:
    """Check independent fixture uint_runtime_vector_index."""
    # Expected UInt32 readback: 00000080ffffffff0000000101000000
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        result = uvec4(uV[uIndex], uV[3], uW[uIndex - 1], uW[0]);

            gl_FragColor = vec4(float(all(equal(result, uvec4(2147483648u, 4294967295u, 16777216u, 1u)))));
        }
        """,
    )
    program.set_uniform("uIndex", Float32(2))
    program.set_uniform_uint(
        "uV", SIMD[DType.uint32, 4](0, 16777217, 2147483648, 4294967295)
    )
    program.set_uniform_uint(
        "uW", SIMD[DType.uint32, 4](1, 16777216, 2147483649, 4294967294)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_runtime_array_read() raises:
    """Check independent fixture uint_runtime_array_read."""
    # Expected UInt32 readback: 0000008001000001ffffffff00000000
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        uint a[4] = uint[4](uV.x, uV.y, uV.z, uV.w); result = uvec4(a[uIndex], a[1], a[3], a[0]);

            gl_FragColor = vec4(float(all(equal(result, uvec4(2147483648u, 16777217u, 4294967295u, 0u)))));
        }
        """,
    )
    program.set_uniform("uIndex", Float32(2))
    program.set_uniform_uint(
        "uV", SIMD[DType.uint32, 4](0, 16777217, 2147483648, 4294967295)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_runtime_array_write() raises:
    """Check independent fixture uint_runtime_array_write."""
    # Expected UInt32 readback: 000000000100000101000001ffffffff
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        uint a[4] = uint[4](uV.x, uV.y, uV.z, uV.w); a[uIndex] = uB; result = uvec4(a[0], a[1], a[2], a[3]);

            gl_FragColor = vec4(float(all(equal(result, uvec4(0u, 16777217u, 16777217u, 4294967295u)))));
        }
        """,
    )
    program.set_uniform_uint("uB", UInt32(16777217))
    program.set_uniform("uIndex", Float32(2))
    program.set_uniform_uint(
        "uV", SIMD[DType.uint32, 4](0, 16777217, 2147483648, 4294967295)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_runtime_uvec_array() raises:
    """Check independent fixture uint_runtime_uvec_array."""
    # Expected UInt32 readback: 010000000000000101000080feffffff
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        uvec4 a[2] = uvec4[2](uV, uW); result = a[uIndex - 1];

            gl_FragColor = vec4(float(all(equal(result, uvec4(1u, 16777216u, 2147483649u, 4294967294u)))));
        }
        """,
    )
    program.set_uniform("uIndex", Float32(2))
    program.set_uniform_uint(
        "uV", SIMD[DType.uint32, 4](0, 16777217, 2147483648, 4294967295)
    )
    program.set_uniform_uint(
        "uW", SIMD[DType.uint32, 4](1, 16777216, 2147483649, 4294967294)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_function_return() raises:
    """Check independent fixture uint_function_return."""
    # Expected UInt32 readback: 000000000100000100000080ffffffff
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;
        uvec4 pick(uvec4 a, uvec4 b, bool flag) { if (flag) { return a; } return b; }

        void main() {
            uvec4 result = uvec4(0u);
        result = pick(uV, uW, uFlag);

            gl_FragColor = vec4(float(all(equal(result, uvec4(0u, 16777217u, 2147483648u, 4294967295u)))));
        }
        """,
    )
    program.set_uniform("uFlag", Float32(1))
    program.set_uniform_uint(
        "uV", SIMD[DType.uint32, 4](0, 16777217, 2147483648, 4294967295)
    )
    program.set_uniform_uint(
        "uW", SIMD[DType.uint32, 4](1, 16777216, 2147483649, 4294967294)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_function_inout_out() raises:
    """Check independent fixture uint_function_inout_out."""
    # Expected UInt32 readback: 00000001fefffffeffffffff01000001
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;
        void adjust(inout uint a, uint step, out uint b) { b = a - step; a += step; }

        void main() {
            uvec4 result = uvec4(0u);
        uint a = uA; uint b = 0u; adjust(a, uB, b); result = uvec4(a, b, uA, uB);

            gl_FragColor = vec4(float(all(equal(result, uvec4(16777216u, 4278190078u, 4294967295u, 16777217u)))));
        }
        """,
    )
    program.set_uniform_uint("uA", UInt32(4294967295))
    program.set_uniform_uint("uB", UInt32(16777217))
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_struct_field_join() raises:
    """Check independent fixture uint_struct_field_join."""
    # Expected UInt32 readback: ffffffff0100000100000080ffffffff
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;
        struct Pair { uint a; uvec4 b; };

        void main() {
            uvec4 result = uvec4(0u);
        Pair p = Pair(uA, uV); result = uvec4(p.a, p.b.yzw);

            gl_FragColor = vec4(float(all(equal(result, uvec4(4294967295u, 16777217u, 2147483648u, 4294967295u)))));
        }
        """,
    )
    program.set_uniform_uint("uA", UInt32(4294967295))
    program.set_uniform_uint(
        "uV", SIMD[DType.uint32, 4](0, 16777217, 2147483648, 4294967295)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_arithmetic_compound() raises:
    """Check independent fixture uint_arithmetic_compound."""
    # Expected UInt32 readback: fdffff7ffeffff7f0000000000000000
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        uint a = uA; a += 2u; a -= 3u; a *= 3u; a /= 2u; uint before = a; ++a; result = uvec4(before, a, 0u, 0u);

            gl_FragColor = vec4(float(all(equal(result, uvec4(2147483645u, 2147483646u, 0u, 0u)))));
        }
        """,
    )
    program.set_uniform_uint("uA", UInt32(4294967295))
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_bitwise_compound() raises:
    """Check independent fixture uint_bitwise_compound."""
    # Expected UInt32 readback: 017f0000ffffffff0100000100000000
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        uint a = uA; a &= uB; a |= 0x80000000u; a ^= 1u; a >>= 1; a <<= 1; a %= 65537u; result = uvec4(a, uA, uB, 0u);

            gl_FragColor = vec4(float(all(equal(result, uvec4(32513u, 4294967295u, 16777217u, 0u)))));
        }
        """,
    )
    program.set_uniform_uint("uA", UInt32(4294967295))
    program.set_uniform_uint("uB", UInt32(16777217))
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_fragment_runtime_path() raises:
    """Check independent fixture uint_fragment_runtime_path."""
    # Expected UInt32 readback: 000000000100000100000080ffffffff
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        uint pixel = uint(gl_FragCoord.x); result = uV + uvec4(pixel);

            gl_FragColor = vec4(float(all(equal(result, uvec4(0u, 16777217u, 2147483648u, 4294967295u)))));
        }
        """,
    )
    program.set_uniform_uint(
        "uV", SIMD[DType.uint32, 4](0, 16777217, 2147483648, 4294967295)
    )
    assert_equal(fixture_run(program)[0], Float32(1))


def test_reference_uint_uniform_uvec2() raises:
    """Check independent fixture uint_uniform_uvec2."""
    # Expected UInt32 readback: 01000001ffffffffffffffff01000001
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uvec2 uPair;

        void main() {
            uvec4 result = uvec4(0u);
        result = uvec4(uPair, uPair.yx);

            gl_FragColor = vec4(float(all(equal(result, uvec4(16777217u, 4294967295u, 4294967295u, 16777217u)))));
        }
        """,
    )
    program.set_uniform_uint(
        "uPair", SIMD[DType.uint32, 2](16777217, 4294967295)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_uniform_uvec3() raises:
    """Check independent fixture uint_uniform_uvec3."""
    # Expected UInt32 readback: 0100000101000080ffffffff01000080
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uvec3 uTriple;

        void main() {
            uvec4 result = uvec4(0u);
        result = uvec4(uTriple, uTriple[1]);

            gl_FragColor = vec4(float(all(equal(result, uvec4(16777217u, 2147483649u, 4294967295u, 2147483649u)))));
        }
        """,
    )
    program.set_uniform_uint(
        "uTriple", UInt32(16777217), UInt32(2147483649), UInt32(4294967295)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_const_minmaxclamp() raises:
    """Check independent fixture uint_const_minmaxclamp."""
    # Expected UInt32 readback: 01000001000000800100008000000080
    var program = compile_shader_material(
        VERTEX,
        """
        void main() {
            uvec4 result = uvec4(0u);
        result = uvec4(min(4294967295u, 16777217u), max(2147483647u, 2147483648u), clamp(4294967295u, 16777216u, 2147483649u), clamp(16777217u, 2147483648u, 4294967295u));

            gl_FragColor = vec4(float(all(equal(result, uvec4(16777217u, 2147483648u, 2147483649u, 2147483648u)))));
        }
        """,
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_const_div_rem_shift() raises:
    """Check independent fixture uint_const_div_rem_shift."""
    # Expected UInt32 readback: ff00000000ffff000100000000000080
    var program = compile_shader_material(
        VERTEX,
        """
        void main() {
            uvec4 result = uvec4(0u);
        result = uvec4(4294967295u / 16777217u, 4294967295u % 16777217u, 4294967295u >> 31u, 16777217u << 31u);

            gl_FragColor = vec4(float(all(equal(result, uvec4(255u, 16776960u, 1u, 2147483648u)))));
        }
        """,
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_int_uint_const_roundtrip() raises:
    """Check independent fixture uint_int_uint_const_roundtrip."""
    # Expected UInt32 readback: 01000080ffffffff00000080ffffff7f
    var program = compile_shader_material(
        VERTEX,
        """
        void main() {
            uvec4 result = uvec4(0u);
        result = uvec4(uint(int(0x80000001u)), uint(int(0xffffffffu)), uint(int(0x80000000u)), uint(int(0x7fffffffu)));

            gl_FragColor = vec4(float(all(equal(result, uvec4(2147483649u, 4294967295u, 2147483648u, 2147483647u)))));
        }
        """,
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_ivec_variable_roundtrip() raises:
    """Check independent fixture uint_ivec_variable_roundtrip."""
    # Expected UInt32 readback: 01000080ffffffff00000080ffffff7f
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        ivec4 a = ivec4(uV); ivec4 b = a; result = uvec4(b);

            gl_FragColor = vec4(float(all(equal(result, uvec4(2147483649u, 4294967295u, 2147483648u, 2147483647u)))));
        }
        """,
    )
    program.set_uniform_uint(
        "uV",
        SIMD[DType.uint32, 4](2147483649, 4294967295, 2147483648, 2147483647),
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_ivec_swizzle_roundtrip() raises:
    """Check independent fixture uint_ivec_swizzle_roundtrip."""
    # Expected UInt32 readback: ffffff7f0000008001000080ffffffff
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        ivec4 a = ivec4(uV); ivec2 b = a.wz; ivec2 c = a.xy; result = uvec4(ivec4(b,c));

            gl_FragColor = vec4(float(all(equal(result, uvec4(2147483647u, 2147483648u, 2147483649u, 4294967295u)))));
        }
        """,
    )
    program.set_uniform_uint(
        "uV",
        SIMD[DType.uint32, 4](2147483649, 4294967295, 2147483648, 2147483647),
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_int_scalar_variable_roundtrip() raises:
    """Check independent fixture uint_int_scalar_variable_roundtrip."""
    # Expected UInt32 readback: 01000080ffffffff00000080ffffff7f
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        int a = int(uV.x); int b = a; result = uvec4(uint(b), uint(int(uV.y)), uint(int(uV.z)), uint(int(uV.w)));

            gl_FragColor = vec4(float(all(equal(result, uvec4(2147483649u, 4294967295u, 2147483648u, 2147483647u)))));
        }
        """,
    )
    program.set_uniform_uint(
        "uV",
        SIMD[DType.uint32, 4](2147483649, 4294967295, 2147483648, 2147483647),
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_int_function_roundtrip() raises:
    """Check independent fixture uint_int_function_roundtrip."""
    # Expected UInt32 readback: 01000080ffffffff00000080ffffff7f
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;
        int signed_pass(int x) { int y = x; return y; }

        void main() {
            uvec4 result = uvec4(0u);
        result = uvec4(uint(signed_pass(int(uV.x))), uint(signed_pass(int(uV.y))), uint(signed_pass(int(uV.z))), uint(signed_pass(int(uV.w))));

            gl_FragColor = vec4(float(all(equal(result, uvec4(2147483649u, 4294967295u, 2147483648u, 2147483647u)))));
        }
        """,
    )
    program.set_uniform_uint(
        "uV",
        SIMD[DType.uint32, 4](2147483649, 4294967295, 2147483648, 2147483647),
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_ivec_function_roundtrip() raises:
    """Check independent fixture uint_ivec_function_roundtrip."""
    # Expected UInt32 readback: 01000080ffffffff00000080ffffff7f
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;
        ivec4 signed_pass(ivec4 x) { ivec4 y = x; return y; }

        void main() {
            uvec4 result = uvec4(0u);
        result = uvec4(signed_pass(ivec4(uV)));

            gl_FragColor = vec4(float(all(equal(result, uvec4(2147483649u, 4294967295u, 2147483648u, 2147483647u)))));
        }
        """,
    )
    program.set_uniform_uint(
        "uV",
        SIMD[DType.uint32, 4](2147483649, 4294967295, 2147483648, 2147483647),
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_ivec_inout_roundtrip() raises:
    """Check independent fixture uint_ivec_inout_roundtrip."""
    # Expected UInt32 readback: ffffff7f00000080ffffffff01000080
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;
        void signed_pass(inout ivec4 x) { x = x.wzyx; }

        void main() {
            uvec4 result = uvec4(0u);
        ivec4 a = ivec4(uV); signed_pass(a); result = uvec4(a);

            gl_FragColor = vec4(float(all(equal(result, uvec4(2147483647u, 2147483648u, 4294967295u, 2147483649u)))));
        }
        """,
    )
    program.set_uniform_uint(
        "uV",
        SIMD[DType.uint32, 4](2147483649, 4294967295, 2147483648, 2147483647),
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_int_signed_comparison() raises:
    """Check independent fixture uint_int_signed_comparison."""
    # Expected UInt32 readback: 01000000010000000100000000000000
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        ivec4 a = ivec4(uV); result = uvec4(lessThan(a, ivec4(0)));

            gl_FragColor = vec4(float(all(equal(result, uvec4(1u, 1u, 1u, 0u)))));
        }
        """,
    )
    program.set_uniform_uint(
        "uV",
        SIMD[DType.uint32, 4](2147483649, 4294967295, 2147483648, 2147483647),
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_bool_high_bit() raises:
    """Check independent fixture uint_bool_high_bit."""
    # Expected UInt32 readback: 01000000010000000100000001000000
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        result = uvec4(uint(bool(uV.x)), uint(bool(uV.y)), uint(bool(uV.z)), uint(bool(uV.w)));

            gl_FragColor = vec4(float(all(equal(result, uvec4(1u, 1u, 1u, 1u)))));
        }
        """,
    )
    program.set_uniform_uint(
        "uV",
        SIMD[DType.uint32, 4](2147483649, 4294967295, 2147483648, 2147483647),
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_bvec_high_bit() raises:
    """Check independent fixture uint_bvec_high_bit."""
    # Expected UInt32 readback: 01000000010000000100000001000000
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        result = uvec4(bvec4(uV));

            gl_FragColor = vec4(float(all(equal(result, uvec4(1u, 1u, 1u, 1u)))));
        }
        """,
    )
    program.set_uniform_uint(
        "uV",
        SIMD[DType.uint32, 4](2147483649, 4294967295, 2147483648, 2147483647),
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_payload_0_constant() raises:
    """Check independent fixture uint_payload_0_constant."""
    # Expected UInt32 readback: 0000000001000000000000800000807f
    var program = compile_shader_material(
        VERTEX,
        """
        void main() {
            uvec4 result = uvec4(0u);
        result = uvec4(0x00000000u, 0x00000001u, 0x80000000u, 0x7f800000u);

            gl_FragColor = vec4(float(all(equal(result, uvec4(0u, 1u, 2147483648u, 2139095040u)))));
        }
        """,
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_payload_0_uniform() raises:
    """Check independent fixture uint_payload_0_uniform."""
    # Expected UInt32 readback: 0000000001000000000000800000807f
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        result = uV;

            gl_FragColor = vec4(float(all(equal(result, uvec4(0u, 1u, 2147483648u, 2139095040u)))));
        }
        """,
    )
    program.set_uniform_uint(
        "uV", SIMD[DType.uint32, 4](0, 1, 2147483648, 2139095040)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_payload_0_variable() raises:
    """Check independent fixture uint_payload_0_variable."""
    # Expected UInt32 readback: 0000000001000000000000800000807f
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        uvec4 a = uV; uvec4 b = a; result = b;

            gl_FragColor = vec4(float(all(equal(result, uvec4(0u, 1u, 2147483648u, 2139095040u)))));
        }
        """,
    )
    program.set_uniform_uint(
        "uV", SIMD[DType.uint32, 4](0, 1, 2147483648, 2139095040)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_payload_0_swizzle() raises:
    """Check independent fixture uint_payload_0_swizzle."""
    # Expected UInt32 readback: 0000807f000000800000000001000000
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        uvec2 a = uV.wz; uvec2 b = uV.xy; result = uvec4(a,b);

            gl_FragColor = vec4(float(all(equal(result, uvec4(2139095040u, 2147483648u, 0u, 1u)))));
        }
        """,
    )
    program.set_uniform_uint(
        "uV", SIMD[DType.uint32, 4](0, 1, 2147483648, 2139095040)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_payload_0_function() raises:
    """Check independent fixture uint_payload_0_function."""
    # Expected UInt32 readback: 0000000001000000000000800000807f
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;
        uvec4 pass_value(uvec4 x) { uvec4 local = x; return local; }

        void main() {
            uvec4 result = uvec4(0u);
        result = pass_value(uV);

            gl_FragColor = vec4(float(all(equal(result, uvec4(0u, 1u, 2147483648u, 2139095040u)))));
        }
        """,
    )
    program.set_uniform_uint(
        "uV", SIMD[DType.uint32, 4](0, 1, 2147483648, 2139095040)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_payload_0_inout() raises:
    """Check independent fixture uint_payload_0_inout."""
    # Expected UInt32 readback: 0100000002000000010000800100807f
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;
        void pass_value(inout uvec4 x) { x += uvec4(1u); }

        void main() {
            uvec4 result = uvec4(0u);
        uvec4 a = uV; pass_value(a); result = a;

            gl_FragColor = vec4(float(all(equal(result, uvec4(1u, 2u, 2147483649u, 2139095041u)))));
        }
        """,
    )
    program.set_uniform_uint(
        "uV", SIMD[DType.uint32, 4](0, 1, 2147483648, 2139095040)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_payload_0_array() raises:
    """Check independent fixture uint_payload_0_array."""
    # Expected UInt32 readback: 0000000001000000000000800000807f
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        uint a[4] = uint[4](uV.x,uV.y,uV.z,uV.w); result = uvec4(a[0],a[1],a[uIndex],a[3]);

            gl_FragColor = vec4(float(all(equal(result, uvec4(0u, 1u, 2147483648u, 2139095040u)))));
        }
        """,
    )
    program.set_uniform("uIndex", Float32(2))
    program.set_uniform_uint(
        "uV", SIMD[DType.uint32, 4](0, 1, 2147483648, 2139095040)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_payload_0_bool() raises:
    """Check independent fixture uint_payload_0_bool."""
    # Expected UInt32 readback: 00000000010000000100000001000000
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        result = uvec4(bvec4(uV));

            gl_FragColor = vec4(float(all(equal(result, uvec4(0u, 1u, 1u, 1u)))));
        }
        """,
    )
    program.set_uniform_uint(
        "uV", SIMD[DType.uint32, 4](0, 1, 2147483648, 2139095040)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_payload_0_minimum() raises:
    """Check independent fixture uint_payload_0_minimum."""
    # Expected UInt32 readback: 0000000001000000000000800000807f
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        result = min(uV, 0x80000000u);

            gl_FragColor = vec4(float(all(equal(result, uvec4(0u, 1u, 2147483648u, 2139095040u)))));
        }
        """,
    )
    program.set_uniform_uint(
        "uV", SIMD[DType.uint32, 4](0, 1, 2147483648, 2139095040)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_payload_0_ivec_roundtrip() raises:
    """Check independent fixture uint_payload_0_ivec_roundtrip."""
    # Expected UInt32 readback: 0000000001000000000000800000807f
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        ivec4 a = ivec4(uV); result = uvec4(a);

            gl_FragColor = vec4(float(all(equal(result, uvec4(0u, 1u, 2147483648u, 2139095040u)))));
        }
        """,
    )
    program.set_uniform_uint(
        "uV", SIMD[DType.uint32, 4](0, 1, 2147483648, 2139095040)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_payload_0_select_0() raises:
    """Check independent fixture uint_payload_0_select_0."""
    # Expected UInt32 readback: 0000807f000000800100000000000000
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        result = uFlag ? uV : uV.wzyx;

            gl_FragColor = vec4(float(all(equal(result, uvec4(2139095040u, 2147483648u, 1u, 0u)))));
        }
        """,
    )
    program.set_uniform("uFlag", Float32(0))
    program.set_uniform_uint(
        "uV", SIMD[DType.uint32, 4](0, 1, 2147483648, 2139095040)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_payload_0_select_1() raises:
    """Check independent fixture uint_payload_0_select_1."""
    # Expected UInt32 readback: 0000000001000000000000800000807f
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        result = uFlag ? uV : uV.wzyx;

            gl_FragColor = vec4(float(all(equal(result, uvec4(0u, 1u, 2147483648u, 2139095040u)))));
        }
        """,
    )
    program.set_uniform("uFlag", Float32(1))
    program.set_uniform_uint(
        "uV", SIMD[DType.uint32, 4](0, 1, 2147483648, 2139095040)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_payload_1_constant() raises:
    """Check independent fixture uint_payload_1_constant."""
    # Expected UInt32 readback: 0100c07f000080ffffffffffffff7f00
    var program = compile_shader_material(
        VERTEX,
        """
        void main() {
            uvec4 result = uvec4(0u);
        result = uvec4(0x7fc00001u, 0xff800000u, 0xffffffffu, 0x007fffffu);

            gl_FragColor = vec4(float(all(equal(result, uvec4(2143289345u, 4286578688u, 4294967295u, 8388607u)))));
        }
        """,
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_payload_1_uniform() raises:
    """Check independent fixture uint_payload_1_uniform."""
    # Expected UInt32 readback: 0100c07f000080ffffffffffffff7f00
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        result = uV;

            gl_FragColor = vec4(float(all(equal(result, uvec4(2143289345u, 4286578688u, 4294967295u, 8388607u)))));
        }
        """,
    )
    program.set_uniform_uint(
        "uV", SIMD[DType.uint32, 4](2143289345, 4286578688, 4294967295, 8388607)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_payload_1_variable() raises:
    """Check independent fixture uint_payload_1_variable."""
    # Expected UInt32 readback: 0100c07f000080ffffffffffffff7f00
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        uvec4 a = uV; uvec4 b = a; result = b;

            gl_FragColor = vec4(float(all(equal(result, uvec4(2143289345u, 4286578688u, 4294967295u, 8388607u)))));
        }
        """,
    )
    program.set_uniform_uint(
        "uV", SIMD[DType.uint32, 4](2143289345, 4286578688, 4294967295, 8388607)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_payload_1_swizzle() raises:
    """Check independent fixture uint_payload_1_swizzle."""
    # Expected UInt32 readback: ffff7f00ffffffff0100c07f000080ff
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        uvec2 a = uV.wz; uvec2 b = uV.xy; result = uvec4(a,b);

            gl_FragColor = vec4(float(all(equal(result, uvec4(8388607u, 4294967295u, 2143289345u, 4286578688u)))));
        }
        """,
    )
    program.set_uniform_uint(
        "uV", SIMD[DType.uint32, 4](2143289345, 4286578688, 4294967295, 8388607)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_payload_1_function() raises:
    """Check independent fixture uint_payload_1_function."""
    # Expected UInt32 readback: 0100c07f000080ffffffffffffff7f00
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;
        uvec4 pass_value(uvec4 x) { uvec4 local = x; return local; }

        void main() {
            uvec4 result = uvec4(0u);
        result = pass_value(uV);

            gl_FragColor = vec4(float(all(equal(result, uvec4(2143289345u, 4286578688u, 4294967295u, 8388607u)))));
        }
        """,
    )
    program.set_uniform_uint(
        "uV", SIMD[DType.uint32, 4](2143289345, 4286578688, 4294967295, 8388607)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_payload_1_inout() raises:
    """Check independent fixture uint_payload_1_inout."""
    # Expected UInt32 readback: 0200c07f010080ff0000000000008000
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;
        void pass_value(inout uvec4 x) { x += uvec4(1u); }

        void main() {
            uvec4 result = uvec4(0u);
        uvec4 a = uV; pass_value(a); result = a;

            gl_FragColor = vec4(float(all(equal(result, uvec4(2143289346u, 4286578689u, 0u, 8388608u)))));
        }
        """,
    )
    program.set_uniform_uint(
        "uV", SIMD[DType.uint32, 4](2143289345, 4286578688, 4294967295, 8388607)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_payload_1_array() raises:
    """Check independent fixture uint_payload_1_array."""
    # Expected UInt32 readback: 0100c07f000080ffffffffffffff7f00
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        uint a[4] = uint[4](uV.x,uV.y,uV.z,uV.w); result = uvec4(a[0],a[1],a[uIndex],a[3]);

            gl_FragColor = vec4(float(all(equal(result, uvec4(2143289345u, 4286578688u, 4294967295u, 8388607u)))));
        }
        """,
    )
    program.set_uniform("uIndex", Float32(2))
    program.set_uniform_uint(
        "uV", SIMD[DType.uint32, 4](2143289345, 4286578688, 4294967295, 8388607)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_payload_1_bool() raises:
    """Check independent fixture uint_payload_1_bool."""
    # Expected UInt32 readback: 01000000010000000100000001000000
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        result = uvec4(bvec4(uV));

            gl_FragColor = vec4(float(all(equal(result, uvec4(1u, 1u, 1u, 1u)))));
        }
        """,
    )
    program.set_uniform_uint(
        "uV", SIMD[DType.uint32, 4](2143289345, 4286578688, 4294967295, 8388607)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_payload_1_minimum() raises:
    """Check independent fixture uint_payload_1_minimum."""
    # Expected UInt32 readback: 0100c07f0000008000000080ffff7f00
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        result = min(uV, 0x80000000u);

            gl_FragColor = vec4(float(all(equal(result, uvec4(2143289345u, 2147483648u, 2147483648u, 8388607u)))));
        }
        """,
    )
    program.set_uniform_uint(
        "uV", SIMD[DType.uint32, 4](2143289345, 4286578688, 4294967295, 8388607)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_payload_1_ivec_roundtrip() raises:
    """Check independent fixture uint_payload_1_ivec_roundtrip."""
    # Expected UInt32 readback: 0100c07f000080ffffffffffffff7f00
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        ivec4 a = ivec4(uV); result = uvec4(a);

            gl_FragColor = vec4(float(all(equal(result, uvec4(2143289345u, 4286578688u, 4294967295u, 8388607u)))));
        }
        """,
    )
    program.set_uniform_uint(
        "uV", SIMD[DType.uint32, 4](2143289345, 4286578688, 4294967295, 8388607)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_payload_1_select_0() raises:
    """Check independent fixture uint_payload_1_select_0."""
    # Expected UInt32 readback: ffff7f00ffffffff000080ff0100c07f
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        result = uFlag ? uV : uV.wzyx;

            gl_FragColor = vec4(float(all(equal(result, uvec4(8388607u, 4294967295u, 4286578688u, 2143289345u)))));
        }
        """,
    )
    program.set_uniform("uFlag", Float32(0))
    program.set_uniform_uint(
        "uV", SIMD[DType.uint32, 4](2143289345, 4286578688, 4294967295, 8388607)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_uint_payload_1_select_1() raises:
    """Check independent fixture uint_payload_1_select_1."""
    # Expected UInt32 readback: 0100c07f000080ffffffffffffff7f00
    var program = compile_shader_material(
        VERTEX,
        """
        uniform uint uA; uniform uint uB; uniform uvec4 uV; uniform uvec4 uW; uniform bool uFlag; uniform int uIndex;

        void main() {
            uvec4 result = uvec4(0u);
        result = uFlag ? uV : uV.wzyx;

            gl_FragColor = vec4(float(all(equal(result, uvec4(2143289345u, 4286578688u, 4294967295u, 8388607u)))));
        }
        """,
    )
    program.set_uniform("uFlag", Float32(1))
    program.set_uniform_uint(
        "uV", SIMD[DType.uint32, 4](2143289345, 4286578688, 4294967295, 8388607)
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_while_finite_63() raises:
    """Check independent fixture while_finite_63."""
    # Expected UInt32 readback: 3f000000e00700000000000001000000
    var program = compile_shader_material(
        VERTEX,
        """
        void main() {
            uvec4 result = uvec4(0u);
        uint i = 0u; uint total = 0u;
        while (i < 63u) { i += 1u; total += i; }
        result = uvec4(i, total, 0u, 1u);

            gl_FragColor = vec4(float(all(equal(result, uvec4(63u, 2016u, 0u, 1u)))));
        }
        """,
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_while_condition_effects_63() raises:
    """Check independent fixture while_condition_effects_63."""
    # Expected UInt32 readback: 3f000000e00700004000000001000000
    var program = compile_shader_material(
        VERTEX,
        """
        bool condition(uint i, inout uint calls) { calls += 1u; return i < 63u; }

        void main() {
            uvec4 result = uvec4(0u);
        uint i = 0u; uint total = 0u; uint calls = 0u;
        while (condition(i, calls)) { i += 1u; total += i; }
        result = uvec4(i, total, calls, 1u);

            gl_FragColor = vec4(float(all(equal(result, uvec4(63u, 2016u, 64u, 1u)))));
        }
        """,
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_do_finite_63() raises:
    """Check independent fixture do_finite_63."""
    # Expected UInt32 readback: 3f000000e00700000000000001000000
    var program = compile_shader_material(
        VERTEX,
        """
        void main() {
            uvec4 result = uvec4(0u);
        uint i = 0u; uint total = 0u;
        do { i += 1u; total += i; } while (i < 63u);
        result = uvec4(i, total, 0u, 1u);

            gl_FragColor = vec4(float(all(equal(result, uvec4(63u, 2016u, 0u, 1u)))));
        }
        """,
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_do_condition_effects_63() raises:
    """Check independent fixture do_condition_effects_63."""
    # Expected UInt32 readback: 3f000000e00700003f00000001000000
    var program = compile_shader_material(
        VERTEX,
        """
        bool condition(uint i, inout uint calls) { calls += 1u; return i < 63u; }

        void main() {
            uvec4 result = uvec4(0u);
        uint i = 0u; uint total = 0u; uint calls = 0u;
        do { i += 1u; total += i; } while (condition(i, calls));
        result = uvec4(i, total, calls, 1u);

            gl_FragColor = vec4(float(all(equal(result, uvec4(63u, 2016u, 63u, 1u)))));
        }
        """,
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_while_finite_64() raises:
    """Check independent fixture while_finite_64."""
    # Expected UInt32 readback: 40000000200800000000000001000000
    var program = compile_shader_material(
        VERTEX,
        """
        void main() {
            uvec4 result = uvec4(0u);
        uint i = 0u; uint total = 0u;
        while (i < 64u) { i += 1u; total += i; }
        result = uvec4(i, total, 0u, 1u);

            gl_FragColor = vec4(float(all(equal(result, uvec4(64u, 2080u, 0u, 1u)))));
        }
        """,
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_while_condition_effects_64() raises:
    """Check independent fixture while_condition_effects_64."""
    # Expected UInt32 readback: 40000000200800004100000001000000
    var program = compile_shader_material(
        VERTEX,
        """
        bool condition(uint i, inout uint calls) { calls += 1u; return i < 64u; }

        void main() {
            uvec4 result = uvec4(0u);
        uint i = 0u; uint total = 0u; uint calls = 0u;
        while (condition(i, calls)) { i += 1u; total += i; }
        result = uvec4(i, total, calls, 1u);

            gl_FragColor = vec4(float(all(equal(result, uvec4(64u, 2080u, 65u, 1u)))));
        }
        """,
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_do_finite_64() raises:
    """Check independent fixture do_finite_64."""
    # Expected UInt32 readback: 40000000200800000000000001000000
    var program = compile_shader_material(
        VERTEX,
        """
        void main() {
            uvec4 result = uvec4(0u);
        uint i = 0u; uint total = 0u;
        do { i += 1u; total += i; } while (i < 64u);
        result = uvec4(i, total, 0u, 1u);

            gl_FragColor = vec4(float(all(equal(result, uvec4(64u, 2080u, 0u, 1u)))));
        }
        """,
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_do_condition_effects_64() raises:
    """Check independent fixture do_condition_effects_64."""
    # Expected UInt32 readback: 40000000200800004000000001000000
    var program = compile_shader_material(
        VERTEX,
        """
        bool condition(uint i, inout uint calls) { calls += 1u; return i < 64u; }

        void main() {
            uvec4 result = uvec4(0u);
        uint i = 0u; uint total = 0u; uint calls = 0u;
        do { i += 1u; total += i; } while (condition(i, calls));
        result = uvec4(i, total, calls, 1u);

            gl_FragColor = vec4(float(all(equal(result, uvec4(64u, 2080u, 64u, 1u)))));
        }
        """,
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_while_finite_65() raises:
    """Check independent fixture while_finite_65."""
    # Expected UInt32 readback: 41000000610800000000000001000000
    var program = compile_shader_material(
        VERTEX,
        """
        void main() {
            uvec4 result = uvec4(0u);
        uint i = 0u; uint total = 0u;
        while (i < 65u) { i += 1u; total += i; }
        result = uvec4(i, total, 0u, 1u);

            gl_FragColor = vec4(float(all(equal(result, uvec4(65u, 2145u, 0u, 1u)))));
        }
        """,
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_while_condition_effects_65() raises:
    """Check independent fixture while_condition_effects_65."""
    # Expected UInt32 readback: 41000000610800004200000001000000
    var program = compile_shader_material(
        VERTEX,
        """
        bool condition(uint i, inout uint calls) { calls += 1u; return i < 65u; }

        void main() {
            uvec4 result = uvec4(0u);
        uint i = 0u; uint total = 0u; uint calls = 0u;
        while (condition(i, calls)) { i += 1u; total += i; }
        result = uvec4(i, total, calls, 1u);

            gl_FragColor = vec4(float(all(equal(result, uvec4(65u, 2145u, 66u, 1u)))));
        }
        """,
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_do_finite_65() raises:
    """Check independent fixture do_finite_65."""
    # Expected UInt32 readback: 41000000610800000000000001000000
    var program = compile_shader_material(
        VERTEX,
        """
        void main() {
            uvec4 result = uvec4(0u);
        uint i = 0u; uint total = 0u;
        do { i += 1u; total += i; } while (i < 65u);
        result = uvec4(i, total, 0u, 1u);

            gl_FragColor = vec4(float(all(equal(result, uvec4(65u, 2145u, 0u, 1u)))));
        }
        """,
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_do_condition_effects_65() raises:
    """Check independent fixture do_condition_effects_65."""
    # Expected UInt32 readback: 41000000610800004100000001000000
    var program = compile_shader_material(
        VERTEX,
        """
        bool condition(uint i, inout uint calls) { calls += 1u; return i < 65u; }

        void main() {
            uvec4 result = uvec4(0u);
        uint i = 0u; uint total = 0u; uint calls = 0u;
        do { i += 1u; total += i; } while (condition(i, calls));
        result = uvec4(i, total, calls, 1u);

            gl_FragColor = vec4(float(all(equal(result, uvec4(65u, 2145u, 65u, 1u)))));
        }
        """,
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_while_finite_128() raises:
    """Check independent fixture while_finite_128."""
    # Expected UInt32 readback: 80000000402000000000000001000000
    var program = compile_shader_material(
        VERTEX,
        """
        void main() {
            uvec4 result = uvec4(0u);
        uint i = 0u; uint total = 0u;
        while (i < 128u) { i += 1u; total += i; }
        result = uvec4(i, total, 0u, 1u);

            gl_FragColor = vec4(float(all(equal(result, uvec4(128u, 8256u, 0u, 1u)))));
        }
        """,
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_while_condition_effects_128() raises:
    """Check independent fixture while_condition_effects_128."""
    # Expected UInt32 readback: 80000000402000008100000001000000
    var program = compile_shader_material(
        VERTEX,
        """
        bool condition(uint i, inout uint calls) { calls += 1u; return i < 128u; }

        void main() {
            uvec4 result = uvec4(0u);
        uint i = 0u; uint total = 0u; uint calls = 0u;
        while (condition(i, calls)) { i += 1u; total += i; }
        result = uvec4(i, total, calls, 1u);

            gl_FragColor = vec4(float(all(equal(result, uvec4(128u, 8256u, 129u, 1u)))));
        }
        """,
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_do_finite_128() raises:
    """Check independent fixture do_finite_128."""
    # Expected UInt32 readback: 80000000402000000000000001000000
    var program = compile_shader_material(
        VERTEX,
        """
        void main() {
            uvec4 result = uvec4(0u);
        uint i = 0u; uint total = 0u;
        do { i += 1u; total += i; } while (i < 128u);
        result = uvec4(i, total, 0u, 1u);

            gl_FragColor = vec4(float(all(equal(result, uvec4(128u, 8256u, 0u, 1u)))));
        }
        """,
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_do_condition_effects_128() raises:
    """Check independent fixture do_condition_effects_128."""
    # Expected UInt32 readback: 80000000402000008000000001000000
    var program = compile_shader_material(
        VERTEX,
        """
        bool condition(uint i, inout uint calls) { calls += 1u; return i < 128u; }

        void main() {
            uvec4 result = uvec4(0u);
        uint i = 0u; uint total = 0u; uint calls = 0u;
        do { i += 1u; total += i; } while (condition(i, calls));
        result = uvec4(i, total, calls, 1u);

            gl_FragColor = vec4(float(all(equal(result, uvec4(128u, 8256u, 128u, 1u)))));
        }
        """,
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_while_finite_256() raises:
    """Check independent fixture while_finite_256."""
    # Expected UInt32 readback: 00010000808000000000000001000000
    var program = compile_shader_material(
        VERTEX,
        """
        void main() {
            uvec4 result = uvec4(0u);
        uint i = 0u; uint total = 0u;
        while (i < 256u) { i += 1u; total += i; }
        result = uvec4(i, total, 0u, 1u);

            gl_FragColor = vec4(float(all(equal(result, uvec4(256u, 32896u, 0u, 1u)))));
        }
        """,
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_while_condition_effects_256() raises:
    """Check independent fixture while_condition_effects_256."""
    # Expected UInt32 readback: 00010000808000000101000001000000
    var program = compile_shader_material(
        VERTEX,
        """
        bool condition(uint i, inout uint calls) { calls += 1u; return i < 256u; }

        void main() {
            uvec4 result = uvec4(0u);
        uint i = 0u; uint total = 0u; uint calls = 0u;
        while (condition(i, calls)) { i += 1u; total += i; }
        result = uvec4(i, total, calls, 1u);

            gl_FragColor = vec4(float(all(equal(result, uvec4(256u, 32896u, 257u, 1u)))));
        }
        """,
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_do_finite_256() raises:
    """Check independent fixture do_finite_256."""
    # Expected UInt32 readback: 00010000808000000000000001000000
    var program = compile_shader_material(
        VERTEX,
        """
        void main() {
            uvec4 result = uvec4(0u);
        uint i = 0u; uint total = 0u;
        do { i += 1u; total += i; } while (i < 256u);
        result = uvec4(i, total, 0u, 1u);

            gl_FragColor = vec4(float(all(equal(result, uvec4(256u, 32896u, 0u, 1u)))));
        }
        """,
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_do_condition_effects_256() raises:
    """Check independent fixture do_condition_effects_256."""
    # Expected UInt32 readback: 00010000808000000001000001000000
    var program = compile_shader_material(
        VERTEX,
        """
        bool condition(uint i, inout uint calls) { calls += 1u; return i < 256u; }

        void main() {
            uvec4 result = uvec4(0u);
        uint i = 0u; uint total = 0u; uint calls = 0u;
        do { i += 1u; total += i; } while (condition(i, calls));
        result = uvec4(i, total, calls, 1u);

            gl_FragColor = vec4(float(all(equal(result, uvec4(256u, 32896u, 256u, 1u)))));
        }
        """,
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_while_break_continue() raises:
    """Check independent fixture while_break_continue."""
    # Expected UInt32 readback: 41000000000400004100000001000000
    var program = compile_shader_material(
        VERTEX,
        """
        bool condition(uint i, inout uint calls) { calls += 1u; return i < 256u; }

        void main() {
            uvec4 result = uvec4(0u);
        uint i = 0u; uint total = 0u; uint calls = 0u;
        while (condition(i,calls)) { i += 1u; if (i == 65u) { break; } if ((i % 2u) == 0u) { continue; } total += i; }result = uvec4(i,total,calls,1u);

            gl_FragColor = vec4(float(all(equal(result, uvec4(65u, 1024u, 65u, 1u)))));
        }
        """,
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_do_break_continue() raises:
    """Check independent fixture do_break_continue."""
    # Expected UInt32 readback: 41000000000400004000000001000000
    var program = compile_shader_material(
        VERTEX,
        """
        bool condition(uint i, inout uint calls) { calls += 1u; return i < 256u; }

        void main() {
            uvec4 result = uvec4(0u);
        uint i = 0u; uint total = 0u; uint calls = 0u;
        do { i += 1u; if (i == 65u) { break; } if ((i % 2u) == 0u) { continue; } total += i; } while (condition(i,calls));result = uvec4(i,total,calls,1u);

            gl_FragColor = vec4(float(all(equal(result, uvec4(65u, 1024u, 64u, 1u)))));
        }
        """,
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_while_zero_body() raises:
    """Check independent fixture while_zero_body."""
    # Expected UInt32 readback: 00000000010000000000000001000000
    var program = compile_shader_material(
        VERTEX,
        """
        bool condition(uint i, inout uint calls) { calls += 1u; return false; }

        void main() {
            uvec4 result = uvec4(0u);
        uint i = 0u; uint calls = 0u; while (condition(i,calls)) { i += 1u; } result = uvec4(i,calls,0u,1u);

            gl_FragColor = vec4(float(all(equal(result, uvec4(0u, 1u, 0u, 1u)))));
        }
        """,
    )
    assert_equal(run(program)[0], Float32(1))


def test_reference_do_minimum_one_body() raises:
    """Check independent fixture do_minimum_one_body."""
    # Expected UInt32 readback: 01000000010000000000000001000000
    var program = compile_shader_material(
        VERTEX,
        """
        bool condition(uint i, inout uint calls) { calls += 1u; return false; }

        void main() {
            uvec4 result = uvec4(0u);
        uint i = 0u; uint calls = 0u; do { i += 1u; } while (condition(i,calls)); result = uvec4(i,calls,0u,1u);

            gl_FragColor = vec4(float(all(equal(result, uvec4(1u, 1u, 0u, 1u)))));
        }
        """,
    )
    assert_equal(run(program)[0], Float32(1))


def main() raises:
    TestSuite.discover_tests[__functions_in_module()]().run()
