# Copyright (c) 2026 Seth Kitchen, PE
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
# Noncommercial use is free; commercial use requires a paid license.
# See LICENSE, LICENSE-COMMERCIAL.md and THIRD-PARTY-NOTICES.md.

"""Generated checks against captured Mesa GLSL ES 3.0 references.

Generated by generate_mojo_tests.py from fixtures/fixtures.json.
Unsigned expectations are compared before conversion to float color.
Refusals remain distinct from the captured full GLSL results.
"""

from materials.glsl import compile_shader_material
from tests.test_glsl import VERTEX, run
from std.testing import TestSuite, assert_equal, assert_raises


def test_reference_while_runtime_bound_63() raises:
    """Check independent fixture while_runtime_bound_63."""
    # Expected UInt32 readback: 3f0000003900003f010000013f000000
    with assert_raises(contains="must provably stop within"):
        _ = compile_shader_material(
            VERTEX,
            """
            uniform uint gain; uniform uint limit;

            void main() {
                uvec4 result = uvec4(0u);
            uint i = 0u; uint total = 4294967290u;
            while (i < limit) { i += 1u; total += gain; }
            result = uvec4(i, total, gain, limit);

                gl_FragColor = vec4(float(all(equal(result, uvec4(63u, 1056964665u, 16777217u, 63u)))));
            }
            """,
        )


def test_reference_do_runtime_bound_63() raises:
    """Check independent fixture do_runtime_bound_63."""
    # Expected UInt32 readback: 3f0000003900003f010000013f000000
    with assert_raises(contains="must provably stop within"):
        _ = compile_shader_material(
            VERTEX,
            """
            uniform uint gain; uniform uint limit;

            void main() {
                uvec4 result = uvec4(0u);
            uint i = 0u; uint total = 4294967290u;
            do { i += 1u; total += gain; } while (i < limit);
            result = uvec4(i, total, gain, limit);

                gl_FragColor = vec4(float(all(equal(result, uvec4(63u, 1056964665u, 16777217u, 63u)))));
            }
            """,
        )


def test_reference_while_runtime_bound_64() raises:
    """Check independent fixture while_runtime_bound_64."""
    # Expected UInt32 readback: 400000003a0000400100000140000000
    with assert_raises(contains="must provably stop within"):
        _ = compile_shader_material(
            VERTEX,
            """
            uniform uint gain; uniform uint limit;

            void main() {
                uvec4 result = uvec4(0u);
            uint i = 0u; uint total = 4294967290u;
            while (i < limit) { i += 1u; total += gain; }
            result = uvec4(i, total, gain, limit);

                gl_FragColor = vec4(float(all(equal(result, uvec4(64u, 1073741882u, 16777217u, 64u)))));
            }
            """,
        )


def test_reference_do_runtime_bound_64() raises:
    """Check independent fixture do_runtime_bound_64."""
    # Expected UInt32 readback: 400000003a0000400100000140000000
    with assert_raises(contains="must provably stop within"):
        _ = compile_shader_material(
            VERTEX,
            """
            uniform uint gain; uniform uint limit;

            void main() {
                uvec4 result = uvec4(0u);
            uint i = 0u; uint total = 4294967290u;
            do { i += 1u; total += gain; } while (i < limit);
            result = uvec4(i, total, gain, limit);

                gl_FragColor = vec4(float(all(equal(result, uvec4(64u, 1073741882u, 16777217u, 64u)))));
            }
            """,
        )


def test_reference_while_runtime_bound_65() raises:
    """Check independent fixture while_runtime_bound_65."""
    # Expected UInt32 readback: 410000003b0000410100000141000000
    with assert_raises(contains="must provably stop within"):
        _ = compile_shader_material(
            VERTEX,
            """
            uniform uint gain; uniform uint limit;

            void main() {
                uvec4 result = uvec4(0u);
            uint i = 0u; uint total = 4294967290u;
            while (i < limit) { i += 1u; total += gain; }
            result = uvec4(i, total, gain, limit);

                gl_FragColor = vec4(float(all(equal(result, uvec4(65u, 1090519099u, 16777217u, 65u)))));
            }
            """,
        )


def test_reference_do_runtime_bound_65() raises:
    """Check independent fixture do_runtime_bound_65."""
    # Expected UInt32 readback: 410000003b0000410100000141000000
    with assert_raises(contains="must provably stop within"):
        _ = compile_shader_material(
            VERTEX,
            """
            uniform uint gain; uniform uint limit;

            void main() {
                uvec4 result = uvec4(0u);
            uint i = 0u; uint total = 4294967290u;
            do { i += 1u; total += gain; } while (i < limit);
            result = uvec4(i, total, gain, limit);

                gl_FragColor = vec4(float(all(equal(result, uvec4(65u, 1090519099u, 16777217u, 65u)))));
            }
            """,
        )


def test_reference_while_runtime_bound_128() raises:
    """Check independent fixture while_runtime_bound_128."""
    # Expected UInt32 readback: 800000007a0000800100000180000000
    with assert_raises(contains="must provably stop within"):
        _ = compile_shader_material(
            VERTEX,
            """
            uniform uint gain; uniform uint limit;

            void main() {
                uvec4 result = uvec4(0u);
            uint i = 0u; uint total = 4294967290u;
            while (i < limit) { i += 1u; total += gain; }
            result = uvec4(i, total, gain, limit);

                gl_FragColor = vec4(float(all(equal(result, uvec4(128u, 2147483770u, 16777217u, 128u)))));
            }
            """,
        )


def test_reference_do_runtime_bound_128() raises:
    """Check independent fixture do_runtime_bound_128."""
    # Expected UInt32 readback: 800000007a0000800100000180000000
    with assert_raises(contains="must provably stop within"):
        _ = compile_shader_material(
            VERTEX,
            """
            uniform uint gain; uniform uint limit;

            void main() {
                uvec4 result = uvec4(0u);
            uint i = 0u; uint total = 4294967290u;
            do { i += 1u; total += gain; } while (i < limit);
            result = uvec4(i, total, gain, limit);

                gl_FragColor = vec4(float(all(equal(result, uvec4(128u, 2147483770u, 16777217u, 128u)))));
            }
            """,
        )


def test_reference_while_runtime_bound_256() raises:
    """Check independent fixture while_runtime_bound_256."""
    # Expected UInt32 readback: 00010000fa0000000100000100010000
    with assert_raises(contains="must provably stop within"):
        _ = compile_shader_material(
            VERTEX,
            """
            uniform uint gain; uniform uint limit;

            void main() {
                uvec4 result = uvec4(0u);
            uint i = 0u; uint total = 4294967290u;
            while (i < limit) { i += 1u; total += gain; }
            result = uvec4(i, total, gain, limit);

                gl_FragColor = vec4(float(all(equal(result, uvec4(256u, 250u, 16777217u, 256u)))));
            }
            """,
        )


def test_reference_do_runtime_bound_256() raises:
    """Check independent fixture do_runtime_bound_256."""
    # Expected UInt32 readback: 00010000fa0000000100000100010000
    with assert_raises(contains="must provably stop within"):
        _ = compile_shader_material(
            VERTEX,
            """
            uniform uint gain; uniform uint limit;

            void main() {
                uvec4 result = uvec4(0u);
            uint i = 0u; uint total = 4294967290u;
            do { i += 1u; total += gain; } while (i < limit);
            result = uvec4(i, total, gain, limit);

                gl_FragColor = vec4(float(all(equal(result, uvec4(256u, 250u, 16777217u, 256u)))));
            }
            """,
        )


def test_reference_while_nested_16_by_16() raises:
    """Check independent fixture while_nested_16_by_16."""
    # Expected UInt32 readback: 10000000000100000000000001000000
    with assert_raises(contains="would grow the graph past"):
        _ = compile_shader_material(
            VERTEX,
            """
            void main() {
                uvec4 result = uvec4(0u);
            uint outer = 0u; uint total = 0u; while (outer < 16u) { uint inner = 0u; while (inner < 16u) { inner += 1u; total += 1u; } outer += 1u; } result = uvec4(outer,total,0u,1u);

                gl_FragColor = vec4(float(all(equal(result, uvec4(16u, 256u, 0u, 1u)))));
            }
            """,
        )


def main() raises:
    TestSuite.discover_tests[__functions_in_module()]().run()
