# Copyright (c) 2026 Seth Kitchen, PE
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
# Noncommercial use is free; commercial use requires a paid license.
# See LICENSE, LICENSE-COMMERCIAL.md and THIRD-PARTY-NOTICES.md.

"""Tests for `math.sine`: the sine the CPU and a GPU kernel share."""

from math.sine import (
    _complement_fraction,
    _large_reduction,
    fraction,
    noise_scale,
    sin_float32,
)
from std.math import inf, isfinite, nan, sin
from std.memory import bitcast
from std.testing import (
    TestSuite,
    assert_almost_equal,
    assert_equal,
    assert_true,
)


def test_the_sine_agrees_with_libm() raises:
    # Every octant, both signs, and the large angles the noise hashes
    # take, up to a few thousand radians.
    var angles: List[Float32] = [
        0,
        0.3,
        0.8,
        1.2,
        1.9,
        2.6,
        3.0,
        3.6,
        4.4,
        5.1,
        5.9,
        6.5,
        -0.4,
        -2.2,
        -4.9,
        12.9898,
        91.479,
        578.25,
        3141.7,
    ]
    for x in angles:
        var actual = sin_float32(x)
        assert_true(isfinite(actual))
        assert_almost_equal(actual, sin(x), atol=2e-6)


def test_an_angle_that_is_not_finite_has_no_sine() raises:
    for x in [
        inf[DType.float32](),
        -inf[DType.float32](),
        nan[DType.float32](),
    ]:
        var s = sin_float32(x)
        assert_true(s != s)


def test_the_noise_is_the_fraction_of_the_scaled_sine() raises:
    assert_equal(noise_scale(1), Float32(43758.5453))
    assert_equal(fraction(Float32(2.25)), Float32(0.25))
    assert_equal(fraction(Float32(-0.25)), Float32(0.75))


def test_large_finite_angles_agree_with_libm() raises:
    var samples: List[Float32] = [
        8191.99951171875,
        8192,
        8192.0009765625,
        1e8,
        1e9,
        1e10,
        1e15,
        1e30,
        3e38,
    ]
    for x in samples:
        for angle in [x, -x]:
            var actual = sin_float32(angle)
            assert_true(isfinite(actual))
            assert_almost_equal(actual, sin(angle), atol=2e-6)
    # Stratify the whole finite exponent range and vary the significand.
    var state = UInt32(42)
    for exponent in range(1, 255):
        for _ in range(16):
            state = state * 1664525 + 1013904223
            var bits = (UInt32(exponent) << 23) | (state & 0x7FFFFF)
            var x = bitcast[DType.float32](bits)
            var actual = sin_float32(x)
            assert_true(isfinite(actual))
            assert_true(abs(actual) <= 1)
            assert_almost_equal(actual, sin(x), atol=2e-6)
            var negative = sin_float32(-x)
            assert_true(isfinite(negative))
            assert_almost_equal(negative, sin(-x), atol=2e-6)


def test_sine_preserves_signed_zero_and_subnormal_angles() raises:
    for bits in [UInt32(0), UInt32(0x80000000), UInt32(1), UInt32(0x80000001)]:
        var x = bitcast[DType.float32](bits)
        assert_equal(bitcast[DType.uint32](sin_float32(x)), bits)


def test_fraction_complement_preserves_low_word_carry() raises:
    # Negating a zero low word carries into the high word; a nonzero low
    # word does not. These exact words test both arithmetic cases even
    # though a zero low word does not occur in Float32 angle reduction.
    var carry = _complement_fraction(0x81234567, 0)
    assert_equal(carry[0], UInt32(0x7EDCBA99))
    assert_equal(carry[1], UInt32(0))
    var no_carry = _complement_fraction(0x81234567, 1)
    assert_equal(no_carry[0], UInt32(0x7EDCBA98))
    assert_equal(no_carry[1], UInt32(0xFFFFFFFF))
    var all_bits = _complement_fraction(0xFFFFFFFF, 0xFFFFFFFF)
    assert_equal(all_bits[0], UInt32(0))
    assert_equal(all_bits[1], UInt32(1))
    var zero = _complement_fraction(0, 0)
    assert_equal(zero[0], UInt32(0))
    assert_equal(zero[1], UInt32(0))


# BEGIN GENERATED LARGE-ANGLE PHASE FIXTURE
# Generated by tools/reference_sine_phases.py; do not edit by hand.
# Inputs, reference remainders, and reference sines use exact bits.
def large_angle_phase_cases() -> List[Tuple[Int, Int, Int, Int]]:
    """Return independent positive-angle phase fixtures.

    Returns:
        Angle bits, nearest quadrant, remainder bits, and sine bits.
    """
    return [
        # 2^13 band: 8192 * pi/2; below, below, above, above.
        (0x46490FD9, 0, 0xBAD110B4, 0xBAD110AF),
        (0x46490FDA, 0, 0xBA222169, 0xBA222168),
        (0x46490FDB, 0, 0x39BBBD2E, 0x39BBBD2E),
        (0x46490FDC, 0, 0x3AAEEF4C, 0x3AAEEF48),
        # 2^13 band: (8192 + 1/2) * pi/2; below, below, above, above.
        (0x464912FD, 0, 0x3F489778, 0x3F34AFBF),
        (0x464912FE, 0, 0x3F48D778, 0x3F34DD10),
        (0x464912FF, 1, 0xBF49083E, 0x3F350A55),
        (0x46491300, 1, 0xBF48C83E, 0x3F353790),
        # 2^13 band: 8197 * pi/2; below, below, above, above.
        (0x46492F44, 1, 0xBA8E255F, 0x3F7FFFF6),
        (0x46492F45, 1, 0xB8E255F0, 0x3F800000),
        (0x46492F46, 1, 0x3A63B542, 0x3F7FFFFA),
        (0x46492F47, 1, 0x3AF1DAA1, 0x3F7FFFE3),
        # 2^13 band: (8197 + 1/2) * pi/2; below, below, above, above.
        (0x46493268, 1, 0x3F48B8ED, 0x3F354260),
        (0x46493269, 1, 0x3F48F8ED, 0x3F351529),
        (0x4649326A, 2, 0xBF48E6C8, 0x3F34E7E6),
        (0x4649326B, 2, 0xBF48A6C8, 0x3F34BA98),
        # 2^13 band: 8202 * pi/2; below, below, above, above.
        (0x46494EAE, 2, 0xBACB3A0A, 0x3ACB3A04),
        (0x46494EAF, 2, 0xBA167413, 0x3A167413),
        (0x46494EB0, 2, 0x39D317DA, 0xB9D317D9),
        (0x46494EB1, 2, 0x3AB4C5F6, 0xBAB4C5F3),
        # 2^13 band: (8202 + 1/2) * pi/2; below, below, above, above.
        (0x464951D2, 2, 0x3F489A63, 0xBF34B1D0),
        (0x464951D3, 2, 0x3F48DA63, 0xBF34DF21),
        (0x464951D4, 3, 0xBF490552, 0xBF350C66),
        (0x464951D5, 3, 0xBF48C552, 0xBF35399F),
        # 2^13 band: 8207 * pi/2; below, below, above, above.
        (0x46496E19, 3, 0xBA884EB4, 0xBF7FFFF7),
        (0x46496E1A, 3, 0xB884EB43, 0xBF800000),
        (0x46496E1B, 3, 0x3A6F6298, 0xBF7FFFF9),
        (0x46496E1C, 3, 0x3AF7B14C, 0xBF7FFFE2),
        # 2^13 band: (8207 + 1/2) * pi/2; below, below, above, above.
        (0x4649713D, 3, 0x3F48BBD9, 0xBF354050),
        (0x4649713E, 3, 0x3F48FBD9, 0xBF351318),
        (0x4649713F, 0, 0xBF48E3DD, 0xBF34E5D5),
        (0x46497140, 0, 0xBF48A3DD, 0xBF34B886),
        # 2^17 band: 131072 * pi/2; below, below, above, above.
        (0x48490FD9, 0, 0xBCD110B4, 0xBCD10AE5),
        (0x48490FDA, 0, 0xBC222169, 0xBC2220BB),
        (0x48490FDB, 0, 0x3BBBBD2E, 0x3BBBBCEB),
        (0x48490FDC, 0, 0x3CAEEF4C, 0x3CAEEBE4),
        # 2^17 band: (131072 + 1/2) * pi/2; below, below, above, above.
        (0x4849100B, 0, 0x3F41777A, 0x3F2F91E0),
        (0x4849100C, 0, 0x3F45777A, 0x3F327599),
        (0x4849100D, 1, 0xBF48A83B, 0x3F354E2A),
        (0x4849100E, 1, 0xBF44A83B, 0x3F381B67),
        # 2^17 band: 131077 * pi/2; below, below, above, above.
        (0x484911D0, 1, 0xBCA4E1FF, 0x3F7FF2BA),
        (0x484911D1, 1, 0xBB9387FC, 0x3F7FFF56),
        (0x484911D2, 1, 0x3C363C02, 0x3F7FFBF2),
        (0x484911D3, 1, 0x3CDB1E01, 0x3F7FE88F),
        # 2^17 band: (131077 + 1/2) * pi/2; below, below, above, above.
        (0x48491202, 1, 0x3F42D8F0, 0x3F395C22),
        (0x48491203, 1, 0x3F46D8F0, 0x3F369415),
        (0x48491204, 2, 0xBF4746C5, 0x3F33C09E),
        (0x48491205, 2, 0xBF4346C5, 0x3F30E1EC),
        # 2^17 band: 131082 * pi/2; below, below, above, above.
        (0x484913C6, 2, 0xBCF8B34A, 0x3CF8A982),
        (0x484913C7, 2, 0xBC716693, 0x3C716457),
        (0x484913C8, 2, 0x3A6996C9, 0xBA6996C7),
        (0x484913C9, 2, 0x3C874CB6, 0xBC874B23),
        # 2^17 band: (131082 + 1/2) * pi/2; below, below, above, above.
        (0x484913F9, 2, 0x3F443A66, 0xBF3191BA),
        (0x484913FA, 2, 0x3F483A66, 0xBF346DC5),
        (0x484913FB, 3, 0xBF45E550, 0xBF373E88),
        (0x484913FC, 3, 0xBF41E550, 0xBF3A03D8),
        # 2^17 band: 131087 * pi/2; below, below, above, above.
        (0x484915BD, 3, 0xBCCC8494, 0xBF7FEB94),
        (0x484915BE, 3, 0xBC190929, 0xBF7FFD24),
        (0x484915BF, 3, 0x3BCDEDAF, 0xBF7FFEB5),
        (0x484915C0, 3, 0x3CB37B6C, 0xBF7FF045),
        # 2^17 band: (131087 + 1/2) * pi/2; below, below, above, above.
        (0x484915EF, 3, 0x3F419BDB, 0xBF3A3647),
        (0x484915F0, 3, 0x3F459BDB, 0xBF3771CC),
        (0x484915F1, 0, 0xBF4883DA, 0xBF34A1D9),
        (0x484915F2, 0, 0xBF4483DA, 0xBF31C69C),
        # 2^21 band: 2097152 * pi/2; below, below, above, above.
        (0x4A490FD9, 0, 0xBED110B4, 0xBECB4DC5),
        (0x4A490FDA, 0, 0xBE222169, 0xBE217437),
        (0x4A490FDB, 0, 0x3DBBBD2E, 0x3DBB79E6),
        (0x4A490FDC, 0, 0x3EAEEF4C, 0x3EAB8D0C),
        # 2^21 band: (2097152 + 1/2) * pi/2; below, below, above, above.
        (0x4A490FDC, 0, 0x3EAEEF4C, 0x3EAB8D0C),
        (0x4A490FDD, 0, 0x3F1777A6, 0x3F0EC889),
        (0x4A490FDE, 1, 0xBF3AA80F, 0x3F3EE9E4),
        (0x4A490FDF, 1, 0xBEF5501F, 0x3F632C80),
        # 2^21 band: 2097157 * pi/2; below, below, above, above.
        (0x4A490FF9, 1, 0xBE864DC9, 0x3F773E35),
        (0x4A490FFA, 1, 0xBC49B921, 0x3F7FFB08),
        (0x4A490FFB, 1, 0x3E73646E, 0x3F78CD74),
        (0x4A490FFC, 1, 0x3EF9B237, 0x3F6227BA),
        # 2^21 band: (2097157 + 1/2) * pi/2; below, below, above, above.
        (0x4A490FFC, 1, 0x3EF9B237, 0x3F6227BA),
        (0x4A490FFD, 1, 0x3F3CD91B, 0x3F3D7253),
        (0x4A490FFE, 2, 0xBF15469A, 0x3F0CF587),
        (0x4A490FFF, 2, 0xBEAA8D34, 0x3EA76A38),
        # 2^21 band: 2097162 * pi/2; below, below, above, above.
        (0x4A491018, 2, 0xBEBB8ADE, 0x3EB7606F),
        (0x4A491019, 2, 0xBDEE2B77, 0x3DEDA220),
        (0x4A49101A, 2, 0x3E08EA45, 0xBE0881ED),
        (0x4A49101B, 2, 0x3EC47522, 0xBEBFAC13),
        # 2^21 band: (2097162 + 1/2) * pi/2; below, below, above, above.
        (0x4A49101B, 2, 0x3EC47522, 0xBEBFAC13),
        (0x4A49101C, 2, 0x3F223A91, 0xBF17962F),
        (0x4A49101D, 3, 0xBF2FE524, 0xBF45E98D),
        (0x4A49101E, 3, 0xBEDFCA48, 0xBF67EEC8),
        # 2^21 band: 2097167 * pi/2; below, below, above, above.
        (0x4A491037, 3, 0xBEF0C7F2, 0xBF6435A4),
        (0x4A491038, 3, 0xBE618FE5, 0xBF79D079),
        (0x4A491039, 3, 0x3CF380DA, 0xBF7FE30D),
        (0x4A49103A, 3, 0x3E8F380E, 0xBF760CB7),
        # 2^21 band: (2097167 + 1/2) * pi/2; below, below, above, above.
        (0x4A49103B, 3, 0x3F079C07, 0xBF5CEA0C),
        (0x4A49103C, 3, 0x3F479C07, 0xBF360B20),
        (0x4A49103D, 0, 0xBF0A83AE, 0xBF03DAA5),
        (0x4A49103E, 0, 0xBE95075D, 0xBE92EEED),
        # 2^23 band: 8388608 * pi/2; below, below, above, above.
        (0x4B490FD9, 3, 0xBD800D9C, 0xBF7F7FEF),
        (0x4B490FDA, 0, 0xBF222169, 0xBF1781E9),
        (0x4B490FDB, 0, 0x3EBBBD2E, 0x3EB78F68),
        (0x4B490FDC, 1, 0xBE510478, 0x3F7AAF79),
        # 2^23 band: (8388608 + 1/2) * pi/2; below, below, above, above.
        (0x4B490FDA, 0, 0xBF222169, 0xBF1781E9),
        (0x4B490FDB, 0, 0x3EBBBD2E, 0x3EB78F68),
        (0x4B490FDC, 1, 0xBE510478, 0x3F7AAF79),
        (0x4B490FDD, 2, 0xBF4660D3, 0x3F331C9C),
        # 2^23 band: 8388617 * pi/2; below, below, above, above.
        (0x4B490FE7, 0, 0xBE4C7C4C, 0xBE4B2112),
        (0x4B490FE8, 1, 0xBF453EC8, 0x3F37B2AB),
        (0x4B490FE9, 1, 0x3E6B04DF, 0x3F794981),
        (0x4B490FEA, 2, 0xBEAEBCFB, 0x3EAB5DA3),
        # 2^23 band: (8388617 + 1/2) * pi/2; below, below, above, above.
        (0x4B490FE8, 1, 0xBF453EC8, 0x3F37B2AB),
        (0x4B490FE9, 1, 0x3E6B04DF, 0x3F794981),
        (0x4B490FEA, 2, 0xBEAEBCFB, 0x3EAB5DA3),
        (0x4B490FEB, 2, 0x3F28A183, 0xBF1CB2A3),
        # 2^23 band: 8388626 * pi/2; below, below, above, above.
        (0x4B490FF5, 1, 0xBEAC78E5, 0x3F719CB2),
        (0x4B490FF6, 1, 0x3F29C38E, 0x3F49BE80),
        (0x4B490FF7, 2, 0x3DBD1EC4, 0xBDBCD9FC),
        (0x4B490FF8, 3, 0xBEF4F7BA, 0xBF6340DD),
        # 2^23 band: (8388626 + 1/2) * pi/2; below, below, above, above.
        (0x4B490FF6, 1, 0x3F29C38E, 0x3F49BE80),
        (0x4B490FF7, 2, 0x3DBD1EC4, 0xBDBCD9FC),
        (0x4B490FF8, 3, 0xBEF4F7BA, 0xBF6340DD),
        (0x4B490FF9, 3, 0x3F058423, 0xBF5DF6F0),
        # 2^23 band: 8388635 * pi/2; below, below, above, above.
        (0x4B491004, 2, 0x3F06A62E, 0xBF0086AC),
        (0x4B491005, 3, 0xBD37986F, 0xBF7FBE2D),
        (0x4B491006, 0, 0xBF1D993C, 0xBF13D4B4),
        (0x4B491007, 0, 0x3EC4CD88, 0x3EBFFE08),
        # 2^23 band: (8388635 + 1/2) * pi/2; below, below, above, above.
        (0x4B491004, 2, 0x3F06A62E, 0xBF0086AC),
        (0x4B491005, 3, 0xBD37986F, 0xBF7FBE2D),
        (0x4B491006, 0, 0xBF1D993C, 0xBF13D4B4),
        (0x4B491007, 0, 0x3EC4CD88, 0x3EBFFE08),
        # 2^31 band: 2147483648 * pi/2; below, below, above, above.
        (0x4F490FD9, 2, 0xBE98ECD3, 0x3E96A955),
        (0x4F490FDA, 1, 0xBEAD4DA7, 0x3F717974),
        (0x4F490FDB, 0, 0xBEC1AE7C, 0xBEBD1862),
        (0x4F490FDC, 3, 0xBED60F51, 0xBF69F33F),
        # 2^31 band: (2147483648 + 1/2) * pi/2; below, below, above, above.
        (0x4F490FD9, 2, 0xBE98ECD3, 0x3E96A955),
        (0x4F490FDA, 1, 0xBEAD4DA7, 0x3F717974),
        (0x4F490FDB, 0, 0xBEC1AE7C, 0xBEBD1862),
        (0x4F490FDC, 3, 0xBED60F51, 0xBF69F33F),
        # 2^31 band: 2147485697 * pi/2; below, below, above, above.
        (0x4F490FE6, 0, 0x3F4133E4, 0x3F2F60AA),
        (0x4F490FE7, 3, 0x3F37037A, 0xBF41523A),
        (0x4F490FE8, 2, 0x3F2CD30F, 0xBF1FFE28),
        (0x4F490FE9, 1, 0x3F22A2A5, 0x3F4E0DBD),
        # 2^31 band: (2147485697 + 1/2) * pi/2; below, below, above, above.
        (0x4F490FE6, 0, 0x3F4133E4, 0x3F2F60AA),
        (0x4F490FE7, 3, 0x3F37037A, 0xBF41523A),
        (0x4F490FE8, 2, 0x3F2CD30F, 0xBF1FFE28),
        (0x4F490FE9, 1, 0x3F22A2A5, 0x3F4E0DBD),
        # 2^31 band: 2147487746 * pi/2; below, below, above, above.
        (0x4F490FF2, 0, 0x3E8DDDCD, 0x3E8C0EDD),
        (0x4F490FF3, 3, 0x3E72F9F0, 0xBF78D3B8),
        (0x4F490FF4, 2, 0x3E4A3846, 0xBE48E873),
        (0x4F490FF5, 1, 0x3E21769C, 0x3F7CD2FD),
        # 2^31 band: (2147487746 + 1/2) * pi/2; below, below, above, above.
        (0x4F490FF2, 0, 0x3E8DDDCD, 0x3E8C0EDD),
        (0x4F490FF3, 3, 0x3E72F9F0, 0xBF78D3B8),
        (0x4F490FF4, 2, 0x3E4A3846, 0xBE48E873),
        (0x4F490FF5, 1, 0x3E21769C, 0x3F7CD2FD),
        # 2^31 band: 2147489795 * pi/2; below, below, above, above.
        (0x4F490FFF, 3, 0xBE761A06, 0xBF78A468),
        (0x4F491000, 2, 0xBE8F6DD8, 0x3E8D8F7C),
        (0x4F491001, 1, 0xBEA3CEAD, 0x3F730268),
        (0x4F491002, 0, 0xBEB82F82, 0xBEB43D15),
        # 2^31 band: (2147489795 + 1/2) * pi/2; below, below, above, above.
        (0x4F490FFF, 3, 0xBE761A06, 0xBF78A468),
        (0x4F491000, 2, 0xBE8F6DD8, 0x3E8D8F7C),
        (0x4F491001, 1, 0xBEA3CEAD, 0x3F730268),
        (0x4F491002, 0, 0xBEB82F82, 0xBEB43D15),
        # 2^47 band: 140737488355328 * pi/2; below, below, above, above.
        (0x57490FD9, 3, 0xBF37DD0B, 0xBF40C354),
        (0x57490FDA, 2, 0xBD2987AF, 0x3D297B4B),
        (0x57490FDB, 1, 0x3F22AC16, 0x3F4E0823),
        (0x57490FDC, 1, 0xBE845E1E, 0x3F777E06),
        # 2^47 band: (140737488355328 + 1/2) * pi/2; below, below, above, above.
        (0x57490FD9, 3, 0xBF37DD0B, 0xBF40C354),
        (0x57490FDA, 2, 0xBD2987AF, 0x3D297B4B),
        (0x57490FDB, 1, 0x3F22AC16, 0x3F4E0823),
        (0x57490FDC, 1, 0xBE845E1E, 0x3F777E06),
        # 2^47 band: 140737622573057 * pi/2; below, below, above, above.
        (0x57490FE6, 3, 0x3E67FF03, 0xBF79753D),
        (0x57490FE7, 3, 0xBF2ADB64, 0xBF4911C3),
        (0x57490FE8, 2, 0x3C1A4B18, 0xBC1A4A83),
        (0x57490FE9, 1, 0x3F2FADBD, 0x3F460CAD),
        # 2^47 band: (140737622573057 + 1/2) * pi/2; below, below, above, above.
        (0x57490FE6, 3, 0x3E67FF03, 0xBF79753D),
        (0x57490FE7, 3, 0xBF2ADB64, 0xBF4911C3),
        (0x57490FE8, 2, 0x3C1A4B18, 0xBC1A4A83),
        (0x57490FE9, 1, 0x3F2FADBD, 0x3F460CAD),
        # 2^47 band: 140737756790786 * pi/2; below, below, above, above.
        (0x57490FF2, 0, 0x3EFD2FF8, 0x3EF2FE6F),
        (0x57490FF3, 0, 0xBECC8651, 0xBEC720EA),
        (0x57490FF4, 3, 0x3E8E02D0, 0xBF76373B),
        (0x57490FF5, 3, 0xBF1DD9BD, 0xBF50DB5C),
        # 2^47 band: (140737756790786 + 1/2) * pi/2; below, below, above, above.
        (0x57490FF2, 0, 0x3EFD2FF8, 0x3EF2FE6F),
        (0x57490FF3, 0, 0xBECC8651, 0xBEC720EA),
        (0x57490FF4, 3, 0x3E8E02D0, 0xBF76373B),
        (0x57490FF5, 3, 0xBF1DD9BD, 0xBF50DB5C),
        # 2^47 band: 140737891008515 * pi/2; below, below, above, above.
        (0x57490FFF, 1, 0xBE06ABB4, 0x3F7DCA0F),
        (0x57491000, 0, 0x3F0B99A4, 0x3F04C898),
        (0x57491001, 0, 0xBEB28302, 0xBEAEEAC1),
        (0x57491002, 3, 0x3EA8061F, 0xBF72568E),
        # 2^47 band: (140737891008515 + 1/2) * pi/2; below, below, above, above.
        (0x57490FFF, 1, 0xBE06ABB4, 0x3F7DCA0F),
        (0x57491000, 0, 0x3F0B99A4, 0x3F04C898),
        (0x57491001, 0, 0xBEB28302, 0xBEAEEAC1),
        (0x57491002, 3, 0x3EA8061F, 0xBF72568E),
        # 2^63 band: 9223372036854775808 * pi/2; below, below, above, above.
        (0x5F490FD9, 3, 0xBE07D7D6, 0xBF7DC02E),
        (0x5F490FDA, 1, 0x3E91F76A, 0x3F75AAB7),
        (0x5F490FDB, 3, 0x3F33ED60, 0xBF43548F),
        (0x5F490FDC, 2, 0xBEE68155, 0x3EDECC0E),
        # 2^63 band: (9223372036854775808 + 1/2) * pi/2; below, below, above, above.
        (0x5F490FD9, 3, 0xBE07D7D6, 0xBF7DC02E),
        (0x5F490FDA, 1, 0x3E91F76A, 0x3F75AAB7),
        (0x5F490FDB, 3, 0x3F33ED60, 0xBF43548F),
        (0x5F490FDC, 2, 0xBEE68155, 0x3EDECC0E),
        # 2^63 band: 9223380832947798017 * pi/2; below, below, above, above.
        (0x5F490FE6, 0, 0x3F15F096, 0x3F0D834D),
        (0x5F490FE7, 3, 0xBF113D75, 0xBF57E48F),
        (0x5F490FE8, 1, 0xBE192F28, 0x3F7D2413),
        (0x5F490FE9, 3, 0x3E894BC1, 0xBF76D9D1),
        # 2^63 band: (9223380832947798017 + 1/2) * pi/2; below, below, above, above.
        (0x5F490FE6, 0, 0x3F15F096, 0x3F0D834D),
        (0x5F490FE7, 3, 0xBF113D75, 0xBF57E48F),
        (0x5F490FE8, 1, 0xBE192F28, 0x3F7D2413),
        (0x5F490FE9, 3, 0x3E894BC1, 0xBF76D9D1),
        # 2^63 band: 9223389629040820226 * pi/2; below, below, above, above.
        (0x5F490FF2, 0, 0xBF2F3A3F, 0xBF21DC97),
        (0x5F490FF3, 2, 0xBE889128, 0x3E86F412),
        (0x5F490FF4, 0, 0x3E1AA45A, 0x3E1A0E0C),
        (0x5F490FF5, 2, 0x3F119AC1, 0xBF09E14E),
        # 2^63 band: (9223389629040820226 + 1/2) * pi/2; below, below, above, above.
        (0x5F490FF2, 0, 0xBF2F3A3F, 0xBF21DC97),
        (0x5F490FF3, 2, 0xBE889128, 0x3E86F412),
        (0x5F490FF4, 0, 0x3E1AA45A, 0x3E1A0E0C),
        (0x5F490FF5, 2, 0x3F119AC1, 0xBF09E14E),
        # 2^63 band: 9223398425133842435 * pi/2; below, below, above, above.
        (0x5F490FFF, 1, 0x3D0AC4C7, 0x3F7FDA65),
        (0x5F491000, 3, 0x3EE73BEE, 0xBF66552F),
        (0x5F491001, 2, 0xBF339013, 0x3F253271),
        (0x5F491002, 0, 0xBE913CD1, 0xBE8F4C2F),
        # 2^63 band: (9223398425133842435 + 1/2) * pi/2; below, below, above, above.
        (0x5F490FFF, 1, 0x3D0AC4C7, 0x3F7FDA65),
        (0x5F491000, 3, 0x3EE73BEE, 0xBF66552F),
        (0x5F491001, 2, 0xBF339013, 0x3F253271),
        (0x5F491002, 0, 0xBE913CD1, 0xBE8F4C2F),
        # 2^95 band: 39614081257132168796771975168 * pi/2; below, below, above, above.
        (0x6F490FD9, 3, 0x3F0AA70C, 0xBF5B5C6D),
        (0x6F490FDA, 3, 0x3F4873D3, 0xBF357326),
        (0x6F490FDB, 0, 0xBF0BDF1B, 0xBF0503F7),
        (0x6F490FDC, 0, 0xBE9C24A8, 0xBE99BBEC),
        # 2^95 band: (39614081257132168796771975168 + 1/2) * pi/2; below, below, above, above.
        (0x6F490FD9, 3, 0x3F0AA70C, 0xBF5B5C6D),
        (0x6F490FDA, 3, 0x3F4873D3, 0xBF357326),
        (0x6F490FDB, 0, 0xBF0BDF1B, 0xBF0503F7),
        (0x6F490FDC, 0, 0xBE9C24A8, 0xBE99BBEC),
        # 2^95 band: 39614119036064031753933684737 * pi/2; below, below, above, above.
        (0x6F490FE6, 1, 0x3F09CDBF, 0x3F5BCC24),
        (0x6F490FE7, 1, 0x3F479A86, 0x3F360C2F),
        (0x6F490FE8, 2, 0xBF0CB868, 0x3F05BD71),
        (0x6F490FE9, 2, 0xBE9DD742, 0x3E9B5A41),
        # 2^95 band: (39614119036064031753933684737 + 1/2) * pi/2; below, below, above, above.
        (0x6F490FE6, 1, 0x3F09CDBF, 0x3F5BCC24),
        (0x6F490FE7, 1, 0x3F479A86, 0x3F360C2F),
        (0x6F490FE8, 2, 0xBF0CB868, 0x3F05BD71),
        (0x6F490FE9, 2, 0xBE9DD742, 0x3E9B5A41),
        # 2^95 band: 39614156814995894711095394306 * pi/2; below, below, above, above.
        (0x6F490FF2, 3, 0x3E964F55, 0xBF750C18),
        (0x6F490FF3, 3, 0x3F08F472, 0xBF5C3B3C),
        (0x6F490FF4, 3, 0x3F46C139, 0xBF36A4B4),
        (0x6F490FF5, 0, 0xBF0D91B5, 0xBF06768B),
        # 2^95 band: (39614156814995894711095394306 + 1/2) * pi/2; below, below, above, above.
        (0x6F490FF2, 3, 0x3E964F55, 0xBF750C18),
        (0x6F490FF3, 3, 0x3F08F472, 0xBF5C3B3C),
        (0x6F490FF4, 3, 0x3F46C139, 0xBF36A4B4),
        (0x6F490FF5, 0, 0xBF0D91B5, 0xBF06768B),
        # 2^95 band: 39614194593927757668257103875 * pi/2; below, below, above, above.
        (0x6F490FFF, 1, 0x3E949CBB, 0x3F754AA1),
        (0x6F491000, 1, 0x3F081B25, 0x3F5CA9B6),
        (0x6F491001, 1, 0x3F45E7EC, 0x3F373CB6),
        (0x6F491002, 2, 0xBF0E6B02, 0x3F072F44),
        # 2^95 band: (39614194593927757668257103875 + 1/2) * pi/2; below, below, above, above.
        (0x6F490FFF, 1, 0x3E949CBB, 0x3F754AA1),
        (0x6F491000, 1, 0x3F081B25, 0x3F5CA9B6),
        (0x6F491001, 1, 0x3F45E7EC, 0x3F373CB6),
        (0x6F491002, 2, 0xBF0E6B02, 0x3F072F44),
        # 2^126 band: 85070591730234615865843651857942052864 * pi/2; below, below, above, above.
        (0x7EC90FD9, 0, 0xBF1B193A, 0xBF11C865),
        (0x7EC90FDA, 2, 0x3EAEF806, 0xBEAB9546),
        (0x7EC90FDB, 1, 0xBE901CEA, 0x3F75ED07),
        (0x7EC90FDC, 3, 0x3F2A86C8, 0xBF494617),
        # 2^126 band: (85070591730234615865843651857942052864 + 1/2) * pi/2; below, below, above, above.
        (0x7EC90FD9, 0, 0xBF1B193A, 0xBF11C865),
        (0x7EC90FDA, 2, 0x3EAEF806, 0xBEAB9546),
        (0x7EC90FDB, 1, 0xBE901CEA, 0x3F75ED07),
        (0x7EC90FDC, 3, 0x3F2A86C8, 0xBF494617),
        # 2^126 band: 85070672859873030472525347646947196929 * pi/2; below, below, above, above.
        (0x7EC90FE6, 1, 0x3F379CED, 0x3F40ED7F),
        (0x7EC90FE7, 0, 0x3DC093A5, 0x3DC04B06),
        (0x7EC90FE8, 3, 0xBF077803, 0xBF5CFC3D),
        (0x7EC90FE9, 1, 0x3ED63A73, 0x3F69EA7C),
        # 2^126 band: (85070672859873030472525347646947196929 + 1/2) * pi/2; below, below, above, above.
        (0x7EC90FE6, 1, 0x3F379CED, 0x3F40ED7F),
        (0x7EC90FE7, 0, 0x3DC093A5, 0x3DC04B06),
        (0x7EC90FE8, 3, 0xBF077803, 0xBF5CFC3D),
        (0x7EC90FE9, 1, 0x3ED63A73, 0x3F69EA7C),
        # 2^126 band: 85070753989511445079207043435952340994 * pi/2; below, below, above, above.
        (0x7EC90FF2, 1, 0xBEF4C3BE, 0x3F634CD3),
        (0x7EC90FF3, 3, 0x3EF066BC, 0xBF644BA6),
        (0x7EC90FF4, 2, 0xBE1D5C68, 0x3E1CBE0A),
        (0x7EC90FF5, 1, 0xBF46E192, 0x3F368E08),
        # 2^126 band: (85070753989511445079207043435952340994 + 1/2) * pi/2; below, below, above, above.
        (0x7EC90FF2, 1, 0xBEF4C3BE, 0x3F634CD3),
        (0x7EC90FF3, 3, 0x3EF066BC, 0xBF644BA6),
        (0x7EC90FF4, 2, 0xBE1D5C68, 0x3E1CBE0A),
        (0x7EC90FF5, 1, 0xBF46E192, 0x3F368E08),
        # 2^126 band: 85070835119149859685888739224957485059 * pi/2; below, below, above, above.
        (0x7EC90FFF, 3, 0xBF39CB6E, 0xBF3F7C9A),
        (0x7EC91000, 1, 0x3E63273E, 0x3F79BA25),
        (0x7EC91001, 0, 0xBECD8151, 0xBEC8080F),
        (0x7EC91002, 2, 0x3F0BD495, 0xBF04FAF9),
        # 2^126 band: (85070835119149859685888739224957485059 + 1/2) * pi/2; below, below, above, above.
        (0x7EC90FFF, 3, 0xBF39CB6E, 0xBF3F7C9A),
        (0x7EC91000, 1, 0x3E63273E, 0x3F79BA25),
        (0x7EC91001, 0, 0xBECD8151, 0xBEC8080F),
        (0x7EC91002, 2, 0x3F0BD495, 0xBF04FAF9),
    ]


# END GENERATED LARGE-ANGLE PHASE FIXTURE


def test_large_angle_phase_neighbors_agree_with_independent_references() raises:
    # Every nonzero finite binary value is rational. A nonzero multiple
    # of pi/2, or a midpoint (2*k+1)*pi/4, is irrational. Thus an exact
    # binary input cannot equal either target. The fixture stores the
    # two adjacent representable values on each side, never a rounded pi.
    for sample in large_angle_phase_cases():
        var x = bitcast[DType.float32](UInt32(sample[0]))
        var remainder = bitcast[DType.float32](UInt32(sample[2]))
        var oracle = bitcast[DType.float32](UInt32(sample[3]))
        var reduced = _large_reduction(x)
        assert_equal(reduced[0], sample[1])
        assert_almost_equal(reduced[1], remainder, atol=2e-6)
        for sign in [Float32(1), Float32(-1)]:
            var angle = sign * x
            var actual = sin_float32(angle)
            assert_true(isfinite(actual))
            assert_true(abs(actual) <= 1)
            assert_almost_equal(actual, sign * oracle, atol=2e-6)
            assert_almost_equal(actual, sin(angle), atol=2e-6)


def main() raises:
    TestSuite.discover_tests[__functions_in_module()]().run()
