# Copyright (c) 2026 Seth Kitchen, PE
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
"""Write Make prerequisites for each example's imports and quoted assets.

The library list still includes every extension for lint and coverage.
Rendering one example depends only on the modules and fixtures it reaches.
Dynamic external asset caches are not tracked; use make -B after changing one.
"""

import argparse
import os
from pathlib import Path
import tempfile

import affected
import suite_key

TOOLS = ['Makefile', 'tools/example_inputs.py', 'tools/affected.py',
         'tools/suite_key.py', 'tools/optimize_png.py']


def dependencies():
    """Return per-example prerequisites using the tested import resolver."""
    known = set(affected.mojo_files())
    imports = {}
    assets = suite_key.asset_files()
    result = {}
    for example in sorted(p for p in known if p.startswith('examples/')):
        files = suite_key.closure(example, known, imports)
        quoted = {prefix for path in files for prefix in imports[path][1]}
        used = [p for p in assets if any(p.startswith(q) for q in quoted)]
        result[Path(example).stem] = sorted(set(TOOLS + files + used))
    return result


def makefile_text(inputs):
    """Encode controlled repository paths as Make variable assignments."""
    lines = ['# Generated by tools/example_inputs.py; do not edit.']
    for name, paths in sorted(inputs.items()):
        for token in [name] + paths:
            if any(c.isspace() or c in '#$:\\' for c in token):
                raise ValueError(f'unsupported Make prerequisite path: {token!r}')
        lines.append(f'EXAMPLE_INPUTS_{name} := ' + ' '.join(paths))
    return '\n'.join(lines) + '\n'


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', required=True, type=Path)
    args = parser.parse_args(argv)
    text = makefile_text(dependencies())
    if args.output.exists() and args.output.read_text() == text:
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    fd, name = tempfile.mkstemp(prefix='example-inputs.', dir=args.output.parent)
    try:
        with os.fdopen(fd, 'w') as target:
            target.write(text)
        os.replace(name, args.output)
    finally:
        if os.path.exists(name):
            os.unlink(name)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
