#!/usr/bin/env python3
# Copyright (c) 2026 Seth Kitchen, PE
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
"""Regenerate binary64 predicate cases with Python's independent Fraction."""

import argparse
from fractions import Fraction
from pathlib import Path
import math
import random
import struct

ROOT = Path(__file__).resolve().parents[1]


def subtract(a, b):
    return tuple(x - y for x, y in zip(a, b))


def dot(a, b):
    return sum(x * y for x, y in zip(a, b))


def cross(a, b):
    return (a[1] * b[2] - a[2] * b[1],
            a[2] * b[0] - a[0] * b[2],
            a[0] * b[1] - a[1] * b[0])


def sign(x):
    return (x > 0) - (x < 0)


def plane(a, b, c, p):
    normal = cross(subtract(b, a), subtract(c, a))
    return dot(normal, subtract(p, a)), dot(normal, normal)


def segment(a, b, p):
    edge, gap = subtract(b, a), subtract(p, a)
    squared = dot(edge, edge)
    projection = dot(edge, gap)
    if not squared or projection <= 0:
        return dot(gap, gap)
    if projection >= squared:
        gap = subtract(p, b)
        return dot(gap, gap)
    return dot(gap, gap) - projection * projection / squared


def literal(x):
    bits = struct.unpack('>Q', struct.pack('>d', x))[0]
    return f'_f(0x{bits:016X})'


def generate():
    rng = random.Random(538)
    cases = []
    zero = (0., 0., 0.)
    for power in [-1074, -1022, -500, -1, 0, 53, 500, 1022]:
        s = math.ldexp(1., power)
        a, b, c, p = zero, (s, 0., 0.), (0., s, 0.), (0., 0., s)
        q = (0., 0., -s)
        for t in [0., s, math.nextafter(s, 0.)]:
            cases.append(([a, b, c, p, a, c, b, q], t))
    largest = float.fromhex('0x1.fffffffffffffp+1023')
    tiny = float.fromhex('0x0.0000000000001p-1022')
    cases += [
        ([(largest, tiny, 0.), (-largest, 0., 0.), (0., largest, tiny),
          (tiny, 0., largest), zero, (tiny, 0., 0.), (0., tiny, 0.),
          (0., 0., tiny)], tiny),
        ([(2.**53, 1., 0.), (0., 0., 0.), (2.**53, 0., 1.),
          (1., 0., 0.), zero, (1., 0., 0.), (0., 1., 0.), (0., 0., 1.)], 0.),
    ]
    # Integer cases include exact ties, either projection endpoint, and
    # nonparallel planes. The extreme cases force the bounded fallback.
    for _ in range(32):
        points = [tuple(float(rng.randrange(-4, 5)) for _ in range(3))
                  for _ in range(8)]
        if not plane(*map(lambda p: tuple(map(Fraction, p)), points[:4]))[1]:
            continue
        if not plane(*map(lambda p: tuple(map(Fraction, p)), points[4:]))[1]:
            continue
        cases.append((points, float(rng.choice([0, 1, 2, 3]))))
    for _ in range(24):
        points = [tuple(math.ldexp(rng.uniform(-1, 1), rng.choice(
            [-1070, -1000, -500, -54, 0, 54, 500, 1000, 1023]))
                        for _ in range(3)) for _ in range(8)]
        cases.append((points, math.ldexp(1., rng.choice([-1074, -500, 0, 500]))))

    # Cancellation around the certified determinant error bound. Here
    # D=delta and its absolute permanent is 4+delta.
    epsilon = math.ldexp(1., -53)
    for factor in [32, 64, 128, 256]:
        for direction in [-1, 1]:
            delta = direction * factor * epsilon * 4
            points = [zero, (1., 1., 0.), (1., 0., 1.),
                      (2. + delta, 1., 1.), zero, (1., 0., 0.),
                      (0., 1., 0.), (0., 0., 1.)]
            cases.append((points, 0.))
    # A slanted normal makes the true distance irrational. Adjacent stored
    # tolerances straddle the exact squared comparison, not a rounded normal.
    for displacement in [0., math.ldexp(1., -53), -math.ldexp(1., -52)]:
        distance = (1. + displacement) / math.sqrt(3.)
        for t in [math.nextafter(distance, 0.), distance,
                  math.nextafter(distance, math.inf)]:
            cases.append(([zero, (1., 1., 0.), (1., 0., 1.),
                           (1. + displacement, 0., 0.), zero,
                           (1., 0., 0.), (0., 1., 0.),
                           (0., 0., 1.)], t))
    # Both guard endpoints, their immediate neighbors, and exact tolerance
    # equality. The next representable value outside must use a fallback.
    for power in [-100, 100]:
        endpoint = math.ldexp(1., power)
        for s in [math.nextafter(endpoint, 0.), endpoint,
                  math.nextafter(endpoint, math.inf)]:
            points = [zero, (s, 0., 0.), (0., s, 0.), (0., 0., s),
                      zero, (0., s, 0.), (s, 0., 0.), (0., 0., -s)]
            for t in [0., math.nextafter(s, 0.), s,
                      math.nextafter(s, math.inf)]:
                cases.append((points, t))

    result = ['# Copyright (c) 2026 Seth Kitchen, PE',
              '# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0',
              '', '"""Generated by tools/generate_exact_predicates_oracle.py.',
              '', 'Expected values use exact rational arithmetic, not production code.',
              '"""', '', 'from std.memory import bitcast', '',
              'comptime _P = SIMD[DType.float64, 4]', '', '',
              'def _f(bits: UInt64) -> Float64:',
              '    return bitcast[DType.float64](bits)', '', '',
              '@fieldwise_init', 'struct _OracleCase(ImplicitlyCopyable):']
    for name in 'abcpdefq':
        result.append(f'    var {name}: _P')
    result += ['    var tolerance: Float64',
               '    var orientation: Int', '    var above: Bool',
               '    var signed_planes: Int', '    var absolute_planes: Int',
               '    var same_signed: Int', '    var same_absolute: Int',
               '    var segment: Int', '    var line: Int',
               '    var difference: Int', '', '',
               'def _oracle_cases() -> List[_OracleCase]:',
               '    var cases = List[_OracleCase]()']
    for points, t in cases:
        a, b, c, p, d, e, f, q = [tuple(map(Fraction, p)) for p in points]
        first, n1 = plane(a, b, c, p)
        second, n2 = plane(d, e, f, q)
        same, _ = plane(a, b, c, q)
        squared_order = sign(first * first * n2 - second * second * n1)
        signed_order = (sign(sign(first) - sign(second))
                        if sign(first) != sign(second) else sign(first) * squared_order)
        above = first > 0 and first * first > Fraction(t)**2 * n1
        edge = subtract(b, a)
        xp, xq = cross(edge, subtract(p, a)), cross(edge, subtract(q, a))
        answers = [sign(first), above, signed_order, squared_order,
                   sign(first - same), sign(abs(first) - abs(same)),
                   sign(segment(a, b, p) - segment(a, b, q)),
                   sign(dot(xp, xp) - dot(xq, xq)),
                   sign((a[0] - b[0]) - (c[0] - p[0]))]
        result += ['    cases.append(', '        _OracleCase(']
        for p in points:
            result.append('            _P(')
            result.extend('                ' + literal(v) + ',' for v in p)
            result += ['                0,', '            ),']
        result.append('            ' + literal(t) + ',')
        result.extend('            ' + str(answer) + ',' for answer in answers)
        result += ['        )', '    )']
    result += ['    return cases^', '']
    return '\n'.join(result), len(cases)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    action = parser.add_mutually_exclusive_group()
    action.add_argument('--write', action='store_true', help='replace the fixture')
    action.add_argument('--check', action='store_true', help='verify the fixture (default)')
    args = parser.parse_args()
    text, count = generate()
    target = ROOT / 'tests/exact_predicates_oracle.mojo'
    if args.write:
        target.write_text(text)
        print(f'Wrote {count} exact predicate oracle cases')
    elif target.read_text() == text:
        print(f'Verified {count} exact predicate oracle cases')
    else:
        raise SystemExit('Exact predicate oracle is stale; run with --write')
