# Copyright (c) 2026 Seth Kitchen, PE
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
"""Example dependency selection does not drag in unrelated extensions."""

from pathlib import Path
import tempfile
import os
import subprocess
import unittest
from unittest.mock import patch

import affected
import example_inputs


class ExampleInputsTests(unittest.TestCase):
    def test_transitive_local_imports_packages_and_asset_prefixes(self):
        files = {
            'examples/cube.mojo': 'from core.mesh import draw\n',
            'examples/person.mojo': 'from extensions.person import draw\n',
            'core/__init__.mojo': '',
            'core/mesh.mojo': 'import colors\n_ = "assets/brick/"\n',
            'core/colors.mojo': '',
            'extensions/__init__.mojo': '',
            'extensions/person.mojo': 'from core.mesh import draw\n',
            'assets/brick/a.png': 'a', 'assets/unrelated.png': 'b',
        }
        with tempfile.TemporaryDirectory() as temp:
            for name, text in files.items():
                path = Path(temp, name)
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(text)
            with patch.object(affected, 'ROOT', temp):
                result = example_inputs.dependencies()
        self.assertIn('core/colors.mojo', result['cube'])
        self.assertIn('core/__init__.mojo', result['cube'])
        self.assertIn('assets/brick/a.png', result['cube'])
        self.assertNotIn('assets/unrelated.png', result['cube'])
        self.assertNotIn('extensions/person.mojo', result['cube'])
        self.assertIn('extensions/person.mojo', result['person'])
        self.assertIn('core/mesh.mojo', result['person'])
        self.assertIn('Makefile', result['cube'])

    def test_make_does_not_rebuild_for_unrelated_extension(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            files = {p: '' for p in example_inputs.TOOLS}
            files.update({
                'examples/cube.mojo': 'from core import draw\n',
                'examples/person.mojo': 'from extension import draw\n',
                'core.mojo': '', 'extension.mojo': 'from core import draw\n'})
            for name, text in files.items():
                path = root / name
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(text)
            with patch.object(affected, 'ROOT', temp):
                inputs = example_inputs.dependencies()
            (root / 'Makefile').write_text(
                example_inputs.makefile_text(inputs)
                + 'cube.png: $(EXAMPLE_INPUTS_cube)\n\ttouch $@\n'
                + 'person.png: $(EXAMPLE_INPUTS_person)\n\ttouch $@\n')
            for name in files:
                os.utime(root / name, (1000, 1000))
            for name in ('cube.png', 'person.png'):
                (root / name).write_text('')
                os.utime(root / name, (2000, 2000))
            os.utime(root / 'extension.mojo', (3000, 3000))
            self.assertEqual(subprocess.run(
                ['make', '-q', 'cube.png'], cwd=root).returncode, 0)
            self.assertEqual(subprocess.run(
                ['make', '-q', 'person.png'], cwd=root).returncode, 1)

    def test_repository_recipes_cover_every_example_and_compress(self):
        root = Path(__file__).resolve().parent.parent
        makefile = (root / 'Makefile').read_text()
        for example in (root / 'examples').glob('*.mojo'):
            if example.stem == 'viewer':  # Interactive terminal, no gallery image.
                continue
            self.assertIn('$(EXAMPLE_INPUTS_' + example.stem + ')', makefile)
        gallery = makefile.split('animation: ', 1)[1].split(
            '# Deliberately leaves', 1)[0]
        self.assertNotIn('$(LIB_SOURCES)', gallery)
        for name in ('carla', 'carla_town', 'carla_towns'):
            recipe = gallery.split('$(OUT_DIR)/' + name + '.png:', 1)[1].split('\n\n', 1)[0]
            self.assertIn('credits --all --output $(@:.png=.credits.md)', recipe)
            self.assertIn('assets/carla/ATTRIBUTION.md', recipe)
        self.assertEqual(gallery.count('$(call run,'),
                         gallery.count('tools/optimize_png.py $@'))

    def test_output_is_stable_and_rejects_make_syntax(self):
        self.assertEqual(example_inputs.makefile_text({'cube': ['a.mojo']}),
                         '# Generated by tools/example_inputs.py; do not edit.\n'
                         'EXAMPLE_INPUTS_cube := a.mojo\n')
        for path in ('a b', 'a#b', '$x', 'a:b', 'a\\b'):
            with self.assertRaises(ValueError):
                example_inputs.makefile_text({'cube': [path]})


if __name__ == '__main__':
    unittest.main()
